### ISSUE TITLE
DevToolsActivePort error when running master branch

### ISSUE THREAD

**Issue by DavidARoberts** [jjjchens235/bing-rewards#119]
This issue is currently happening when I run with master branch, I have tested with some of the dev branches you have pushed but I get chromedriver errors with those branches. I did notice that chromedriver 97 is being downloaded when chromedriver 96 is the current release

1. Run BingRewards.py
2. Observe Results in logs/error.log

Sun, Nov 21 2021 03:08PM
Traceback (most recent call last):
  File "C:\Users\David\Documents\BingRewards\bing-rewards-master\BingRewards\BingRewards.py", line 76, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "C:\Users\David\Documents\BingRewards\bing-rewards-master\BingRewards\src\rewards.py", line 1266, in complete_all
    driver = self.__complete_edge_search()
  File "C:\Users\David\Documents\BingRewards\bing-rewards-master\BingRewards\src\rewards.py", line 1064, in __complete_edge_search
    driver = Driver.get_driver(
  File "C:\Users\David\Documents\BingRewards\bing-rewards-master\BingRewards\src\driver.py", line 135, in get_driver
    driver = webdriver.Chrome(path, options=options)
  File "C:\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist

**Comment by DavidARoberts** [comment]
It looks like this issue was previously reported #111 , I will close this issue but I am still seeing the chromedriver.exe be downloaded for chrome 97. I will just create a separate issue for that.

**Comment by cupiditys** [comment]
i had the same issue, u can download the beta release of chrome version 97 and it works

**Comment by DavidARoberts** [comment]
@cupiditys I just downloaded the chromedriver for 96, I just mentioned it because I noticed @jjjchens235 had code that was specifically trying to download the second latest version.
