### ISSUE TITLE
EDGE Search failing on recent builds

### ISSUE THREAD

**Issue by connect-dots** [jjjchens235/bing-rewards#12]
Hi,

First of all, thanks for resurrecting and maintaining this repo. I really appreciate it!

Secondly, I think one of your commits after Nov 13 2018 seems to have broken Edge search (for me at least). I'm using Win10. Tested on two diff PC's

Looks like it's failing to download the driver or locate it, but my Python is basic at best (I'm still learning).

The Nov 13th 2018 and < build's still work fine.

Here's the error log:

> Starting Edge search
Traceback (most recent call last):
  File "BingRewards.py", line 136, in <module>
    __main(args[0], arg1)
  File "BingRewards.py", line 95, in __main
    rewards.complete_edge_and_web_search(hist_log.get_search_hist())
  File "D:\bots\user1\BingRewards\src\rewards.py", line 701, in complete_edge_and_web_search
    self.__complete_edge_search(close=True)
  File "D:\bots\user1\BingRewards\src\rewards.py", line 571, in __complete_edge_search
    driver = Driver.get_driver(self.path, Driver.WEB_DEVICE, self.headless)
  File "D:\bots\user1\BingRewards\src\driver.py", line 68, in get_driver
    Driver.__download_driver(path, system)
  File "D:\bots\user1\BingRewards\src\driver.py", line 43, in __download_driver
    response = urlopen(url, context=ssl.SSLContext(ssl.PROTOCOL_TLSv1)) # context args for mac
  File "C:\Users\user1\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Thanks again for any help. Would love to keep using your newest builds. Cheers

**Comment by jjjchens235** [comment]
Hi,
Thanks for bringing this up.

I reproduced this error as well when I deleted the chromedriver file inside src/drivers.

I think the url that is being used to download a new chrome driver inside driver.py is no longer valid- it returns a broken link. I have updated the URL.
