### ISSUE TITLE
Only completes when run in non-headless mode.

### ISSUE THREAD

**Issue by Bahnschrift** [jjjchens235/bing-rewards#126]
The program is only functioning when with the `-nhl` flag. When run without, it outputs as below, then freezes. I've tried leaving it for up to half an hour and it doesn't move. 

_Console Ouput:_
```
λ python .\BingRewards\BingRewards.py

Command line options selected:
search_type=remaining, headless=True, email=None, cookies=True


        You selected remaining

> Starting Edge search
Downloading chromedriver version: 97.0.4692.20

DevTools listening on ws://127.0.0.1:56352/devtools/browser/f0a75250-e717-4838-800f-563217a8c145

DevTools listening on ws://127.0.0.1:59635/devtools/browser/1de240b2-a77c-4c8b-9744-b9f7fa0c50e0
Downloading chromedriver version: 96.0.4664.45
```

Since it freezes, I eventually have to kill the program with control+C. The KeyboardInterrupt error from `error.log` is below:

_error.log:_
```
Thu, Nov 25 2021 12:29PM
Traceback (most recent call last):
  File "C:\Users\kbeck\OneDrive\Desktop\bing-rewards\BingRewards\BingRewards.py", line 77, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "C:\Users\kbeck\OneDrive\Desktop\bing-rewards\BingRewards\src\rewards.py", line 1270, in complete_all
    driver = self.__complete_edge_search()
  File "C:\Users\kbeck\OneDrive\Desktop\bing-rewards\BingRewards\src\rewards.py", line 1068, in __complete_edge_search
    driver = Driver.get_driver(
  File "C:\Users\kbeck\OneDrive\Desktop\bing-rewards\BingRewards\src\driver.py", line 140, in get_driver
    driver = webdriver.Chrome(path, options=options)
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 416, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\remote_connection.py", line 398, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\remote_connection.py", line 420, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\urllib3\request.py", line 78, in request
    return self.request_encode_body(
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\urllib3\poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python310\lib\http\client.py", line 1368, in getresponse
    response.begin()
  File "C:\Program Files\Python310\lib\http\client.py", line 317, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python310\lib\http\client.py", line 278, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```

However, when run with `-nhl`, it functions as normal (with the chrome window visible), so I haven't attached the log for this. It's worth noting that up until around two weeks ago it worked fine without `-nhl`, then at some point it broke of it's own accord and wouldn't work even with `-nhl`. The commits 2 days ago (`b255dfca2a936fe8b9f4581f28c7bf5ff4f40342`) seem to have fixed `-nhl` for me, but not the regular mode.

**Comment by Bahnschrift** [comment]
Just got a friend to try this and he ran into the same issue without `-nhl` (maybe a region specific issue? we are both in Australia), but when running with `-nhl` he got a pop-up saying `Failed To Create Data Directory. Google Chrome cannot read and write to its data directory: stored_browser_data`. His console output is at: https://pastebin.com/raw/V3b0HTUT

**Comment by jjjchens235** [comment]
try adding `-nc` flag

**Comment by Bahnschrift** [comment]
Froze up again. I tried leaving it for a while this time and it eventually crashed with this error: 
```
Traceback (most recent call last):
  File "C:\Users\kbeck\OneDrive\Desktop\bing-rewards\BingRewards\src\driver.py", line 140, in get_driver
    driver = webdriver.Chrome(path, options=options)
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\kbeck\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from timeout: Timed out receiving message from renderer: 600.000
  (Session info: headless chrome=96.0.4664.45)
Stacktrace:
Backtrace:
	Ordinal0 [0x008C0C43+2493507]
	Ordinal0 [0x0085A4B1+2073777]
	Ordinal0 [0x00762608+1058312]
	Ordinal0 [0x00754E8B+1003147]
	Ordinal0 [0x00753EDD+999133]
	Ordinal0 [0x00754196+999830]
	Ordinal0 [0x00753A85+998021]
	Ordinal0 [0x0075E714+1042196]
	Ordinal0 [0x00753A41+997953]
	Ordinal0 [0x00754966+1001830]
	Ordinal0 [0x00753EDD+999133]
	Ordinal0 [0x00754196+999830]
	Ordinal0 [0x00753A85+998021]
	Ordinal0 [0x0075A08F+1024143]
	Ordinal0 [0x0075A0E7+1024231]
	Ordinal0 [0x00753A41+997953]
	Ordinal0 [0x00754966+1001830]
	Ordinal0 [0x00753EDD+999133]
	Ordinal0 [0x00754196+999830]
	Ordinal0 [0x00753A85+998021]
	Ordinal0 [0x0075C733+1034035]
	Ordinal0 [0x00753A41+997953]
	Ordinal0 [0x00754966+1001830]
	Ordinal0 [0x00753EDD+999133]
	Ordinal0 [0x00754196+999830]
	Ordinal0 [0x00753A85+998021]
	Ordinal0 [0x0075A579+1025401]
	Ordinal0 [0x00753A41+997953]
	Ordinal0 [0x00754966+1001830]
	Ordinal0 [0x00753EDD+999133]
	Ordinal0 [0x00754196+999830]
	Ordinal0 [0x00753A85+998021]
	Ordinal0 [0x007598FC+1022204]
	Ordinal0 [0x00753A41+997953]
	Ordinal0 [0x00754966+1001830]
	Ordinal0 [0x00753EDD+999133]
	Ordinal0 [0x00754196+999830]
	Ordinal0 [0x00753A85+998021]
	Ordinal0 [0x0074F72D+980781]
	Ordinal0 [0x00753A41+997953]
	Ordinal0 [0x007537E0+997344]
	Ordinal0 [0x00753589+996745]
	Ordinal0 [0x00763820+1062944]
	Ordinal0 [0x007AAED9+1355481]
	Ordinal0 [0x007A9B7A+1350522]
	Ordinal0 [0x007A580B+1333259]
	Ordinal0 [0x00782314+1188628]
	Ordinal0 [0x0078316F+1192303]
	GetHandleVerifier [0x00A47BF6+1548950]
	GetHandleVerifier [0x00AF461C+2256060]
	GetHandleVerifier [0x0094C13B+518107]
	GetHandleVerifier [0x0094B1E0+514176]
	Ordinal0 [0x0085F53D+2094397]
	Ordinal0 [0x00863418+2110488]
	Ordinal0 [0x00863552+2110802]
	Ordinal0 [0x0086CE81+2150017]
	BaseThreadInitThunk [0x751A6739+25]
	RtlGetFullPathName_UEx [0x772A8AFF+1215]
	RtlGetFullPathName_UEx [0x772A8ACD+1165]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kbeck\OneDrive\Desktop\bing-rewards\BingRewards\BingRewards.py", line 85, in __main
    rewards.complete_offers()
  File "C:\Users\kbeck\OneDrive\Desktop\bing-rewards\BingRewards\src\rewards.py", line 1256, in complete_offers
    driver = self.__complete_offers()
  File "C:\Users\kbeck\OneDrive\Desktop\bing-rewards\BingRewards\src\rewards.py", line 1153, in __complete_offers
    driver = Driver.get_driver(
  File "C:\Users\kbeck\OneDrive\Desktop\bing-rewards\BingRewards\src\driver.py", line 146, in get_driver
    raise SessionNotCreatedException(f'Tried downloading the {dl_try_count} most recent chromedrivers. None match your Chrome browswer version. Aborting now, please update your chrome browser.')
selenium.common.exceptions.SessionNotCreatedException: Message: Tried downloading the 3 most recent chromedrivers. None match your Chrome browswer version. Aborting now, please update your chrome browser.
```

**Comment by jjjchens235** [comment]
Thanks for posting all these logs. It looks like this is the original error: `selenium.common.exceptions.SessionNotCreatedException: Message: session not created from timeout: Timed out receiving message from renderer: 600.000`. 

The log from your friend displays a different error. I think I have a solution for your friend's error as someone submitted a PR for this recently. 
Regarding your error, I'm a little less certain. Unfortunately I cannot reproduce on my machine, so here are some ideas:

#### Set-up
1. restart your machine, to clear all instances of chromedriver.
2. consider upgrading your Selenium package if you're using an old version, something like `pip install selenium --upgrade`
2. find all instances of `stored_browser_data/` sub-directories within the main BingRewards/ directory, this linux command should do that  `find . -name "stored*" -type d `
3. Delete all `stored_browser_data/` directories
4. Check-out dev branch, i.e `git checkout dev`. Also `git pull` if you've used dev branch before (unlikely).

#### Attempt1: run as usual
1. Run `python BingRewards.py`

#### Attempt2: run with no cookies option
1. Restart computer - let's start from scratch 
2. Delete all `stored_browser_data/` directories one more time.
2. Run `python BingRewards.py -nc`

#### Attempt3: mess with chrome options
1. Take a quick look at this StackOverflow [thread](https://stackoverflow.com/a/52340526)
2. Of note, on this line of [code](https://github.com/jjjchens235/bing-rewards/blob/master/BingRewards/src/driver.py#L97) add this code `options.add_argument("--disable-gpu")

#### Attempt4: revert to an older commit
1.  `git checkout 86f4a4f` 
2. run `python BingRewards.py`

**Comment by Bahnschrift** [comment]
Wow. Thank you for such a detailed response. I went through all of those and it seems that adding `options.add_argument("--disable-gpu")` fixed the issue. I tried running the same program on my laptop and ran in to the same issue, so I would guess it's either caused by windows 11 or an AMD GPU (5700XT on PC and iGPU on laptop). Though it seems like it's a different issue, I'll get my friend to try adding that line and see if it fixes it for him too.

Thanks for your help.

**Comment by Aholicknight** [comment]
Continuing from the issue #124 this is the new error: https://hastebin.com/cokiwoqoqi.hs 

From the error, a new error arises which is: 
`FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'drivers\\chromedriver_win32\\chromedriver.exe' -> 'drivers\\chromedriver.exe'` 

`PermissionError: [WinError 5] Access is denied: 'drivers\\chromedriver_win32\\chromedriver.exe' -> 'drivers\\chromedriver.exe'` 

`Message: session not created
from timeout: Timed out receiving message from renderer: 600.000
  (Session info: headless chrome=96.0.4664.45)`

I am going to run it again with admin privileges and see if that fixes it.

**Comment by jjjchens235** [comment]
@Bahnschrift  - great news! For your friend's error, I would suggest having him run `set-up steps` and `Attempt1`, that should be the fix. His error is related to [this PR](https://github.com/jjjchens235/bing-rewards/pull/118) 

@Aholicknight - ok, keep me updated. If still an issue, please post the full log.

**Comment by Aholicknight** [comment]
@jjjchens235 That is the full issue, please view the hastebin link to view it all.

**Comment by jjjchens235** [comment]
I took a look at the full log. There are two issues:
1. Session timeout exception, similar to OP's issue
2. PermissionExceptionError

Can we try the following:

#### set-up
1. manually delete all files/folders  in `drivers/` dir
2. `git checkout dev` (want to make sure we're running the same code)
3. `git pull`


#### Attempt1
1. `python BingRewards.py`

#### Attempt2
1. `python BingRewards.py -nhl`


If still an issue, plz include: 

1. full log 
2. output of `ls -l drivers/`

**Comment by Aholicknight** [comment]
I'm going to delete the entire BingRewards folder and see if that fixes it.

**Comment by Aholicknight** [comment]
Deleting the entire folder & redownloading it appears to fix the problem.
