### ISSUE TITLE
[Showstopper] GPU process isn't usable. Goodbye.

### ISSUE THREAD

**Issue by sensboston** [jjjchens235/bing-rewards#132]
On latest "master" I started getting an error on starting Selenium driver: **GPU process isn't usable. Goodbye.**
<details>
  <summary>Full error log</summary>

```
python BingRewards.py -nhl                                                                                                                       
Command line options selected:
search_type=remaining, headless=False, email=None, cookies=True

        You selected remaining

> Starting Edge search

DevTools listening on ws://127.0.0.1:37651/devtools/browser/75dd13c3-46e7-4f8f-94e1-28df6ed803a3
[704:16612:1208/115011.388:FATAL:gpu_data_manager_impl_private.cc(417)] GPU process isn't usable. Goodbye.

Traceback (most recent call last):
  File "C:\Users\User\BR\BingRewards\src\driver.py", line 142, in get_driver
    driver = webdriver.Chrome(path, options=options)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\BR\BingRewards\BingRewards.py", line 81, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "C:\Users\User\BR\BingRewards\BingRewards.py", line 27, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\User\BR\BingRewards\src\rewards.py", line 1284, in complete_search_type
    self.complete_all(search_hist)
  File "C:\Users\User\BR\BingRewards\src\rewards.py", line 1272, in complete_all
    driver = self.__complete_edge_search()
  File "C:\Users\User\BR\BingRewards\src\rewards.py", line 1070, in __complete_edge_search
    driver = Driver.get_driver(
  File "C:\Users\User\BR\BingRewards\src\driver.py", line 167, in get_driver
    raise WebDriverException(error_msg)
selenium.common.exceptions.WebDriverException: Message: Message: unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

```
</details>

This happens on ThinkPad P71 with two graphics cards (Intel & Nvidia) only; on previous "release" (sorry, can't tell git commit # but I attached zip archive) it works fine except crash on offers processing (i.e. mobile searches also not available)

[BR.zip](https://github.com/jjjchens235/bing-rewards/files/7677751/BR.zip)

**Comment by sensboston** [comment]
**Update:** It looks like this line (adding a new option) in driver.py is a source of the issue:
```
        if cookies:
            cookies_path = os.path.join(os.getcwd(), 'stored_browser_data/')
            **#options.add_argument("user-data-dir=" + cookies_path)**

```
Commenting this line makes Python script working again.

**Comment by jjjchens235** [comment]
Hi - the cookies option seems to have caused issues for many people running Windows. 

I think adding the no cookies flag like so should be a fix, unless you absolutely need cookies:
`python BingRewards.py -nc`

**Comment by sensboston** [comment]
Yes, sounds reasonable. BTW, why do we (you) need cookies at all?

**Comment by jjjchens235** [comment]
Cookies was implemented based off of the concern listed in this [comment](https://github.com/jjjchens235/bing-rewards/issues/78#issue-924319413)

**Comment by sensboston** [comment]
> Cookies was implemented based off of the concern listed in this comment

Thanks for letting me know but this statement, i.e.

>Microsoft detect bots by listing accounts that connect multiple time with new browser with the same IP.

 is completely incorrect - Microsoft can't do this because of NAT; it's very possible (and of course exist in real word) to have a lot of new users from the same IP. And my personal practice tell this too ;) 

So, I suggest you to disable cookies by default and add ability to turn 'em on for the users who really believe in this false statement.

**Comment by jjjchens235** [comment]
I think you're right, will do so.

**Comment by jjjchens235** [comment]
Cookies are disabled by default now.
