### ISSUE TITLE
Failing searches: Unable to get progress elements from dashboard

### ISSUE THREAD

**Issue by Powered87** [jjjchens235/bing-rewards#147]
Any idea what this error relates to and how to fix? I have this scheduled to run twice a day through task scheduler (in case the first one fails) and I've been receiving this error lately.

```
Fri, Jan 07 2022 09:28AM
Traceback (most recent call last):
  File "C:\Python310\bing-rewards\BingRewards\BingRewards.py", line 90, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "C:\Python310\bing-rewards\BingRewards\BingRewards.py", line 29, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Python310\bing-rewards\BingRewards\src\rewards.py", line 1313, in complete_search_type
    self.complete_all(search_hist)
  File "C:\Python310\bing-rewards\BingRewards\src\rewards.py", line 1305, in complete_all
    driver = self.__complete_mobile_search()
  File "C:\Python310\bing-rewards\BingRewards\src\rewards.py", line 1154, in __complete_mobile_search
    self.completion.mobile_search = self.__search(
  File "C:\Python310\bing-rewards\BingRewards\src\rewards.py", line 316, in __search
    progress = self.__get_search_progress(driver, device, is_edge)
  File "C:\Python310\bing-rewards\BingRewards\src\rewards.py", line 235, in __get_search_progress
    raise NoSuchElementException(msg)
selenium.common.exceptions.NoSuchElementException: Message: When searching, too many time out exceptions when getting progress elements
```

**Comment by jjjchens235** [comment]
It seems that I'm getting this error occasionally as well when I'm running the default headless=True.

A temporary solution that has been working for me is to run with -nhl mode. Maybe you can adjust your windows scheduler argument to include that for now.

**Comment by Powered87** [comment]
Thank you, did I do this right? Sorry, I'm not too familiar with this.

![image](https://user-images.githubusercontent.com/20592762/148706226-68908462-5dd6-416f-8926-0ac6b8680a21.png)

**Comment by LeeRyanSA** [comment]
I'm using the most recent version: updated yesterday

I get this error: 

Traceback (most recent call last):
  File "C:\Users\Ryan Lee\Downloads\bing\BingRewards\BingRewards.py", line 120, in <module>
    __main()
  File "C:\Users\Ryan Lee\Downloads\bing\BingRewards\BingRewards.py", line 86, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "C:\Users\Ryan Lee\Downloads\bing\BingRewards\BingRewards.py", line 28, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\Ryan Lee\Downloads\bing\BingRewards\src\rewards.py", line 1410, in complete_search_type
    self.complete_all(search_hist)
  File "C:\Users\Ryan Lee\Downloads\bing\BingRewards\src\rewards.py", line 1401, in complete_all
    driver = self.__complete_mobile_search()
  File "C:\Users\Ryan Lee\Downloads\bing\BingRewards\src\rewards.py", line 1222, in __complete_mobile_search
    self.completion.mobile_search = self.__search(
  File "C:\Users\Ryan Lee\Downloads\bing\BingRewards\src\rewards.py", line 331, in __search
    progress = self.__get_search_progress(driver, device, is_edge)
  File "C:\Users\Ryan Lee\Downloads\bing\BingRewards\src\rewards.py", line 250, in __get_search_progress
    raise NoSuchElementException(msg)
selenium.common.exceptions.NoSuchElementException: Message: When searching, too many time out exceptions when getting progress elements

**Comment by jjjchens235** [comment]
So it seems that `-nhl` does not fix this issue after all. Will try to get a fix for this ASAP or update otherwise

**Comment by jjjchens235** [comment]
The update no longer uses  https://account.microsoft.com/rewards/pointsbreakdown to derive the points - I think that's the URL that was causing previous issues.

The update is in `dev` branch if anyone wants to run that code. Will merge to master in a few days.

**Comment by LeeRyanSA** [comment]
I used the dev branch, and I can confirm it is fixed. Thank you. I believe we can close this issue/bug now.
