### ISSUE TITLE
Punch card offer #1 not working

### ISSUE THREAD

**Issue by icanotc** [jjjchens235/bing-rewards#148]
pulled from the master branch today, the first run was fine except that it failed to complete the punch card, but I've never attempted trying to get the punch cards at all.

This is the error that it gave me:

```
> Starting punch card
       >> Punch card "New Year, new you" is not complete yet.
       >> Starting activity "Day 1. Resolutions, but not only!"
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
              >>> Could not find quiz2 progress elements
              >>> Latest punch card activity NOT successfully completed. Possibly not enough time has elapsed since last punch.
       >> Overall punch card progress: 0 of 4 completed
    < Failed to complete latest punch card activity
```
on the second run, I got a different error:
```
You selected remaining

> Starting punch card
Traceback (most recent call last):
  File "/path/to/folder/bing-rewards-master/BingRewards/BingRewards.py", line 120, in <module>
    __main()
  File "/path/to/folder/bing-rewards-master/BingRewards/BingRewards.py", line 86, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "/path/to/folder/bing-rewards-master/BingRewards/BingRewards.py", line 28, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "/path/to/folder/bing-rewards-master/BingRewards/src/rewards.py", line 1422, in complete_search_type
    self.complete_punchcard(search_hist)
  File "/path/to/folder/bing-rewards-master/BingRewards/src/rewards.py", line 1383, in complete_punchcard
    driver = self.__complete_punchcard()
  File "/path/to/folder/bing-rewards-master/BingRewards/src/rewards.py", line 1269, in __complete_punchcard
    driver = Driver.get_driver(
NameError: name 'Driver' is not defined
```
I fixed this error by changing the complete punch card function this:

```python
def __complete_punchcard(self, driver=None):
        self.__sys_out("Starting punch card", 1)
        try:
            if not driver:
                driver = self.driver.get_driver(
                    self.driver.WEB_DEVICE, self.headless, self.cookies
                )
                self.__login(driver)
```

hope this helps!

**Comment by jjjchens235** [comment]
Thanks for reporting, the 2nd issue is fixed per your suggestion.

I'm curious why the punch card isn't working for you tho... If you have the chance, can you run in -nhl mode and report if you even get to a page that says 'start quiz' at the bottom? A screenshot of the page where the program stops at would be tremendous!

**Comment by icanotc** [comment]
it seems like i can't replicate the bug anymore, i tried a fresh install of the script but that issue is gone. maybe this first issue is caused by the second issue.

**Comment by jjjchens235** [comment]
I'm certainly not going to complain!
