### ISSUE TITLE
check_login_url() - timeoutexception

### ISSUE THREAD

**Issue by vinciraia99** [jjjchens235/bing-rewards#151]
Hi I tried to insert this python script on raspberry pi 3b by installing the chromedriver and via pip the various dependencies but every time it gives me this error

`search_type=remaining, headless=True, email=None, cookies=False, telegram=True, driver=<class 'src.driver.ChromeDriver'>

['Fri, Jan 14 2022 11:01AM', 'Failed Edge Search, Web Search, Mobile Search, Offers, Latest Punch Card Activity']

You selected remaining

> Starting Edge search
       >> Logging in
Traceback (most recent call last):
  File "/home/pi/bing-rewards/BingRewards/BingRewards.py", line 120, in <module>
    __main()
  File "/home/pi/bing-rewards/BingRewards/BingRewards.py", line 86, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "/home/pi/bing-rewards/BingRewards/BingRewards.py", line 28, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "/home/pi/bing-rewards/BingRewards/src/rewards.py", line 1440, in complete_search_type
    self.complete_all(search_hist)
  File "/home/pi/bing-rewards/BingRewards/src/rewards.py", line 1427, in complete_all
    driver = self.__complete_edge_search()
  File "/home/pi/bing-rewards/BingRewards/src/rewards.py", line 1194, in __complete_edge_search
    self.__login(driver)
  File "/home/pi/bing-rewards/BingRewards/src/rewards.py", line 167, in __login
    is_login_complete = self.__check_login_url(driver, driver.current_url)
  File "/home/pi/bing-rewards/BingRewards/src/rewards.py", line 102, in __check_login_url
    WebDriverWait(driver, 2).until(
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x000000a949cc <unknown>
#1 0x0000007f3884 <unknown>
#2 0x000000826dd0 <unknown>
#3 0x000000857ba8 <unknown>
#4 0x0000008430f0 <unknown>
#5 0x000000855988 <unknown>
#6 0x000000842f74 <unknown>
#7 0x00000081b648 <unknown>
#8 0x00000081c574 <unknown>
#9 0x000000ac42b8 <unknown>
#10 0x000000ad6680 <unknown>
#11 0x000000ad6314 <unknown>
#12 0x000000ad7aa0 <unknown>
#13 0x000000ac52cc <unknown>
#14 0x000000ad7d5c <unknown>
#15 0x000000abac34 <unknown>
#16 0x000000aefa90 <unknown>
#17 0x000000aefc00 <unknown>
#18 0x000000b0a98c <unknown>
#19 0x000076f36300 <unknown>
#20 0x000000000000 <unknown>
`

**Comment by jjjchens235** [comment]
Hi - someone made a PR recently for raspberry PI, and they installed chromedriver via `sudo apt-get install chromium-chromedriver`.
If you already did that, and still get error, can you lmk what value this returns for you?
```
import platform
print(platform.machine())

**Comment by Powered87** [comment]
I think I'm receiving the same error?
Windows 10 machine
`Fri, Jan 21 2022 09:12AM
Traceback (most recent call last):
  File "C:\Python310\bing-rewards MS5\BingRewards\BingRewards.py", line 86, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "C:\Python310\bing-rewards MS5\BingRewards\BingRewards.py", line 28, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Python310\bing-rewards MS5\BingRewards\src\rewards.py", line 1410, in complete_search_type
    self.complete_all(search_hist)
  File "C:\Python310\bing-rewards MS5\BingRewards\src\rewards.py", line 1397, in complete_all
    driver = self.__complete_edge_search()
  File "C:\Python310\bing-rewards MS5\BingRewards\src\rewards.py", line 1164, in __complete_edge_search
    self.__login(driver)
  File "C:\Python310\bing-rewards MS5\BingRewards\src\rewards.py", line 167, in __login
    is_login_complete = self.__check_login_url(driver, driver.current_url)
  File "C:\Python310\bing-rewards MS5\BingRewards\src\rewards.py", line 102, in __check_login_url
    WebDriverWait(driver, 2).until(
  File "C:\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
Backtrace:
	Ordinal0 [0x00F56903+2517251]
	Ordinal0 [0x00EEF8E1+2095329]
	Ordinal0 [0x00DF2848+1058888]
	Ordinal0 [0x00E1D448+1233992]
	Ordinal0 [0x00E1D63B+1234491]
	Ordinal0 [0x00E47812+1406994]
	Ordinal0 [0x00E3650A+1336586]
	Ordinal0 [0x00E45BBF+1399743]
	Ordinal0 [0x00E3639B+1336219]
	Ordinal0 [0x00E127A7+1189799]
	Ordinal0 [0x00E13609+1193481]
	GetHandleVerifier [0x010E5904+1577972]
	GetHandleVerifier [0x01190B97+2279047]
	GetHandleVerifier [0x00FE6D09+534521]
	GetHandleVerifier [0x00FE5DB9+530601]
	Ordinal0 [0x00EF4FF9+2117625]
	Ordinal0 [0x00EF98A8+2136232]
	Ordinal0 [0x00EF99E2+2136546]
	Ordinal0 [0x00F03541+2176321]
	BaseThreadInitThunk [0x7601FA29+25]
	RtlGetAppContainerNamedObjectPath [0x76F17A9E+286]
	RtlGetAppContainerNamedObjectPath [0x76F17A6E+238]
`

**Comment by jjjchens235** [comment]
I looked at your error msg more closely. It seems like you're failing on this section. 
I'm not sure if you can run this on `no headless mode` on a raspberry pi, but that would certainly help diagnose the issue. 
The only thing I can think of is the 2 seconds wait time isn't enough for the page to load on the raspberry pi.

```
 #'stay signed in' page
        elif "https://login.live.com/ppsecure" in url:
            WebDriverWait(driver, 2).until(
                EC.element_to_be_clickable((By.ID, 'KmsiCheckboxField'))
            ).click()

**Comment by jjjchens235** [comment]
no response from op - assumed to be fixed

**Comment by nootkroot** [comment]
I'm having the exact same problem on Windows 10.

```You selected remaining

> Starting Edge search
Downloading Windows msedgedriver version: 98.0.1108.56

DevTools listening on ws://127.0.0.1:60068/devtools/browser/6ae17b4b-60c2-499a-abc6-ef2e73aaed2a
       >> Logging in
Traceback (most recent call last):
  File "D:\Documents\Automator\bing-rewards-1.5\BingRewards\BingRewards.py", line 117, in <module>
    __main()
  File "D:\Documents\Automator\bing-rewards-1.5\BingRewards\BingRewards.py", line 80, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "D:\Documents\Automator\bing-rewards-1.5\BingRewards\BingRewards.py", line 28, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "D:\Documents\Automator\bing-rewards-1.5\BingRewards\src\rewards.py", line 1342, in complete_search_type
    self.complete_remaining_searches(search_type, prev_completion)
  File "D:\Documents\Automator\bing-rewards-1.5\BingRewards\src\rewards.py", line 1322, in complete_remaining_searches
    driver = self.__complete_edge_search(driver)
  File "D:\Documents\Automator\bing-rewards-1.5\BingRewards\src\rewards.py", line 1268, in __complete_edge_search
    driver, completion = self.__complete_action(action, description, driver, print_stats, close, device_type, **action_kwargs)
  File "D:\Documents\Automator\bing-rewards-1.5\BingRewards\src\rewards.py", line 1241, in __complete_action
    self.__login(driver)
  File "D:\Documents\Automator\bing-rewards-1.5\BingRewards\src\rewards.py", line 163, in __login
    is_login_complete = self.__check_login_url(driver, driver.current_url)
  File "D:\Documents\Automator\bing-rewards-1.5\BingRewards\src\rewards.py", line 98, in __check_login_url
    WebDriverWait(driver, 2).until(
  File "C:\Users\ariel\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Microsoft::Applications::Events::EventProperties::unpack [0x00007FF66DE833C2+22610]
        Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x00007FF66DDC1C92+503778]
        Ordinal0 [0x00007FF66D8C0FA5+659365]
        Ordinal0 [0x00007FF66D8FBD52+900434]
        Ordinal0 [0x00007FF66D8FC028+901160]
        Ordinal0 [0x00007FF66D92DBC7+1104839]
        Ordinal0 [0x00007FF66D91701F+1011743]
        Ordinal0 [0x00007FF66D92B2C4+1094340]
        Ordinal0 [0x00007FF66D916DF3+1011187]
        Ordinal0 [0x00007FF66D8EDE97+843415]
        Ordinal0 [0x00007FF66D8EF368+848744]
        Microsoft::Applications::Events::EventProperty::to_string [0x00007FF66DA88BC8+848072]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF66DB7AB9D+39117]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF66DB7DE12+52034]
        Microsoft::Applications::Events::EventProperty::to_string [0x00007FF66D9C0906+28166]
        Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x00007FF66DDC8921+531569]
        Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x00007FF66DDCDE04+553300]
        Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x00007FF66DDCDF95+553701]
        Microsoft::Applications::Events::EventProperty::to_string [0x00007FF66DA96650+904016]
        BaseThreadInitThunk [0x00007FF920687034+20]
        RtlUserThreadStart [0x00007FF9213A2651+33]```

**Comment by nootkroot** [comment]
Ok so this is apparently caused by 2FA so I would have to enable the 2FA option.
