### ISSUE TITLE
Failing searches since 1/14/22

### ISSUE THREAD

**Issue by ForceConstant** [jjjchens235/bing-rewards#152]
I ran with -nhl and got a "Its not you, its us " from rewards.microsoft.com and eventually code times out with below.

Traceback (most recent call last):
  File "E:\BingRewards\BingRewards.py", line 86, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "E:\BingRewards\BingRewards.py", line 28, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "E:\BingRewards\src\rewards.py", line 1440, in complete_search_type
    self.complete_all(search_hist)
  File "E:\BingRewards\src\rewards.py", line 1428, in complete_all
    self.__complete_web_search(driver)
  File "E:\BingRewards\src\rewards.py", line 1223, in __complete_web_search
    self.completion.web_search = self.__search(
  File "E:\BingRewards\src\rewards.py", line 333, in __search
    progress = self.__get_search_progress(driver, device, is_edge)
  File "E:\BingRewards\src\rewards.py", line 252, in __get_search_progress
    raise NoSuchElementException(msg)
selenium.common.exceptions.NoSuchElementException: Message: When searching, too many time out exceptions when getting progress elements

**Comment by tareqx2** [comment]
Getting the same error, when testing it out with no-headless, I do notice it has trouble getting to the points breakdown page. It appears to be on MS's end however, as it'll often come up with a "it's not you, it's us" error page.

**Comment by jjjchens235** [comment]
#147 duplicate
