### ISSUE TITLE
Missing Punch Card 

### ISSUE THREAD

**Issue by Affoghiamoci** [jjjchens235/bing-rewards#161]
In italy this month there seems to be no punch cards and this crashes the system, is it possible to disable that piece of code via a flag or find a solution when it does not find the punch cards?

**Comment by Saytoo** [comment]
yeah same in France and I recently got this error:   
Traceback (most recent call last):
  File "C:\Users\Sayto\Downloads\Auto Microsoft Rewards\bing-rewards-master\BingRewards\BingRewards.py", line 120, in <module>
    __main()
  File "C:\Users\Sayto\Downloads\Auto Microsoft Rewards\bing-rewards-master\BingRewards\BingRewards.py", line 86, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "C:\Users\Sayto\Downloads\Auto Microsoft Rewards\bing-rewards-master\BingRewards\BingRewards.py", line 28, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\Sayto\Downloads\Auto Microsoft Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1422, in complete_search_type
    self.complete_punchcard(search_hist)
  File "C:\Users\Sayto\Downloads\Auto Microsoft Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1383, in complete_punchcard
    driver = self.__complete_punchcard()
  File "C:\Users\Sayto\Downloads\Auto Microsoft Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1274, in __complete_punchcard
    self.completion.punchcard = self.__punchcard(driver)
  File "C:\Users\Sayto\Downloads\Auto Microsoft Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1152, in __punchcard
    driver.get(parent_url)
UnboundLocalError: local variable 'parent_url' referenced before assignment

**Comment by DimaRazb** [comment]
Same in CA, seen for a couple of days.

**Comment by jjjchens235** [comment]
> In italy this month there seems to be no punch cards and this crashes the system, is it possible to disable that piece of code via a flag or find a solution when it does not find the punch cards?

Thanks for calling out, I'll find a solution when there aren't punch cards.

**Comment by jjjchens235** [comment]
Ok I have a solution in place in dev branch - can you guys let me know if it fixes the issue?

**Comment by Saytoo** [comment]
> Ok I have a solution in place in dev branch - can you guys let me know if it fixes the issue?

Working now, thanks for the fix.

**Comment by Affoghiamoci** [comment]
> Ok I have a solution in place in dev branch - can you guys let me know if it fixes the issue?

I confirm, thanks!
