### ISSUE TITLE
Not showing 2FA code

### ISSUE THREAD

**Issue by nootkroot** [jjjchens235/bing-rewards#173]
When I try to run the program with 2FA enabled on my account I get this output:

```
> Starting Edge search
Downloading Windows msedgedriver version: 98.0.1108.56

DevTools listening on ws://127.0.0.1:60068/devtools/browser/6ae17b4b-60c2-499a-abc6-ef2e73aaed2a
       >> Logging in
Traceback (most recent call last):
  File "D:\Documents\Automator\bing-rewards-1.5\BingRewards\BingRewards.py", line 117, in <module>
    __main()
  File "D:\Documents\Automator\bing-rewards-1.5\BingRewards\BingRewards.py", line 80, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "D:\Documents\Automator\bing-rewards-1.5\BingRewards\BingRewards.py", line 28, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "D:\Documents\Automator\bing-rewards-1.5\BingRewards\src\rewards.py", line 1342, in complete_search_type
    self.complete_remaining_searches(search_type, prev_completion)
  File "D:\Documents\Automator\bing-rewards-1.5\BingRewards\src\rewards.py", line 1322, in complete_remaining_searches
    driver = self.__complete_edge_search(driver)
  File "D:\Documents\Automator\bing-rewards-1.5\BingRewards\src\rewards.py", line 1268, in __complete_edge_search
    driver, completion = self.__complete_action(action, description, driver, print_stats, close, device_type, **action_kwargs)
  File "D:\Documents\Automator\bing-rewards-1.5\BingRewards\src\rewards.py", line 1241, in __complete_action
    self.__login(driver)
  File "D:\Documents\Automator\bing-rewards-1.5\BingRewards\src\rewards.py", line 163, in __login
    is_login_complete = self.__check_login_url(driver, driver.current_url)
  File "D:\Documents\Automator\bing-rewards-1.5\BingRewards\src\rewards.py", line 98, in __check_login_url
    WebDriverWait(driver, 2).until(
  File "C:\Users\ariel\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Microsoft::Applications::Events::EventProperties::unpack [0x00007FF66DE833C2+22610]
        Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x00007FF66DDC1C92+503778]
        Ordinal0 [0x00007FF66D8C0FA5+659365]
        Ordinal0 [0x00007FF66D8FBD52+900434]
        Ordinal0 [0x00007FF66D8FC028+901160]
        Ordinal0 [0x00007FF66D92DBC7+1104839]
        Ordinal0 [0x00007FF66D91701F+1011743]
        Ordinal0 [0x00007FF66D92B2C4+1094340]
        Ordinal0 [0x00007FF66D916DF3+1011187]
        Ordinal0 [0x00007FF66D8EDE97+843415]
        Ordinal0 [0x00007FF66D8EF368+848744]
        Microsoft::Applications::Events::EventProperty::to_string [0x00007FF66DA88BC8+848072]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF66DB7AB9D+39117]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF66DB7DE12+52034]
        Microsoft::Applications::Events::EventProperty::to_string [0x00007FF66D9C0906+28166]
        Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x00007FF66DDC8921+531569]
        Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x00007FF66DDCDE04+553300]
        Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x00007FF66DDCDF95+553701]
        Microsoft::Applications::Events::EventProperty::to_string [0x00007FF66DA96650+904016]
        BaseThreadInitThunk [0x00007FF920687034+20]
        RtlUserThreadStart [0x00007FF9213A2651+33]
```

I tried downloading the source from releases and cloning the main and dev repo.

**Comment by nootkroot** [comment]
Is this still being worked on?

**Comment by jjjchens235** [comment]
I have been unable to turn on 2FA to test this. 
The MS set-up page makes me download the Microsoft Authenticator app but I already have it on my phone and connected to my email.

**Comment by nootkroot** [comment]
Maybe try reinstalling? However I'm not sure if that will wipe anything and make any accounts inaccessible. I could try seeing if changing a setting in my Microsoft authenticator will make it work.

**Comment by nootkroot** [comment]
Ok so I've looked more into the code and it seems like my 2FA page has the path `https://live.login.com/ppsecure` so the program thinks it's just the stay signed in page and therefore throws an error. 

![image](https://user-images.githubusercontent.com/65555981/155410239-fa6a92ee-04c7-42ec-8f54-1861e809e972.png)

So I would probably have to try writing my own code to get this to work and maybe start a pull request.

**Comment by jjjchens235** [comment]
A pr would be great, but i believe the current implemention assumes this url already.

**Comment by nootkroot** [comment]
This is what I read. Seems like it's assuming its just a "stay signed in" page and doesn't wait for me to select anything in the authenticator.
https://github.com/jjjchens235/bing-rewards/blob/d3f59e3c79b13594aced3560ad0a32ea053f7aa4/BingRewards/src/rewards.py#L94-L100

**Comment by jjjchens235** [comment]
Line 123 is what i was referencing

**Comment by nootkroot** [comment]
Seems like line 123 is waiting until the login changes to `https://login.live.com/ppsecure` however the problem is when I log in the URL is already `https://login.live.com/ppsecure` and so the elif statement on line 95 runs instead of the elif statement on line 118 where it checks if the URL is `https://login.live.com/`. To put it simply, the URL for my 2FA page is `https://login.live.com/ppsecure` and not `https://login.live.com/` so the wrong if statement is picked up.

**Comment by nootkroot** [comment]
Was just able to make it work by moving this:
https://github.com/jjjchens235/bing-rewards/blob/d3f59e3c79b13594aced3560ad0a32ea053f7aa4/BingRewards/src/rewards.py#L126-L129
to line 96 and doing something like this:
```python
elif "https://login.live.com/ppsecure" in url:
            # approve sign in page
            try:
                driver.find_element(By.ID, "idChkBx_SAOTCAS_TD").click()
                self.__sys_out("Waiting for user to approve sign-in request. In Microsoft Authenticator, please click approve.", 2)
            #'stay signed in' page
            finally:
                WebDriverWait(driver, 30).until(
                    EC.element_to_be_clickable((By.ID, 'KmsiCheckboxField'))
                ).click()
                #yes, stay signed in
                driver.find_element(By.XPATH, '//*[@id="idSIButton9"]').click()
```

**Comment by nootkroot** [comment]
Should I start a pull request for this?

**Comment by nootkroot** [comment]
Also just wanted to say that this was the first time I successfully ran the program and it worked beautifully. Great work!

**Comment by jjjchens235** [comment]
You got it to work so great work to you lol!
I'll review your pull request next week, thanks for the contribution!

**Comment by nootkroot** [comment]
Thanks! This is actually my first Github contribution so it's pretty exciting lol. I think I'll close this now since I've already made the pull request.
