### ISSUE TITLE
AttributeError: module 'selenium.webdriver.support.expected_conditions' has no attribute 'any_of' [fix: update to selenium v4.0+]

### ISSUE THREAD

**Issue by andrewdens** [jjjchens235/bing-rewards#179]
Getting this error in logs, I checked into this issue and there were people saying to use selenium 4 alpha releases.

Error checking rewards status -
 Traceback (most recent call last):
  File "C:\opt\bing-rewards\BingRewards\src\rewards.py", line 1241, in __get_available_points
    dashboard = self.get_dashboard_data(driver)
  File "C:\opt\bing-rewards\BingRewards\src\rewards.py", line 211, in get_dashboard_data
    self.__open_dashboard(driver)
  File "C:\opt\bing-rewards\BingRewards\src\rewards.py", line 183, in __open_dashboard
    EC.any_of(
AttributeError: module 'selenium.webdriver.support.expected_conditions' has no attribute 'any_of'

Traceback (most recent call last):
  File "C:\opt\bing-rewards\BingRewards\BingRewards.py", line 130, in <module>
    __main()
  File "C:\opt\bing-rewards\BingRewards\BingRewards.py", line 86, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "C:\opt\bing-rewards\BingRewards\BingRewards.py", line 38, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\opt\bing-rewards\BingRewards\src\rewards.py", line 1349, in complete_search_type
    init_points, driver = self.__get_available_points(driver=None, device_type=self.driver.WEB_DEVICE)
  File "C:\opt\bing-rewards\BingRewards\src\rewards.py", line 1249, in __get_available_points
    return available_points, driver
UnboundLocalError: local variable 'available_points' referenced before assignment

**Comment by andrewdens** [comment]
Updating to selenium 4.0.0a7 fixed this issue. 
Source: [](https://stackoverflow.com/questions/66194080/why-are-expected-conditions-all-of-none-of-and-any-of-absent-in-the-selenium-p)

**Comment by jjjchens235** [comment]
Thanks for calling this out, didn't realize `any_of` was selenium 4 only.
I have updated the requirements.txt and will leave this issue up for now in case others run into this too.

**Comment by tw15egan** [comment]
Was running into the same issue, I can confirm pulling latest from master and re-running `pip install -r BingRewards/requirements.txt` resolved the issue. Thanks!
