### ISSUE TITLE
TimeoutException in latest code

### ISSUE THREAD

**Issue by Jetski5822** [jjjchens235/bing-rewards#182]
pulled latest; and got this error;

did a git clean -fxd, and reinstalled the components - no dice.

```
Command line options selected:
search_type=all, headless=True, email=blah@gmail.com, cookies=False, telegram=True, driver=<class 'src.driver.ChromeDriver'>

['Fri, Feb 25 2022 09:04AM', 'Failed Edge Search, Web Search, Mobile Search, Offers, Latest Punch Card Activity']

You selected all

DevTools listening on ws://127.0.0.1:52951/devtools/browser/3272ebea-d9e5-4c55-b514-de7bc3b0fca6
       >> Logging in
Traceback (most recent call last):
  File "c:\projects\bing-rewards\BingRewards\BingRewards.py", line 130, in <module>
    __main()
  File "c:\projects\bing-rewards\BingRewards\BingRewards.py", line 86, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "c:\projects\bing-rewards\BingRewards\BingRewards.py", line 38, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "c:\projects\bing-rewards\BingRewards\src\rewards.py", line 1349, in complete_search_type
    init_points, driver = self.__get_available_points(driver=None, device_type=self.driver.WEB_DEVICE)
  File "c:\projects\bing-rewards\BingRewards\src\rewards.py", line 1238, in __get_available_points
    driver = self.__get_driver(device_type)
  File "c:\projects\bing-rewards\BingRewards\src\rewards.py", line 1227, in __get_driver
    self.__login(driver)
  File "c:\projects\bing-rewards\BingRewards\src\rewards.py", line 161, in __login
    is_login_complete = self.__check_login_url(driver, driver.current_url)
  File "c:\projects\bing-rewards\BingRewards\src\rewards.py", line 96, in __check_login_url
    WebDriverWait(driver, 2).until(
  File "C:\Users\mayneframe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x011069A3+2582947]
        Ordinal0 [0x0109A6D1+2139857]
        Ordinal0 [0x00F93A98+1063576]
        Ordinal0 [0x00FBFF3E+1244990]
        Ordinal0 [0x00FC013B+1245499]
        Ordinal0 [0x00FE9F52+1417042]
        Ordinal0 [0x00FD8594+1344916]
        Ordinal0 [0x00FE834A+1409866]
        Ordinal0 [0x00FD8366+1344358]
        Ordinal0 [0x00FB5176+1200502]
        Ordinal0 [0x00FB6066+1204326]
        GetHandleVerifier [0x012ABE02+1675858]
        GetHandleVerifier [0x0136036C+2414524]
        GetHandleVerifier [0x0119BB01+560977]
        GetHandleVerifier [0x0119A8D3+556323]
        Ordinal0 [0x010A020E+2163214]
        Ordinal0 [0x010A5078+2183288]
        Ordinal0 [0x010A51C0+2183616]
        Ordinal0 [0x010AEE1C+2223644]
        BaseThreadInitThunk [0x761C6739+25]
        RtlGetFullPathName_UEx [0x772C8E7F+1215]
        RtlGetFullPathName_UEx [0x772C8E4D+1165]
```

**Comment by Jetski5822** [comment]
Hmm went back to 94feb55 - same issue.... :(

**Comment by Jetski5822** [comment]
Failed here

![image](https://user-images.githubusercontent.com/619530/155643749-e479ceec-45ec-42c6-a24e-e957f1259c68.png)

**Comment by Jetski5822** [comment]
Turned on password less and now I get the code popup on my authenticator app... seems to be working now - thanks :)
