### ISSUE TITLE
Selenium TimeoutException on quizzes

### ISSUE THREAD

**Issue by MindScape00** [jjjchens235/bing-rewards#185]
Getting a crash and failed to complete on newest Master & Dev branch (both installs of it failing) when trying to complete "Show what you know" & "A, B, or C?" quizzes. 

![image](https://user-images.githubusercontent.com/12514692/157139917-8920cfa1-5404-49c0-b9aa-c15952017160.png)

```
Traceback (most recent call last):
  File "C:\Bing Rewards\bing-rewards-master\BingRewards\BingRewards.py", line 86, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "C:\Bing Rewards\bing-rewards-master\BingRewards\BingRewards.py", line 38, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1361, in complete_search_type
    driver = self.complete_remaining_searches(driver, search_type, prev_completion)
  File "C:\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1345, in complete_remaining_searches
    self.__complete_offers(driver)
  File "C:\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1317, in __complete_offers
    driver, completion = self.__complete_action(action, description, driver, close, device_type, **action_kwargs)
  File "C:\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1263, in __complete_action
    completion = action(driver, **action_kwargs)
  File "C:\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1103, in __offers
    self.__perform_action_on_offers(self.__click_offer, driver, more_activities_xpath, [], offer_count=remaining_offer_count)
  File "C:\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1082, in __perform_action_on_offers
    c = action(driver, offer)
  File "C:\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1025, in __click_offer
    completed = self.__quiz2(driver)
  File "C:\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 870, in __quiz2
    WebDriverWait(driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\redact\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```

**Comment by Hawkadoodle** [comment]
The issue was logged 13 days ago and the solution was to update selenium to the latest version

`pip install selenium==4.1.0`

credit to [andrewdens](https://github.com/andrewdens)

**Comment by jjjchens235** [comment]
Can you run this in `-nhl` mode and share a screenshot of the page it fails on?
I did not get this error.

On my end, I will try to add some logic so that it handles the error and proceeds to the next offer without aborting the program.

**Comment by connect-dots** [comment]
Can confirm I'm also getting this error and I am on Py 3.8.12 and Selenium 4.1.0. - Ubuntu 18 - UK based
I had to re-run on my accounts and on the 2nd pass it completed.

I would have attempted to run -nhl, but it was too late by the time I saw this.

**Comment by IcyFrogs** [comment]
For me it crashed on the "famous seas" search
Also the cookie popup is staying open on the screen I don't know if that's the reason

![88uhui1](https://user-images.githubusercontent.com/92159377/157320506-4e3f3b06-85a9-4486-bbc1-dcef10028378.jpg)

**Comment by MindScape00** [comment]
So a quick update from my side, I had tried to re-run multiple times with the error being consistent. I then cleared my "stored_browser_data" file and re-ran - it hit another error again this time, but I believe it was just a failed authentication ("this account is not signed up for Microsoft rewards" error page) - so after one more try, it finally ran and was able to complete those quizzes finally!

To jump on some of the other comments- I did not have the cookie pop-up, so that was unrelated on my case. In regards to running in -nhl, I actually was running as that (I usually do just to watch it run in the background if there's any interesting searches lmao), but there was nothing significant about the page, other than it being the bing search page with the quiz on it - it didn't look like it had ever clicked the answer on the page, but another tab would open with a second search (which looked to be the search page that it usually takes you to when you answer, and it reloads to the next question with a different search related to that first answer). Sorry if this doesn't make much sense, just trying to relay all the info I have since I can't SS the -nhl mode again. I think it could be some issue with corrupted data storage / cookies though, since I do always run in cookie mode (otherwise that 2FA hits every time and that kinda defeats running it on automation).

**Comment by coollbv** [comment]
This happening today again on Test Your Smarts - It recognizes the quiz, starts the process (0/10) and then fails.

**Comment by koogunmo** [comment]
Also happened to me today on Test Your Smarts.

**Comment by DimaRazb** [comment]
Same here for a 2nd week. Only quizzes are failing. (I'm on Win10)
Bing~Bot, [3/11/2022 6:36 AM]
Traceback (most recent call last):
  File "C:\temp\vrxxx\BingRewards\BingRewards.py", line 86, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "C:\temp\vrxxx\BingRewards\BingRewards.py", line 38, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\temp\vrxxx\BingRewards\src\rewards.py", line 1361, in complete_search_type
    driver = self.complete_remaining_searches(driver, search_type, prev_completion)
  File "C:\temp\vrxxx\BingRewards\src\rewards.py", line 1343, in complete_remaining_searches
    self.__complete_web_search(driver)
  File "C:\temp\vrxxx\BingRewards\src\rewards.py", line 1297, in __complete_web_search
    driver, completion = self.__complete_action(action, description, driver, close, device_type, **action_kwargs)
  File "C:\temp\vrxxx\BingRewards\src\rewards.py", line 1263, in __complete_action
    completion = action(driver, **action_kwargs)
  File "C:\temp\vrxxx\BingRewards\src\rewards.py", line 316, in __search
    progress = self.__get_search_progress(driver, search_type)
  File "C:\temp\vrxxx\BingRewards\src\rewards.py", line 237, in __get_search_progress
    user_status = self.get_dashboard_data(driver)['userStatus']
  File "C:\temp\vrxxx\BingRewards\src\rewards.py", line 218, in get_dashboard_data
    self.__open_dashboard(driver)
  File "C:\temp\vrxxx\BingRewards\src\rewards.py", line 184, in __open_dashboard
    driver.get(self.__DASHBOARD_URL)
  File "C:\Users\1\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 85, in get
    self._dispatch("navigate_to", (url, self._driver), "get", (url, ))
  File "C:\Users\1\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 183, in _dispatch
    raise e
  File "C:\Users\1\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 180, in _dispatch
    result = getattr(self._driver, d_call)(*d_args)
  File "C:\Users\1\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 436, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\1\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\1\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_CLOSED
  (Session info: headless chrome=99.0.4844.51)
Stacktrace:
Backtrace:
 Ordinal0 [0x011769A3 2582947]
 Ordinal0 [0x0110A6D1 2139857]
 Ordinal0 [0x01003A98 1063576]
 Ordinal0 [0x01000551 1049937]
 Ordinal0 [0x00FF5D9D 1007005]
 Ordinal0 [0x00FF6A0E 1010190]
 Ordinal0 [0x00FF5FFE 1007614]
 Ordinal0 [0x00FF55F0 1005040]
 Ordinal0 [0x00FF4727 1001255]
 Ordinal0 [0x00FF49E6 1001958]
 Ordinal0 [0x0100518A 1069450]
 Ordinal0 [0x010588FD 1411325]
 Ordinal0 [0x0104854C 1344844]
 Ordinal0 [0x0105834A 1409866]
 Ordinal0 [0x01048366 1344358]
 Ordinal0 [0x01025176 1200502]
 Ordinal0 [0x01026066 1204326]
 GetHandleVerifier [0x0131BE02 1675858]
 GetHandleVerifier [0x013D036C 2414524]
 GetHandleVerifier [0x0120BB01 560977]
 GetHandleVerifier [0x0120A8D3 556323]
 Ordinal0 [0x0111020E 2163214]
 Ordinal0 [0x01115078 2183288]
 Ordinal0 [0x011151C0 2183616]
 Ordinal0 [0x0111EE1C 2223644]
 BaseThreadInitThunk [0x76B1FA29 25]
 RtlGetAppContainerNamedObjectPath [0x77247A9E 286]
 RtlGetAppContainerNamedObjectPath [0x77247A6E 238]

Bing~Bot, [3/11/2022 7:53 AM]
Traceback (most recent call last):
  File "C:\temp\vrxxx\BingRewards\BingRewards.py", line 86, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "C:\temp\vrxxx\BingRewards\BingRewards.py", line 38, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\temp\vrxxx\BingRewards\src\rewards.py", line 1354, in complete_search_type
    driver = self.complete_remaining_searches(driver, search_type, prev_completion)
  File "C:\temp\vrxxx\BingRewards\src\rewards.py", line 1338, in complete_remaining_searches
    self.__complete_offers(driver)
  File "C:\temp\vrxxx\BingRewards\src\rewards.py", line 1310, in __complete_offers
    driver, completion = self.__complete_action(action, description, driver, close, device_type, **action_kwargs)
  File "C:\temp\vrxxx\BingRewards\src\rewards.py", line 1256, in __complete_action
    completion = action(driver, **action_kwargs)
  File "C:\temp\vrxxx\BingRewards\src\rewards.py", line 1089, in __offers
    self.__perform_action_on_offers(self.__click_offer, driver, daily_sets_xpath, [], offer_count=3)
  File "C:\temp\vrxxx\BingRewards\src\rewards.py", line 1075, in __perform_action_on_offers
    c = action(driver, offer)
  File "C:\temp\vrxxx\BingRewards\src\rewards.py", line 1018, in __click_offer
    completed = self.__quiz2(driver)
  File "C:\temp\vrxxx\BingRewards\src\rewards.py", line 864, in __quiz2
    EC.element_to_be_clickable((By.CLASS_NAME, 'cbtn'))
  File "C:\Users\1\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by jjjchens235** [comment]
I ran this today using headless=False on a fresh account, and had no issues with the following offers:
  - Show what you know
  - test your smarts
  - A, B, or C?

I'm going to assume it's a Microsoft issue until proven otherwise. If anyone encounters this issue again, please try running in `-nhl` mode and see if it resolves for you.

**Comment by DimaRazb** [comment]
Hey @jjjchens235, the first run worked, on the second run it failed, so can't say that -nhl would be a fix for me.
Thanks anyway!

**Comment by DimaRazb** [comment]
So I did more tests and can say that -a worked. The issue somehow is related to the order of the activity, and if we go with -r it starts offers and fails without mobile and punch card. I was going to decide how can I re-order the searches but I remembered about -a param, and tested stuff first manually and then found that it works fine for me. Folks could try to use it as a workaround I guess.
Cheers

**Comment by jjjchens235** [comment]
Are you using the most updated release from yesterday? If not, could you report back to see if you still have issues? I have added error handling for offers so the program shouldn't crash. In addition, I have updated the driver version.

**Comment by ddday** [comment]
https://i.imgur.com/aMQAXIb.png , Recently started receiving this as well on latest version

**Comment by jjjchens235** [comment]
@ddday this was fixed here: https://github.com/jjjchens235/bing-rewards/issues/221#issuecomment-1140998353

**Comment by jjjchens235** [comment]
Stale issue- closing
