### ISSUE TITLE
UnboundLocalError: local variable 'available_points' referenced before assignment

### ISSUE THREAD

**Issue by heximing** [jjjchens235/bing-rewards#186]
['Tue, Mar 08 2022 08:13AM', 'Failed Edge Search, Web Search, Mobile Search, Offers, Latest Punch Card Activity']

You selected remaining

DevTools listening on ws://127.0.0.1:50257/devtools/browser/e802b50e-e584-4013-9e2c-9616ae65cb3b
       >> Logging in
           << Successfully logged in
> Error checking rewards status -
 Traceback (most recent call last):
  File "C:\D\Python\bing-rewards-master\BingRewards\src\rewards.py", line 1241, in __get_available_points
    dashboard = self.get_dashboard_data(driver)
  File "C:\D\Python\bing-rewards-master\BingRewards\src\rewards.py", line 211, in get_dashboard_data
    self.__open_dashboard(driver)
  File "C:\D\Python\bing-rewards-master\BingRewards\src\rewards.py", line 183, in __open_dashboard
    EC.any_of(
AttributeError: module 'selenium.webdriver.support.expected_conditions' has no attribute 'any_of'

Traceback (most recent call last):
  File "C:\D\Python\bing-rewards-master\BingRewards\BingRewards.py", line 130, in <module>
    __main()
  File "C:\D\Python\bing-rewards-master\BingRewards\BingRewards.py", line 86, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "C:\D\Python\bing-rewards-master\BingRewards\BingRewards.py", line 38, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\D\Python\bing-rewards-master\BingRewards\src\rewards.py", line 1349, in complete_search_type
    init_points, driver = self.__get_available_points(driver=None, device_type=self.driver.WEB_DEVICE)
  File "C:\D\Python\bing-rewards-master\BingRewards\src\rewards.py", line 1249, in __get_available_points
    return available_points, driver
UnboundLocalError: local variable 'available_points' referenced before assignment

It has been working until 2 days ago.

**Comment by jjjchens235** [comment]
#179 has fix
