### ISSUE TITLE
'chromedriver.exe' executable needs to be in PATH.

### ISSUE THREAD

**Issue by Luphaestus** [jjjchens235/bing-rewards#190]
I have added chromedirver to path, and chromedirver is in the driver file in the repo (I didnt add it).

Here is the relevant info in error log....

```py
Traceback (most recent call last):
  File "C:\Users\Zak\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Zak\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Zak\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zak\Documents\bing\bing-rewards 1\BingRewards\src\driver.py", line 174, in get_driver
    driver = cls.WebDriverCls(driver_path, options=options)
  File "C:\Users\Zak\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Zak\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 90, in __init__
    self.service.start()
  File "C:\Users\Zak\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home```

**Comment by jjjchens235** [comment]
Could you provide the full error message please

**Comment by Mottledkarma517** [comment]
```py
Wed, Mar 23 2022 04:38PM
Traceback (most recent call last):
  File "C:\Users\Zak\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Zak\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Zak\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zak\Documents\bing\bing-rewards 1\BingRewards\src\driver.py", line 174, in get_driver
    driver = cls.WebDriverCls(driver_path, options=options)
  File "C:\Users\Zak\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Zak\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 90, in __init__
    self.service.start()
  File "C:\Users\Zak\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zak\Documents\bing\bing-rewards 1\BingRewards\BingRewards.py", line 86, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "C:\Users\Zak\Documents\bing\bing-rewards 1\BingRewards\BingRewards.py", line 38, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\Zak\Documents\bing\bing-rewards 1\BingRewards\src\rewards.py", line 1337, in complete_search_type
    self.__get_driver(device_type)
  File "C:\Users\Zak\Documents\bing\bing-rewards 1\BingRewards\src\rewards.py", line 1231, in __get_driver
    self.driver = self.driver_factory.get_driver(
  File "C:\Users\Zak\Documents\bing\bing-rewards 1\BingRewards\src\driver.py", line 198, in get_driver
    raise WebDriverException(error_msg)
selenium.common.exceptions.WebDriverException: Message: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home



Starting new HTTPS connection (1): api.telegram.org:443
https://api.telegram.org:443 "GET /bot5285090659:AAH2Sp5hT7fe1fNsE5lOZVINNAKRGeg3uFc/sendMessage?chat_id=5003443478&text=Traceback%20(most%20recent%20call%20last):%0A%20%20File%20%22C:%5CUsers%5CZak%5CAppData%5CLocal%5CPrograms%5CPython%5CPython39%5Clib%5Csite-packages%5Cselenium%5Cwebdriver%5Ccommon%5Cservice.py%22,%20line%2071,%20in%20start%0A%20%20%20%20self.process%20=%20subprocess.Popen(cmd,%20env=self.env,%0A%20%20File%20%22C:%5CUsers%5CZak%5CAppData%5CLocal%5CPrograms%5CPython%5CPython39%5Clib%5Csubprocess.py%22,%20line%20951,%20in%20__init__%0A%20%20%20%20self._execute_child(args,%20executable,%20preexec_fn,%20close_fds,%0A%20%20File%20%22C:%5CUsers%5CZak%5CAppData%5CLocal%5CPrograms%5CPython%5CPython39%5Clib%5Csubprocess.py%22,%20line%201420,%20in%20_execute_child%0A%20%20%20%20hp,%20ht,%20pid,%20tid%20=%20_winapi.CreateProcess(executable,%20args,%0AFileNotFoundError:%20%5BWinError%202%5D%20The%20system%20cannot%20find%20the%20file%20specified%0A%0ADuring%20handling%20of%20the%20above%20exception,%20another%20exception%20occurred:%0A%0ATraceback%20(most%20recent%20call%20last):%0A%20%20File%20%22C:%5CUsers%5CZak%5CDocuments%5Cbing%5Cbing-rewards%201%5CBingRewards%5Csrc%5Cdriver.py%22,%20line%20174,%20in%20get_driver%0A%20%20%20%20driver%20=%20cls.WebDriverCls(driver_path,%20options=options)%0A%20%20File%20%22C:%5CUsers%5CZak%5CAppData%5CLocal%5CPrograms%5CPython%5CPython39%5Clib%5Csite-packages%5Cselenium%5Cwebdriver%5Cchrome%5Cwebdriver.py%22,%20line%2070,%20in%20__init__%0A%20%20%20%20super(WebDriver,%20self).__init__(DesiredCapabilities.CHROME%5B'browserName'%5D,%20%22goog%22,%0A%20%20File%20%22C:%5CUsers%5CZak%5CAppData%5CLocal%5CPrograms%5CPython%5CPython39%5Clib%5Csite-packages%5Cselenium%5Cwebdriver%5Cchromium%5Cwebdriver.py%22,%20line%2090,%20in%20__init__%0A%20%20%20%20self.service.start()%0A%20%20File%20%22C:%5CUsers%5CZak%5CAppData%5CLocal%5CPrograms%5CPython%5CPython39%5Clib%5Csite-packages%5Cselenium%5Cwebdriver%5Ccommon%5Cservice.py%22,%20line%2081,%20in%20start%0A%20%20%20%20raise%20WebDriverException(%0Aselenium.common.exceptions.WebDriverException:%20Message:%20'chromedriver.exe'%20executable%20needs%20to%20be%20in%20PATH.%20Please%20see%20https://chromedriver.chromium.org/home%0A%0A%0ADuring%20handling%20of%20the%20above%20exception,%20another%20exception%20occurred:%0A%0ATraceback%20(most%20recent%20call%20last):%0A%20%20File%20%22C:%5CUsers%5CZak%5CDocuments%5Cbing%5Cbing-rewards%201%5CBingRewards%5CBingRewards.py%22,%20line%2086,%20in%20__main%0A%20%20%20%20complete_search(rewards,%20completion,%20search_type,%20search_hist)%0A%20%20File%20%22C:%5CUsers%5CZak%5CDocuments%5Cbing%5Cbing-rewards%201%5CBingRewards%5CBingRewards.py%22,%20line%2038,%20in%20complete_search%0A%20%20%20%20rewards.complete_search_type(search_type,%20completion,%20search_hist)%0A%20%20File%20%22C:%5CUsers%5CZak%5CDocuments%5Cbing%5Cbing-rewards%201%5CBingRewards%5Csrc%5Crewards.py%22,%20line%201337,%20in%20complete_search_type%0A%20%20%20%20self.__get_driver(device_type)%0A%20%20File%20%22C:%5CUsers%5CZak%5CDocuments%5Cbing%5Cbing-rewards%201%5CBingRewards%5Csrc%5Crewards.py%22,%20line%201231,%20in%20__get_driver%0A%20%20%20%20self.driver%20=%20self.driver_factory.get_driver(%0A%20%20File%20%22C:%5CUsers%5CZak%5CDocuments%5Cbing%5Cbing-rewards%201%5CBingRewards%5Csrc%5Cdriver.py%22,%20line%20198,%20in%20get_driver%0A%20%20%20%20raise%20WebDriverException(error_msg)%0Aselenium.common.exceptions.WebDriverException:%20Message:%20Message:%20'chromedriver.exe'%20executable%20needs%20to%20be%20in%20PATH.%20Please%20see%20https://chromedriver.chromium.org/home%0A%0A%0A HTTP/1.1" 400 73
```

**Comment by jjjchens235** [comment]
> I have added chromedirver to path, and chromedirver is in the driver file in the repo (I didnt add it).

Is the name of the file in the driver folder `chromedriver` or `chromedriver.exe` ? If the former, could you please provide the output of `platform.system()`

**Comment by Luphaestus** [comment]
It is `chromedriver.exe` and the output of `platform.system()` was `Windows`

**Comment by jjjchens235** [comment]
Sorry, I'm not sure how to solve this.

Based on [StackOverflow](https://stackoverflow.com/a/40556092), it looks like you've already tried the first two, but there's a final 3rd option.

Per the 3rd option, you would manually add the hard-coded driver path to this line of [code](https://github.com/jjjchens235/bing-rewards/blob/master/BingRewards/src/driver.py#L176)

Something like
```
driver = cls.WebDriverCls('<my_hardcoded_path>', options=options)
```

Again, sorry I cannot be more helpful.
