### ISSUE TITLE
The Halo series punch card

### ISSUE THREAD

**Issue by jjjchens235** [jjjchens235/bing-rewards#191]
This punch card is crashing the program

```sh
 >> Punch card "Paramount+: Halo Original Series" is not complete yet.
       >> Starting activity "Activate punch card"
Boo! Telegram notification NOT sent, response code is: <Response [400]> with response msg {"ok":false,"error_code":400,"description":"Bad Request: message is too long"}

Traceback (most recent call last):
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/BingRewards.py", line 122, in <module>
    main()
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/BingRewards.py", line 87, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/BingRewards.py", line 46, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/rewards.py", line 1359, in complete_search_type
    self.complete_remaining_searches(search_type, prev_completion)
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/rewards.py", line 1343, in complete_remaining_searches
    self.__complete_punchcard()
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/rewards.py", line 1321, in __complete_punchcard
    self.completion.punchcard = self.__complete_action(
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/rewards.py", line 1263, in __complete_action
    completion = action(**action_kwargs)
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/rewards.py", line 1184, in __punchcard
    activity_index = self.__punchcard_activity(parent_url, punchcard['childPromotions'])
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/rewards.py", line 1154, in __punchcard_activity
    self.driver.execute_script("document.getElementsByClassName('offer-cta')[0].click()")
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 95, in execute_script
    return self._dispatch("execute_script", (script, self._driver), "execute_script", unwrapped_args)
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 183, in _dispatch
    raise e
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 180, in _dispatch
    result = getattr(self._driver, d_call)(*d_args)
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 878, in execute_script
    return self.execute(command, {
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read properties of undefined (reading 'click')
  (Session info: chrome=99.0.4844.83)

```

**Comment by jjjchens235** [comment]
The solution is not to do this punchcard, the points offered can not be automated (i.e downloading app)

**Comment by jjjchens235** [comment]
8acc819
