### ISSUE TITLE
Erroring out on run: login issue

### ISSUE THREAD

**Issue by LCzoboriek** [jjjchens235/bing-rewards#192]
Fri, Mar 25 2022 02:36PM
Traceback (most recent call last):
  File "C:\Users\ldccz\Documents\GitHub\bing-rewards\BingRewards\BingRewards.py", line 86, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "C:\Users\ldccz\Documents\GitHub\bing-rewards\BingRewards\BingRewards.py", line 38, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\ldccz\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 1337, in complete_search_type
    self.__get_driver(device_type)
  File "C:\Users\ldccz\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 1234, in __get_driver
    self.__login()
  File "C:\Users\ldccz\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 167, in __login
    is_login_complete = self.__check_login_url(self.driver.current_url)
  File "C:\Users\ldccz\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 106, in __check_login_url
    WebDriverWait(self.driver, 30).until(
  File "C:\Users\ldccz\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
Backtrace:
	Ordinal0 [0x00A09943+2595139]
	Ordinal0 [0x0099C9F1+2148849]
	Ordinal0 [0x00894528+1066280]
	Ordinal0 [0x008C0FD4+1249236]
	Ordinal0 [0x008C11CB+1249739]
	Ordinal0 [0x008ED812+1431570]
	Ordinal0 [0x008DBA34+1358388]
	Ordinal0 [0x008EBAF2+1424114]
	Ordinal0 [0x008DB806+1357830]
	Ordinal0 [0x008B6086+1204358]
	Ordinal0 [0x008B6F96+1208214]
	GetHandleVerifier [0x00BAB232+1658114]
	GetHandleVerifier [0x00C6312C+2411516]
	GetHandleVerifier [0x00A9F261+560433]
	GetHandleVerifier [0x00A9E366+556598]
	Ordinal0 [0x009A286B+2173035]
	Ordinal0 [0x009A75F8+2192888]
	Ordinal0 [0x009A76E5+2193125]
	Ordinal0 [0x009B11FC+2232828]
	BaseThreadInitThunk [0x76096739+25]
	RtlGetFullPathName_UEx [0x779D8E7F+1215]
	RtlGetFullPathName_UEx [0x779D8E4D+1165]

Not sure what the issue is, if someone could help me?

**Comment by DimaRazb** [comment]
Hey, try to run -w, -m and see where is the error will raise. I bet it's punchcard only, so you could temporary ignore this activity probably.
Cheers

**Comment by LCzoboriek** [comment]
run it with both -w and -m or just seperately?

**Comment by LCzoboriek** [comment]
Fri, Mar 25 2022 02:59PM
Traceback (most recent call last):
  File "C:\Users\ldccz\Documents\GitHub\bing-rewards\BingRewards\BingRewards.py", line 86, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "C:\Users\ldccz\Documents\GitHub\bing-rewards\BingRewards\BingRewards.py", line 38, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\ldccz\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 1337, in complete_search_type
    self.__get_driver(device_type)
  File "C:\Users\ldccz\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 1234, in __get_driver
    self.__login()
  File "C:\Users\ldccz\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 167, in __login
    is_login_complete = self.__check_login_url(self.driver.current_url)
  File "C:\Users\ldccz\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 106, in __check_login_url
    WebDriverWait(self.driver, 30).until(
  File "C:\Users\ldccz\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
Backtrace:
	Ordinal0 [0x00A09943+2595139]
	Ordinal0 [0x0099C9F1+2148849]
	Ordinal0 [0x00894528+1066280]
	Ordinal0 [0x008C0FD4+1249236]
	Ordinal0 [0x008C11CB+1249739]
	Ordinal0 [0x008ED812+1431570]
	Ordinal0 [0x008DBA34+1358388]
	Ordinal0 [0x008EBAF2+1424114]
	Ordinal0 [0x008DB806+1357830]
	Ordinal0 [0x008B6086+1204358]
	Ordinal0 [0x008B6F96+1208214]
	GetHandleVerifier [0x00BAB232+1658114]
	GetHandleVerifier [0x00C6312C+2411516]
	GetHandleVerifier [0x00A9F261+560433]
	GetHandleVerifier [0x00A9E366+556598]
	Ordinal0 [0x009A286B+2173035]
	Ordinal0 [0x009A75F8+2192888]
	Ordinal0 [0x009A76E5+2193125]
	Ordinal0 [0x009B11FC+2232828]
	BaseThreadInitThunk [0x76096739+25]
	RtlGetFullPathName_UEx [0x779D8E7F+1215]
	RtlGetFullPathName_UEx [0x779D8E4D+1165]


This was -w

**Comment by LCzoboriek** [comment]
Fri, Mar 25 2022 03:00PM
Traceback (most recent call last):
  File "C:\Users\ldccz\Documents\GitHub\bing-rewards\BingRewards\BingRewards.py", line 86, in __main
    complete_search(rewards, completion, search_type, search_hist)
  File "C:\Users\ldccz\Documents\GitHub\bing-rewards\BingRewards\BingRewards.py", line 38, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\ldccz\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 1337, in complete_search_type
    self.__get_driver(device_type)
  File "C:\Users\ldccz\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 1234, in __get_driver
    self.__login()
  File "C:\Users\ldccz\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 167, in __login
    is_login_complete = self.__check_login_url(self.driver.current_url)
  File "C:\Users\ldccz\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 106, in __check_login_url
    WebDriverWait(self.driver, 30).until(
  File "C:\Users\ldccz\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
Backtrace:
	Ordinal0 [0x00A09943+2595139]
	Ordinal0 [0x0099C9F1+2148849]
	Ordinal0 [0x00894528+1066280]
	Ordinal0 [0x008C0FD4+1249236]
	Ordinal0 [0x008C11CB+1249739]
	Ordinal0 [0x008ED812+1431570]
	Ordinal0 [0x008DBA34+1358388]
	Ordinal0 [0x008EBAF2+1424114]
	Ordinal0 [0x008DB806+1357830]
	Ordinal0 [0x008B6086+1204358]
	Ordinal0 [0x008B6F96+1208214]
	GetHandleVerifier [0x00BAB232+1658114]
	GetHandleVerifier [0x00C6312C+2411516]
	GetHandleVerifier [0x00A9F261+560433]
	GetHandleVerifier [0x00A9E366+556598]
	Ordinal0 [0x009A286B+2173035]
	Ordinal0 [0x009A75F8+2192888]
	Ordinal0 [0x009A76E5+2193125]
	Ordinal0 [0x009B11FC+2232828]
	BaseThreadInitThunk [0x76096739+25]
	RtlGetFullPathName_UEx [0x779D8E7F+1215]
	RtlGetFullPathName_UEx [0x779D8E4D+1165]


-m here

**Comment by LCzoboriek** [comment]
Nah no points have been collected today

**Comment by andrewdens** [comment]
I'm getting the same error. When testing with python BingRewards -nhl it looks like it fails on the Riot League/Valorant punchcard

**Comment by jjjchens235** [comment]
@LCzoboriek : it looks like you're erroring out on this line `rewards\BingRewards\src\rewards.py", line 106, in __check_login_url`
Please run this again with argument `-nhl` to see what the behavior is in the browser, some possible things are incorrect password, 2FA page, etc.

Everyone else is failing on Halo, I will try to fix this asap.

**Comment by heximing** [comment]
I have the same error.

**Comment by jjjchens235** [comment]
Halo error should be fixed now.

**Comment by wastingoctober** [comment]
> Halo error should be fixed now.

Thanks as always!

**Comment by LCzoboriek** [comment]
> @LCzoboriek : it looks like you're erroring out on this line `rewards\BingRewards\src\rewards.py", line 106, in __check_login_url` Please run this again with argument `-nhl` to see what the behavior is in the browser, some possible things are incorrect password, 2FA page, etc.
> 
> Everyone else is failing on Halo, I will try to fix this asap.

Okay running it in nhl seemed to work, it failed a fair few quiz's but earned 345 points today :) I tried again without nhl but it did the same thing again, it seems to not open the browser, but with nhl it does? Odd

**Comment by LCzoboriek** [comment]
anyway the rewards works for the most part :) So ill close this
