### ISSUE TITLE
Getting 'NoneType' object is not subscriptable Errors after completing Punchcard quiz [SOLVED]

### ISSUE THREAD

**Issue by Gigafrost** [jjjchens235/bing-rewards#196]
**Before posting issue...**

1. Run using non-headless mode: `python BingRewards -nhl`
2. Copy relevant output from `errors.log`

**Your Issue - include the details from the above steps:**

When starting BingRewards, I would get a 'NoneType' object is not subscriptable error after it's finished completing the Punchcard quiz. Any idea what I would need to do to fix it? I downloaded and updated to the latest version of BingRewards and it's still giving me this error. Has anyone else had something like this?

Error.log

`Traceback (most recent call last):
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\BingRewards.py", line 87, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\BingRewards.py", line 46, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1366, in complete_search_type
    self.complete_remaining_searches(search_type, prev_completion)
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1350, in complete_remaining_searches
    self.__complete_punchcard()
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1328, in __complete_punchcard
    self.completion.punchcard = self.__complete_action(
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1270, in __complete_action
    completion = action(**action_kwargs)
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1176, in __punchcard
    offer_types = punchcard['parentPromotion']['attributes']['type'].split(',')
TypeError: 'NoneType' object is not subscriptable`

**Comment by webdeck** [comment]
same here - line 1176 uses punchcard['parentPromotion'] before the null check in line 1179:

```
Command line options selected:
search_type=remaining, headless=True, email=None, cookies=False, telegram=True, driver=<class 'src.driver.ChromeDriverFactory'>

['Sat, Mar 26 2022 04:10AM', 'Failed Mobile Search, Latest Punch Card Activity']

You selected remaining
Logging in
<< Successfully logged in
Starting punch card
Punch card "Women's History Month" is already completed.
Traceback (most recent call last):
File "/Users/server/bing-rewards/BingRewards/BingRewards.py", line 122, in <module>
main()
File "/Users/server/bing-rewards/BingRewards/BingRewards.py", line 87, in main
complete_search(rewards, completion, args.search_type, search_hist)
File "/Users/server/bing-rewards/BingRewards/BingRewards.py", line 46, in complete_search
rewards.complete_search_type(search_type, completion, search_hist)
File "/Users/server/bing-rewards/BingRewards/src/rewards.py", line 1366, in complete_search_type
self.complete_remaining_searches(search_type, prev_completion)
File "/Users/server/bing-rewards/BingRewards/src/rewards.py", line 1350, in complete_remaining_searches
self.__complete_punchcard()
File "/Users/server/bing-rewards/BingRewards/src/rewards.py", line 1328, in __complete_punchcard
self.completion.punchcard = self.__complete_action(
File "/Users/server/bing-rewards/BingRewards/src/rewards.py", line 1270, in __complete_action
completion = action(**action_kwargs)
File "/Users/server/bing-rewards/BingRewards/src/rewards.py", line 1176, in __punchcard
offer_types = punchcard['parentPromotion']['attributes']['type'].split(',')
TypeError: 'NoneType' object is not subscriptable
```

**Comment by jjjchens235** [comment]
34f9f0d should fix it, in `master` now.

**Comment by Gigafrost** [comment]
> [34f9f0d](https://github.com/jjjchens235/bing-rewards/commit/34f9f0dce8dfeafb0bba6a52f7fec27173c8bee0) should fix it, in `master` now.

That did the trick! Thank you for fixing this so quickly! It's working great again! Changing this to Solved!
