### ISSUE TITLE
Unhelpful error

### ISSUE THREAD

**Issue by AndrewChqng** [jjjchens235/bing-rewards#203]
Manages to open in headless mode, but shows this issue, updated selemium in case but still no luck
```
Fri, Apr 08 2022 04:36PM
Traceback (most recent call last):
  File "D:\Downloads\bing-rewards\BingRewards\src\rewards.py", line 191, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Downloads\bing-rewards\BingRewards\src\rewards.py", line 191, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Downloads\bing-rewards\BingRewards\BingRewards.py", line 98, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "D:\Downloads\bing-rewards\BingRewards\BingRewards.py", line 61, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "D:\Downloads\bing-rewards\BingRewards\src\rewards.py", line 1366, in complete_search_type
    init_points = self.__get_available_points()
  File "D:\Downloads\bing-rewards\BingRewards\src\rewards.py", line 1264, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
  File "D:\Downloads\bing-rewards\BingRewards\src\rewards.py", line 221, in get_dashboard_data
    self.__open_dashboard()
  File "D:\Downloads\bing-rewards\BingRewards\src\rewards.py", line 208, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "D:\Downloads\bing-rewards\BingRewards\src\rewards.py", line 208, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "D:\Downloads\bing-rewards\BingRewards\src\rewards.py", line 207, in __open_dashboard
    raise(e)
  File "D:\Downloads\bing-rewards\BingRewards\src\rewards.py", line 191, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```

**Comment by jjjchens235** [comment]
dup, the fix has been merged to master
https://github.com/jjjchens235/bing-rewards/issues/199
