### ISSUE TITLE
Error for mobile search/telegram (i think)

### ISSUE THREAD

**Issue by Saytoo** [jjjchens235/bing-rewards#204]
I use it from france btw, here is the log:

Sat, Apr 09 2022 03:45PM
Traceback (most recent call last):
  File "C:\Users\Sayto\Downloads\Auto Microsoft Rewards\bing-rewards-master\BingRewards\BingRewards.py", line 87, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\Sayto\Downloads\Auto Microsoft Rewards\bing-rewards-master\BingRewards\BingRewards.py", line 46, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\Sayto\Downloads\Auto Microsoft Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1369, in complete_search_type
    self.complete_remaining_searches(search_type, prev_completion)
  File "C:\Users\Sayto\Downloads\Auto Microsoft Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1351, in complete_remaining_searches
    self.__complete_offers()
  File "C:\Users\Sayto\Downloads\Auto Microsoft Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1323, in __complete_offers
    self.completion.offers = self.__complete_action(
  File "C:\Users\Sayto\Downloads\Auto Microsoft Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1273, in __complete_action
    completion = action(**action_kwargs)
  File "C:\Users\Sayto\Downloads\Auto Microsoft Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1104, in __offers
    self.__perform_action_on_offers(self.__click_offer, daily_sets_xpath, [], offer_count=3)
  File "C:\Users\Sayto\Downloads\Auto Microsoft Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1085, in __perform_action_on_offers
    c = action(offer)
  File "C:\Users\Sayto\Downloads\Auto Microsoft Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1027, in __click_offer
    completed = self.__quiz2()
  File "C:\Users\Sayto\Downloads\Auto Microsoft Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 870, in __quiz2
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\Sayto\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 249, in click
    self._dispatch("click", (self._webelement, self._driver), "click", ())
  File "C:\Users\Sayto\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 331, in _dispatch
    raise e
  File "C:\Users\Sayto\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 328, in _dispatch
    result = getattr(self._webelement, d_call)(*d_args)
  File "C:\Users\Sayto\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Sayto\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Sayto\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Sayto\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span id="3E131D_45_btn" class="cbtn" data-appns="SERP" data-k="5792.1">...</span> is not clickable at point (484, 687). Other element would receive the click: <div id="nonclicky" class="visible-lg">...</div>
  (Session info: headless chrome=100.0.4896.75)
Stacktrace:
Backtrace:
	Ordinal0 [0x00437413+2389011]
	Ordinal0 [0x003C9F61+1941345]
	Ordinal0 [0x002BC658+837208]
	Ordinal0 [0x002EF8AF+1046703]
	Ordinal0 [0x002ED8D6+1038550]
	Ordinal0 [0x002EB5EB+1029611]
	Ordinal0 [0x002EA359+1024857]
	Ordinal0 [0x002DFF93+982931]
	Ordinal0 [0x0030414C+1130828]
	Ordinal0 [0x002DF974+981364]
	Ordinal0 [0x00304364+1131364]
	Ordinal0 [0x00314302+1196802]
	Ordinal0 [0x00303F66+1130342]
	Ordinal0 [0x002DE546+976198]
	Ordinal0 [0x002DF456+980054]
	GetHandleVerifier [0x005E9632+1727522]
	GetHandleVerifier [0x0069BA4D+2457661]
	GetHandleVerifier [0x004CEB81+569713]
	GetHandleVerifier [0x004CDD76+566118]
	Ordinal0 [0x003D0B2B+1968939]
	Ordinal0 [0x003D5988+1989000]
	Ordinal0 [0x003D5A75+1989237]
	Ordinal0 [0x003DECB1+2026673]
	BaseThreadInitThunk [0x75E7FA29+25]
	RtlGetAppContainerNamedObjectPath [0x774C7A7E+286]
	RtlGetAppContainerNamedObjectPath [0x774C7A4E+238]

Starting new HTTPS connection (1): api.telegram.org:443
https://api.telegram.org:443 "GET /bot5040510872:AAEsXIP6t5kQ49RDsoezabR0Iyq2-4wHixA/sendMessage?chat_id=1076420319&text=Traceback%20(most%20recent%20call%20last):%0A%20%20File%20%22C:%5CUsers%5CSayto%5CDownloads%5CAuto%20Microsoft%20Rewards%5Cbing-rewards-master%5CBingRewards%5CBingRewards.py%22,%20line%2087,%20in%20main%0A%20%20%20%20complete_search(rewards,%20completion,%20args.search_type,%20search_hist)%0A%20%20File%20%22C:%5CUsers%5CSayto%5CDownloads%5CAuto%20Microsoft%20Rewards%5Cbing-rewards-master%5CBingRewards%5CBingRewards.py%22,%20line%2046,%20in%20complete_search%0A%20%20%20%20rewards.complete_search_type(search_type,%20completion,%20search_hist)%0A%20%20File%20%22C:%5CUsers%5CSayto%5CDownloads%5CAuto%20Microsoft%20Rewards%5Cbing-rewards-master%5CBingRewards%5Csrc%5Crewards.py%22,%20line%201369,%20in%20complete_search_type%0A%20%20%20%20self.complete_remaining_searches(search_type,%20prev_completion)%0A%20%20File%20%22C:%5CUsers%5CSayto%5CDownloads%5CAuto%20Microsoft%20Rewards%5Cbing-rewards-master%5CBingRewards%5Csrc%5Crewards.py%22,%20line%201351,%20in%20complete_remaining_searches%0A%20%20%20%20self.__complete_offers()%0A%20%20File%20%22C:%5CUsers%5CSayto%5CDownloads%5CAuto%20Microsoft%20Rewards%5Cbing-rewards-master%5CBingRewards%5Csrc%5Crewards.py%22,%20line%201323,%20in%20__complete_offers%0A%20%20%20%20self.completion.offers%20=%20self.__complete_action(%0A%20%20File%20%22C:%5CUsers%5CSayto%5CDownloads%5CAuto%20Microsoft%20Rewards%5Cbing-rewards-master%5CBingRewards%5Csrc%5Crewards.py%22,%20line%201273,%20in%20__complete_action%0A%20%20%20%20completion%20=%20action(**action_kwargs)%0A%20%20File%20%22C:%5CUsers%5CSayto%5CDownloads%5CAuto%20Microsoft%20Rewards%5Cbing-rewards-master%5CBingRewards%5Csrc%5Crewards.py%22,%20line%201104,%20in%20__offers%0A%20%20%20%20self.__perform_action_on_offers(self.__click_offer,%20daily_sets_xpath,%20%5B%5D,%20offer_count=3)%0A%20%20File%20%22C:%5CUsers%5CSayto%5CDownloads%5CAuto%20Microsoft%20Rewards%5Cbing-rewards-master%5CBingRewards%5Csrc%5Crewards.py%22,%20line%201085,%20in%20__perform_action_on_offers%0A%20%20%20%20c%20=%20action(offer)%0A%20%20File%20%22C:%5CUsers%5CSayto%5CDownloads%5CAuto%20Microsoft%20Rewards%5Cbing-rewards-master%5CBingRewards%5Csrc%5Crewards.py%22,%20line%201027,%20in%20__click_offer%0A%20%20%20%20completed%20=%20self.__quiz2()%0A%20%20File%20%22C:%5CUsers%5CSayto%5CDownloads%5CAuto%20Microsoft%20Rewards%5Cbing-rewards-master%5CBingRewards%5Csrc%5Crewards.py%22,%20line%20870,%20in%20__quiz2%0A%20%20%20%20WebDriverWait(self.driver,%20self.__WEB_DRIVER_WAIT_SHORT).until(%0A%20%20File%20%22C:%5CUsers%5CSayto%5CAppData%5CLocal%5CPackages%5CPythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0%5CLocalCache%5Clocal-packages%5CPython39%5Csite-packages%5Cselenium%5Cwebdriver%5Csupport%5Cevent_firing_webdriver.py%22,%20line%20249,%20in%20click%0A%20%20%20%20self._dispatch(%22click%22,%20(self._webelement,%20self._driver),%20%22click%22,%20())%0A%20%20File%20%22C:%5CUsers%5CSayto%5CAppData%5CLocal%5CPackages%5CPythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0%5CLocalCache%5Clocal-packages%5CPython39%5Csite-packages%5Cselenium%5Cwebdriver%5Csupport%5Cevent_firing_webdriver.py%22,%20line%20331,%20in%20_dispatch%0A%20%20%20%20raise%20e%0A%20%20File%20%22C:%5CUsers%5CSayto%5CAppData%5CLocal%5CPackages%5CPythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0%5CLocalCache%5Clocal-packages%5CPython39%5Csite-packages%5Cselenium%5Cwebdriver%5Csupport%5Cevent_firing_webdriver.py%22,%20line%20328,%20in%20_dispatch%0A%20%20%20%20result%20=%20getattr(self._webelement,%20d_call)(*d_args)%0A%20%20File%20%22C:%5CUsers%5CSayto%5CAppData%5CLocal%5CPackages%5CPythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0%5CLocalCache%5Clocal-packages%5CPython39%5Csite-packages%5Cselenium%5Cwebdriver%5Cremote%5Cwebelement.py%22,%20line%2081,%20in%20click%0A%20%20%20%20self._execute(Command.CLICK_ELEMENT)%0A%20%20File%20%22C:%5CUsers%5CSayto%5CAppData%5CLocal%5CPackages%5CPythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0%5CLocalCache%5Clocal-packages%5CPython39%5Csite-packages%5Cselenium%5Cwebdriver%5Cremote%5Cwebelement.py%22,%20line%20710,%20in%20_execute%0A%20%20%20%20return%20self._parent.execute(command,%20params)%0A%20%20File%20%22C:%5CUsers%5CSayto%5CAppData%5CLocal%5CPackages%5CPythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0%5CLocalCache%5Clocal-packages%5CPython39%5Csite-packages%5Cselenium%5Cwebdriver%5Cremote%5Cwebdriver.py%22,%20line%20424,%20in%20execute%0A%20%20%20%20self.error_handler.check_response(response)%0A%20%20File%20%22C:%5CUsers%5CSayto%5CAppData%5CLocal%5CPackages%5CPythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0%5CLocalCache%5Clocal-packages%5CPython39%5Csite-packages%5Cselenium%5Cwebdriver%5Cremote%5Cerrorhandler.py%22,%20line%20247,%20in%20check_response%0A%20%20%20%20raise%20exception_class(message,%20screen,%20stacktrace)%0Aselenium.common.exceptions.ElementClickInterceptedException:%20Message:%20element%20click%20intercepted:%20Element%20%3Cspan%20id=%223E131D_45_btn%22%20class=%22cbtn%22%20data-appns=%22SERP%22%20data-k=%225792.1%22%3E...%3C/span%3E%20is%20not%20clickable%20at%20point%20(484,%20687).%20Other%20element%20would%20receive%20the%20click:%20%3Cdiv%20id=%22nonclicky%22%20class=%22visible-lg%22%3E...%3C/div%3E%0A%20%20(Session%20info:%20headless%20chrome=100.0.4896.75)%0AStacktrace:%0ABacktrace:%0A%09Ordinal0%20%5B0x00437413+2389011%5D%0A%09Ordinal0%20%5B0x003C9F61+1941345%5D%0A%09Ordinal0%20%5B0x002BC658+837208%5D%0A%09Ordinal0%20%5B0x002EF8AF+1046703%5D%0A%09Ordinal0%20%5B0x002ED8D6+1038550%5D%0A%09Ordinal0%20%5B0x002EB5EB+1029611%5D%0A%09Ordinal0%20%5B0x002EA359+1024857%5D%0A%09Ordinal0%20%5B0x002DFF93+982931%5D%0A%09Ordinal0%20%5B0x0030414C+1130828%5D%0A%09Ordinal0%20%5B0x002DF974+981364%5D%0A%09Ordinal0%20%5B0x00304364+1131364%5D%0A%09Ordinal0%20%5B0x00314302+1196802%5D%0A%09Ordinal0%20%5B0x00303F66+1130342%5D%0A%09Ordinal0%20%5B0x002DE546+976198%5D%0A%09Ordinal0%20%5B0x002DF456+980054%5D%0A%09GetHandleVerifier%20%5B0x005E9632+1727522%5D%0A%09GetHandleVerifier%20%5B0x0069BA4D+2457661%5D%0A%09GetHandleVerifier%20%5B0x004CEB81+569713%5D%0A%09GetHandleVerifier%20%5B0x004CDD76+566118%5D%0A%09Ordinal0%20%5B0x003D0B2B+1968939%5D%0A%09Ordinal0%20%5B0x003D5988+1989000%5D%0A%09Ordinal0%20%5B0x003D5A75+1989237%5D%0A%09Ordinal0%20%5B0x003DECB1+2026673%5D%0A%09BaseThreadInitThunk%20%5B0x75E7FA29+25%5D%0A%09RtlGetAppContainerNamedObjectPath%20%5B0x774C7A7E+286%5D%0A%09RtlGetAppContainerNamedObjectPath%20%5B0x774C7A4E+238%5D%0A%0A HTTP/1.1" 400 78

**Comment by Saytoo** [comment]
nvm now working with the driver.py update
