### ISSUE TITLE
Cannot import name

### ISSUE THREAD

**Issue by CookerBower** [jjjchens235/bing-rewards#209]
am i doing this wrong? 
> C:\Users\Owner>cd C:\Scripts\bing-rewards-1.8\BingRewards

> C:\Scripts\bing-rewards-1.8\BingRewards>python python BingRewards.py -r -nhl -d msedge
> python: can't open file 'C:\\Scripts\\bing-rewards-1.8\\BingRewards\\python': [Errno 2] No such file or directory

> C:\Scripts\bing-rewards-1.8\BingRewards>python BingRewards.py -r -nhl -d msedge

> Failed to import configuration file
> Traceback (most recent call last):
 > File "C:\Scripts\bing-rewards-1.8\BingRewards\BingRewards.py", line 122, in <module>
    main()
  > File "C:\Scripts\bing-rewards-1.8\BingRewards\BingRewards.py", line 59, in main
    from src import config
> ImportError: cannot import name 'config' from 'src' (C:\Scripts\bing-rewards-1.8\BingRewards\src\__init__.py)

I found the issue however I still don't know how to fix it. the setup.py doesn't create config.py

**Comment by jjjchens235** [comment]
1. Does setup.py run successfully?


2. Can you run the following from the project root directory `bing-rewards-master` and share the output via screenshot?
```sh
cd BingRewards/src/
ls
```


3. Can you also share the following output via screenshot:
```
git status
```

**Comment by CookerBower** [comment]
![image](https://user-images.githubusercontent.com/104735042/166168616-490cad5a-99d1-4fb8-90f1-a24da7130d06.png)

**Comment by jjjchens235** [comment]
Your output does not show the results of the `ls`.
Furthermore, the output of your `git status` indicates there's an issue.

Please do the following:
1. In `Scripts` folder, please clone the repo anew. `git clone https://github.com/jjjchens235/bing-rewards`
2. Please run the setup steps again as described in the `README`

**Comment by jjjchens235** [comment]
No activity, marking as closed
