### ISSUE TITLE
Error after postcard was completed - process exited with code 1 (0x00000001)

### ISSUE THREAD

**Issue by Gigafrost** [jjjchens235/bing-rewards#212]
Hello, I found this error that's appeared after the punch card was completed. I was wondering if this can be looked at / what solution there is for this sort of error? 

Starting punch card
       >> Punch card "On top of the world" is not complete yet.
       >> Starting activity "Day 1: Take flight to new heights"
              >>> Starting quiz
              >>> Multiple choice
                     >>>> Progress: [##############################] 10/10 (100%)
                  <<< Successfully completed quiz
              >>> Latest punch card activity successfully completed!
Traceback (most recent call last):
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\BingRewards.py", line 122, in <module>
    main()
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\BingRewards.py", line 87, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\BingRewards.py", line 46, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1366, in complete_search_type
    self.complete_remaining_searches(search_type, prev_completion)
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1350, in complete_remaining_searches
    self.__complete_punchcard()
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1328, in __complete_punchcard
    self.completion.punchcard = self.__complete_action(
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1270, in __complete_action
    completion = action(**action_kwargs)
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1176, in __punchcard
    offer_types = punchcard['parentPromotion']['attributes']['type'].split(',')
TypeError: 'NoneType' object is not subscriptable

[process exited with code 1 (0x00000001)]

from error.log

Thu, May 12 2022 01:56PM
Traceback (most recent call last):
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\BingRewards.py", line 87, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\BingRewards.py", line 46, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1366, in complete_search_type
    self.complete_remaining_searches(search_type, prev_completion)
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1350, in complete_remaining_searches
    self.__complete_punchcard()
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1328, in __complete_punchcard
    self.completion.punchcard = self.__complete_action(
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1270, in __complete_action
    completion = action(**action_kwargs)
  File "C:\Users\Kaitlyn\Downloads\PC Tools\Bing Rewards\bing-rewards-master\BingRewards\src\rewards.py", line 1176, in __punchcard
    offer_types = punchcard['parentPromotion']['attributes']['type'].split(',')
TypeError: 'NoneType' object is not subscriptable

**Comment by Affoghiamoci** [comment]
Same here, i think is about language, where are u from?

**Comment by Gigafrost** [comment]
> Same here, i think is about language, where are u from?

United States

**Comment by jjjchens235** [comment]
@Gigafrost - are you using the most recent version of the code? This `TypeError` was fixed a while back.

**Comment by Gigafrost** [comment]
Yup, I believe so.

1.8.right?

**Comment by jjjchens235** [comment]
Ah that's my bad. There were a few hotfixes that I had to push outside of a release 'tag'. I think if you pull from the current `master` branch which is a little ahead of v1.8, it should fix your issue.

**Comment by jjjchens235** [comment]
I'm actually a little confused, you initially reported this [issue](https://github.com/jjjchens235/bing-rewards/issues/196) back in March and you noted that the issue had been fixed. The error message from both of these issues look identical.

I added a v1.9 release which reflects the current state of the master branch. Please try using the code in v1.9. I'm going to mark this as resolved, but please re-open if the issue persists.
