### ISSUE TITLE
 No module named 'google'

### ISSUE THREAD

**Issue by HighKingPhoenix** [jjjchens235/bing-rewards#218]
**Before posting issue...**

1. Run using non-headless mode: `python BingRewards -nhl`
2. Copy relevant output from `errors.log`

**Your Issue - include the details from the above steps:**
PS C:\Users\Phoenix\Documents\auto\Cammy\BingRewards> python BingRewards.py -nhl
Traceback (most recent call last):
  File "C:\Users\Phoenix\Documents\auto\Cammy\BingRewards\BingRewards.py", line 10, in <module>
    from src.google_sheets_reporting import GoogleSheetsReporting
  File "C:\Users\Phoenix\Documents\auto\Cammy\BingRewards\src\google_sheets_reporting.py", line 6, in <module>
    from google.auth.transport.requests import Request
ModuleNotFoundError: No module named 'google'

**Comment by DerMuffin** [comment]
Install all requirements from the txt file. Look the Readme file. This explains how you do it.
