### ISSUE TITLE
Punchcard Frozen - Stranger things [Resolved]

### ISSUE THREAD

**Issue by jjjchens235** [jjjchens235/bing-rewards#221]
**Before posting issue...**

1. Run using non-headless mode: `python BingRewards -nhl`
2. Copy relevant output from `errors.log`

**Your Issue - include the details from the above steps:**

### Issue
The program completely freezes after clicking 'Activate' punchcard for Stranger things.
When activating, a new tab is opened as expected, but the tab is completely blank.

The program tries to close the new tab, but Selenium doesn't recognize the blank tab and closes the first tab.
Then, it tries to return to the first tab that was just closed. Only the blank tab exists at this point, Selenium does not recognize it, and program hangs. 

### Error log:
```
> Starting punch card
       >> Punch card "On top of the world" is already completed.
       >> Punch card "Stranger Things Season 4" is not complete yet.
       >> Starting activity "Get the app"
> Error during punch card:
 Traceback (most recent call last):
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/rewards.py", line 1277, in __complete_action
    completion = action(**action_kwargs)
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/rewards.py", line 1194, in __punchcard
    is_complete_activity = self.get_dashboard_data()['punchCards'][punchcard_index]['childPromotions'][activity_index]['complete']
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/rewards.py", line 223, in get_dashboard_data
    self.__open_dashboard()
  File "/Users/jwong/Programming/Python/bing-rewards-master/BingRewards/src/rewards.py", line 189, in __open_dashboard
    self.driver.get(self.__DASHBOARD_URL)
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 85, in get
    self._dispatch("navigate_to", (url, self._driver), "get", (url, ))
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 183, in _dispatch
    raise e
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 180, in _dispatch
    result = getattr(self._driver, d_call)(*d_args)
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 436, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/Users/jwong/miniconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: headless chrome=102.0.5005.61)
```

**Comment by jjjchens235** [comment]
Hotfix in master: d1bd125
