### ISSUE TITLE
Every ChromeDriver update oblige to update Google Chrome as well

### ISSUE THREAD

**Issue by malesci** [jjjchens235/bing-rewards#224]
**Before posting issue...**

1. Run using non-headless mode: `python BingRewards -nhl`
2. Copy relevant output from `errors.log`

**Your Issue - include the details from the above steps:**

**Issue**
Time to time, there is a ChromeDriver update, and every time the script is stuck because its require a Google Chrome update.
I'm not always in the position to update Google Chrome as well.
Would be possible to select a fixed version of ChromeDriver, and update this value manually accordingly to my browser?

thank you

**Log**
```
Traceback (most recent call last):

  File "/home/runner/work/bing-rewards/bing-rewards/BingRewards/src/driver.py", line 176, in get_driver
    driver = cls.WebDriverCls(driver_path, options=options)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    RemoteWebDriver.__init__(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 101.0.4951.64 with binary path /usr/bin/google-chrome
Stacktrace:
#0 0x5627882a9f33 <unknown>
#1 0x562787ff4118 <unknown>
#2 0x56278801b1c5 <unknown>
#3 0x5627880169d0 <unknown>
#4 0x562788012d5a <unknown>
#5 0x56278804dd3a <unknown>
#6 0x562788047e63 <unknown>
#7 0x56278801d82a <unknown>
#8 0x56278801e985 <unknown>
#9 0x5627882ee4cd <unknown>
#10 0x5627882f25ec <unknown>
#11 0x5627882d871e <unknown>
#12 0x5627882f3238 <unknown>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/bing-rewards/bing-rewards/BingRewards/BingRewards.py", line 154, in <module>
    main()
  File "/home/runner/work/bing-rewards/bing-rewards/BingRewards/BingRewards.py", line 116, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "/home/runner/work/bing-rewards/bing-rewards/BingRewards/BingRewards.py", line 77, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "/home/runner/work/bing-rewards/bing-rewards/BingRewards/src/rewards.py", line 1368, in complete_search_type
    self.__get_driver(device_type)
  File "/home/runner/work/bing-rewards/bing-rewards/BingRewards/src/rewards.py", line 1255, in __get_driver
    self.driver = self.driver_factory.get_driver(
  File "/home/runner/work/bing-rewards/bing-rewards/BingRewards/src/driver.py", line [18], in get_driver
    raise SessionNotCreatedException(
selenium.common.exceptions.SessionNotCreatedException: Message: Tried downloading the 3 most recent drivers. None match your browser version. Aborting now, please update your browser.

Warning: User set the password in plain text. Use `-p` with no arguments next time for better security.

Command line options selected:
email=***, search_type=remaining, driver=<class 'src.driver.ChromeDriverFactory'>, headless=True, cookies=False, nosandbox=False, telegram=True, google_sheets=True, google_trends_geo=US

You selected remaining
Downloading Linux chromedriver version: 103.0.5060.[24]
Downloading Linux chromedriver version: 102.0.5005.61
Downloading Linux chromedriver version: 101.0.4951.[41]
Telegram notification sent

Error: Process completed with exit code 1.
```

**Comment by malesci** [comment]
Your comment make sense for sure.
For now I mitigated the issue by scripting for update of Google Chrome browser and chrome driver as well at the latest version before every run.
