### ISSUE TITLE
Message: no such element: Unable to locate element.

### ISSUE THREAD

**Issue by ivanmarban** [jjjchens235/bing-rewards#24]
Python 3.7.7
macOS 10.13.6

It seems that div elements has changed...

```python > Starting Edge search
       >> Logging in
           << Successfully logged in
       >> Starting search
Traceback (most recent call last):
  File "BingRewards/BingRewards.py", line 136, in <module>
    __main(args[0], arg1)
  File "BingRewards/BingRewards.py", line 56, in __main
    rewards.complete_edge_search(hist_log.get_search_hist())
  File "/Volumes/Macintosh HDD/Desarrollo/workspace/bing-rewards/BingRewards/src/rewards.py", line 792, in complete_edge_search
    driver = self.__complete_edge_search()
  File "/Volumes/Macintosh HDD/Desarrollo/workspace/bing-rewards/BingRewards/src/rewards.py", line 666, in __complete_edge_search
    self.completion.edge_search = self.__search(driver, Driver.WEB_DEVICE, is_edge_search)
  File "/Volumes/Macintosh HDD/Desarrollo/workspace/bing-rewards/BingRewards/src/rewards.py", line 185, in __search
    current_progress, complete_progress = self.__get_search_progress(driver, device, is_edge)
  File "/Volumes/Macintosh HDD/Desarrollo/workspace/bing-rewards/BingRewards/src/rewards.py", line 115, in __get_search_progress
    progress_name = element.find_element_by_xpath('./div/div[2]/mee-rewards-user-points-details/div/div/div/div/p[1]').text.lower()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 271, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 235, in find_element
    return self._dispatch("find", (by, value, self._driver), "find_element", (by, value))
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 294, in _dispatch
    raise e
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 291, in _dispatch
    result = getattr(self._webelement, d_call)(*d_args)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 518, in find_element
    {"using": by, "value": value})['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"./div/div[2]/mee-rewards-user-points-details/div/div/div/div/p[1]"}
  (Session info: headless chrome=80.0.3987.132)```

**Comment by joeblack2k** [comment]
Same here ?
is there a fix available ?

**Comment by jjjchens235** [comment]
I ran this today and the searches worked fine. Are you guys in the United States? Either way, I'm not sure I can fix though, as I cannot replicate this bug.

**Comment by deadman36g** [comment]
I am in the US

**Comment by ivanmarban** [comment]
Spain here.

**Comment by joeblack2k** [comment]
Netherlands here
