### ISSUE TITLE
Bot stuck after login

### ISSUE THREAD

**Issue by IcyFrogs** [jjjchens235/bing-rewards#243]
After the bot signs in and clicks "yes" on the "stay signed in" dialog, the next page just sits there loading forever
then after 2 minutes it gives up and the bot closes with error

![stck](https://user-images.githubusercontent.com/92159377/178292279-fd23e895-564d-488d-9ec3-178b4a46c83d.png)

You selected remaining

DevTools listening on ws://127.0.0.1:56568/devtools/browser/b2d4a09f-b46d-42e2-9902-0829524c836e
       >> Logging in
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\bing-rewards-1.11\BingRewards\BingRewards.py", line 172, in <module>
    main()
  File "C:\Users\Admin\Desktop\bing-rewards-1.11\BingRewards\BingRewards.py", line 130, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\Admin\Desktop\bing-rewards-1.11\BingRewards\BingRewards.py", line 90, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\Admin\Desktop\bing-rewards-1.11\BingRewards\src\rewards.py", line 1368, in complete_search_type
    self.__get_driver(device_type)
  File "C:\Users\Admin\Desktop\bing-rewards-1.11\BingRewards\src\rewards.py", line 1258, in __get_driver
    self.__login()
  File "C:\Users\Admin\Desktop\bing-rewards-1.11\BingRewards\src\rewards.py", line 173, in __login
    is_login_complete = self.__check_login_url(self.driver.current_url)
  File "C:\Users\Admin\Desktop\bing-rewards-1.11\BingRewards\src\rewards.py", line 148, in __check_login_url
    raise RuntimeError("Made it to an unrecognized page during login process.")
RuntimeError: Made it to an unrecognized page during login process.

**Comment by lowrank** [comment]
I still had the same issue though.

**Comment by IcyFrogs** [comment]
AH yes you are right. It's still happening. Strangely though just now it got past the loading page so I assumed it was working but then the bot later crashed and now the same thing is happening again hehe

**Comment by wastingoctober** [comment]
Mine is having this issue as well, but it does appear to be a server-side problem. Hopefully Microsoft gets it resolved soon.

**Comment by lowrank** [comment]
It is a server side issue. The mobile and edge searches are fine, mine stuck at web searches. Decide to manually do it. : )

**Comment by wastingoctober** [comment]
> It is a server side issue. The mobile and edge searches are fine, mine stuck at web searches. Decide to manually do it. : )
Thanks for the specifics, I'll just have it do everything else then.

**Comment by IcyFrogs** [comment]
Yeah most likely. Will try it again tomorrow, thanks

**Comment by DimaRazb** [comment]
Same here. Huh, it looks like the issue started four days ago. I see successful reports on July 7th.

**Comment by IcyFrogs** [comment]
Yep working perfectly now 👍
