### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by mgrimace** [jjjchens235/bing-rewards#245]
**Before posting issue...**

1. Run using non-headless mode: `python BingRewards -nhl`

```
python3 BingRewards.py -nhl
Traceback (most recent call last):
  File "BingRewards.py", line 7, in <module>
    from src.rewards import Rewards
  File "/home/ubuntu/bing-rewards/BingRewards/src/rewards.py", line 21, in <module>
    class Rewards:
  File "/home/ubuntu/bing-rewards/BingRewards/src/rewards.py", line 34, in Rewards
    messengers: list[BaseMessenger]
TypeError: 'type' object is not subscriptable
```

2. Copy relevant output from `errors.log`

Doesn't start/no log?

**Your Issue - include the details from the above steps:**

I updated to the most recent release v1.12 using the ./update.sh, and running the script now gives me the above error. I'm using Ubuntu 20.04 on a virtual server accessed via SSH terminal

**Comment by jjjchens235** [comment]
Hmm, what version of Python are you using? 
I think list annotation was introduced only in Python 3.9.

I will try to update this code to be backward compatible with older versions of python, but the immediate fix would be to update python I think.

**Comment by mgrimace** [comment]
Looks like 3.8 on my end, that's the likely culprit! It seems like 3.8 is the base version of python in 20.04, I'll have to look into how to manually update it on my end. In terms of the error/issue though, that's likely it. I'll drop back to previous release in the meantime and post anything relevant that emerges. Thanks!

**Comment by jjjchens235** [comment]
I updated dev branch, if you have a chance, please try it out and let me know if it fixes your issue.

**Comment by mgrimace** [comment]
Ah yes, just crashed out of search:

```
ython3 BingRewards/BingRewards.py

Command line options selected:
email=None, search_type=remaining, driver=<class 'src.driver.ChromeDriverFactory'>, headless=True, cookies=False, nosandbox=False, telegram=False, discord=False, google_sheets=False, google_trends_geo=US

['Thu, Jul 14 2022 10:30AM', 'Failed Edge Search, Web Search, Mobile Search, Offers, Latest Punch Card Activity']

You selected remaining
       >> Logging in
           << Successfully logged in
> Starting Edge search
       >> Starting search
              >>> Progress: [##############################] 12/12 (100%)
           << Successfully completed search
    < Successfully completed Edge search

> Starting Mobile search
       >> Starting search
              >>> Progress: [######                        ] 12/60 (20%)> Error during Mobile search:
 Traceback (most recent call last):
  File "/home/ubuntu/bing-rewards/BingRewards/src/rewards.py", line 1288, in __complete_action
    completion = action(**action_kwargs)
  File "/home/ubuntu/bing-rewards/BingRewards/src/rewards.py", line 390, in __search
    self.__handle_alerts()
  File "/home/ubuntu/bing-rewards/BingRewards/src/rewards.py", line 953, in __handle_alerts
    self.driver.switch_to.alert.dismiss()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/switch_to.py", line 56, in alert
    _ = alert.text
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/common/alert.py", line 66, in text
    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)["value"]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: headless chrome=103.0.5060.114)
Stacktrace:
#0 0x5640cd883f33 <unknown>
#1 0x5640cd5ce118 <unknown>
#2 0x5640cd5b9008 <unknown>
#3 0x5640cd5b7c0f <unknown>
#4 0x5640cd5b819c <unknown>
#5 0x5640cd5c65ff <unknown>
#6 0x5640cd5c7162 <unknown>
#7 0x5640cd5d524d <unknown>
#8 0x5640cd5d866a <unknown>
#9 0x5640cd5b85c6 <unknown>
#10 0x5640cd5d4f54 <unknown>
#11 0x5640cd5e13ac <unknown>
#12 0x5640cd621e63 <unknown>
#13 0x5640cd5f782a <unknown>
#14 0x5640cd5f8985 <unknown>
#15 0x5640cd8c84cd <unknown>
#16 0x5640cd8cc5ec <unknown>
#17 0x5640cd8b271e <unknown>
#18 0x5640cd8cd238 <unknown>
#19 0x5640cd8a7870 <unknown>
#20 0x5640cd8e9608 <unknown>
#21 0x5640cd8e9788 <unknown>
#22 0x5640cd903f1d <unknown>
#23 0x7fb57475b609 <unknown>```

**Comment by jjjchens235** [comment]
I suspect the error stems from the following issue regarding chromedriver v103:
https://github.com/jjjchens235/bing-rewards/issues/239

**Comment by mgrimace** [comment]
> I suspect the error stems from the following issue regarding chromedriver v103: #239
> 
> Edit: Do you not get this error in the previous bing-rewards version?

It just started for me but might be coincidental too, as it is no more issues on my end fully working now. I ended up updating Ubuntu from 20.04 to 22.04 as well which seemed to resolve the chromedriver error, though I'm not sure why since I'm still on v103. Either way, seems to be working!

Python 3.10.04
Chrome 103.0.5060.114
