### ISSUE TITLE
Bing Wallpaper App Notification Problem !! How Can I Fix It?

### ISSUE THREAD

**Issue by islamheroooo** [jjjchens235/bing-rewards#246]
![Screenshot 2022-07-13 154733](https://user-images.githubusercontent.com/27694267/178778299-0adfdd62-43eb-48a5-adf8-3afd96799e5d.png)

1. Afte running script using non-headless mode: `python BingRewards -nhl` and see what caused the problem It appears that Bing Wallpaper pop up cause error and after that Script crashes.

2. I'm running the ( python-3.10.4 ) version.

3. This is the output I received after crashing in Telegram
{
"C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 183, in click
    self._dispatch("click", (self._webelement, self._driver), "click", ())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 200, in _dispatch
    result = getattr(self._webelement, d_call)(*d_args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 88, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 396, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <input type="button" value="Heinrich Böll" id="rqAnswerOption1" class="rqOption" data-serpquery="/search?q=Heinrich Böll
}

Thanks For the support ;
@chen-ye 
@conlon 
@ShoGinn 
@glinesbdev

**Comment by islamheroooo** [comment]
any help !!

**Comment by islamheroooo** [comment]
It was working before perfectly.

**Comment by jjjchens235** [comment]
Your market is based off of where you live. So i dont think you can change that without risking ban. 

However, if you provide the full stack trace (i think you only provided an excerpt) , maybe we can isolate the issue.

Also need to provide the element id of the popup

**Comment by islamheroooo** [comment]
I will be mad!
when doing the regular searches without the script to get the pop-up id, it didn't appear at all but when making the Script do the searches It appears every time.
this is the full trace

(
Thu, Jul 14 2022 09:03PM
Traceback (most recent call last):

  File "C:\Users\islam\Downloads\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\islam\Downloads\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\islam\Downloads\BingRewards\src\rewards.py", line 1395, in complete_search_type
    self.__complete_punchcard()
  File "C:\Users\islam\Downloads\BingRewards\src\rewards.py", line 1345, in __complete_punchcard
    self.completion.punchcard = self.__complete_action(
  File "C:\Users\islam\Downloads\BingRewards\src\rewards.py", line 1287, in __complete_action
    completion = action(**action_kwargs)
  File "C:\Users\islam\Downloads\BingRewards\src\rewards.py", line 1203, in __punchcard
    activity_index = self.__punchcard_activity(parent_url, punchcard['childPromotions'])
  File "C:\Users\islam\Downloads\BingRewards\src\rewards.py", line 1151, in __punchcard_activity
    self.__quiz()
  File "C:\Users\islam\Downloads\BingRewards\src\rewards.py", line 831, in __quiz
    ).click()
  File "C:\Users\islam\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 183, in click
    self._dispatch("click", (self._webelement, self._driver), "click", ())
  File "C:\Users\islam\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 200, in _dispatch
    result = getattr(self._webelement, d_call)(*d_args)
  File "C:\Users\islam\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 88, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\islam\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 396, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\islam\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "C:\Users\islam\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <input type="button" value="Sam Panopoulos" id="rqAnswerOption1" class="rqOption" data-serpquery="/search?q=Sam+Panopoulos&amp;filters=BTQI%3A%221%22+BTCI%3A%221%22+ShowTimesTaskPaneTrigger%3A%22false%22&amp;skipopalnative=true&amp;rnoreward=1&amp;FORM=ML151V" data-option="Sam Panopoulos" tabindex="0" role="button" aria-label="Second of 4 options. Sam Panopoulos"> is not clickable at point (260, 808). Other element would receive the click: <span id="b_desc" class="b_desc">...</span>
  (Session info: chrome=105.0.5172.0)
Stacktrace:
Backtrace:
	Ordinal0 [0x006C8823+2197539]
	Ordinal0 [0x00660911+1771793]
	Ordinal0 [0x00573FE8+802792]
	Ordinal0 [0x005A8AF7+1018615]
	Ordinal0 [0x005A6AA8+1010344]
	Ordinal0 [0x005A479B+1001371]
	Ordinal0 [0x005A3509+996617]
	Ordinal0 [0x00599093+954515]
	Ordinal0 [0x005BD65C+1103452]
	Ordinal0 [0x00598A74+952948]
	Ordinal0 [0x005BD874+1103988]
	Ordinal0 [0x005CDA72+1170034]
	Ordinal0 [0x005BD476+1102966]
	Ordinal0 [0x00597660+947808]
	Ordinal0 [0x00598556+951638]
	GetHandleVerifier [0x00971A32+2740578]
	GetHandleVerifier [0x00963776+2682534]
	GetHandleVerifier [0x0075307A+518058]
	GetHandleVerifier [0x00752196+514246]
	Ordinal0 [0x00667ADB+1800923]
	Ordinal0 [0x0066C2E8+1819368]
	Ordinal0 [0x0066C3D5+1819605]
	Ordinal0 [0x00675810+1857552]
	BaseThreadInitThunk [0x76786739+25]
	RtlGetFullPathName_UEx [0x77148FEF+1215]
	RtlGetFullPathName_UEx [0x77148FBD+1165]


Starting new HTTPS connection (1): api.telegram.org:443
https://api.telegram.org:443 "GET /bot5359327379:AAGGyWwZa3i2EjXEndkM3GG0OII-/sendMessage?chat_id=142128398&text=Traceback%20(most%20recent%20call%20last):%0A%20%20File%20%22C:%5CUsers%5Cislam%5CCBingRewards%5CBingRewards.py%22,%20line%20135,%20in%20main%0A%20%20%20%20complete_search(rewards,%20completion,%20args.search_type,%20search_hist)%0A%20%20File%20%22C:%5CUsers%5Cislam%5CCBingRewards%5CBingRewards.py%22,%20line%2092,%20in%20complete_search%0A%20%20%20%20rewards.complete_search_type(search_type,%20completion,%20search_hist)%0A%20%20File%20%22C:%5CUsers%5Cislam%5CCBingRewards%5Csrc%5Crewards.py%22,%20line%201395,%20in%20complete_search_type%0A%20%20%20%20self.__complete_punchcard()%0A%20%20File%20%22C:%5CUsers%5Cislam%5CCBingRewards%5Csrc%5Crewards.py%22,%20line%201345,%20in%20__complete_punchcard%0A%20%20%20%20self.completion.punchcard%20=%20self.__complete_action(%0A%20%20File%20%22C:%5CUsers%5Cislam%5CCBingRewards%5Csrc%5Crewards.py%22,%20line%201287,%20in%20__complete_action%0A%20%20%20%20completion%20=%20action(**action_kwargs)%0A%20%20File%20%22C:%5CUsers%5Cislam%5CCBingRewards%5Csrc%5Crewards.py%22,%20line%201203,%20in%20__punchcard%0A%20%20%20%20activity_index%20=%20self.__punchcard_activity(parent_url,%20punchcard%5B'childPromotions'%5D)%0A%20%20File%20%22C:%5CUsers%5Cislam%5CCBingRewards%5Csrc%5Crewards.py%22,%20line%201151,%20in%20__punchcard_activity%0A%20%20%20%20self.__quiz()%0A%20%20File%20%22C:%5CUsers%5Cislam%5CCBingRewards%5Csrc%5Crewards.py%22,%20line%20831,%20in%20__quiz%0A%20%20%20%20).click()%0A%20%20File%20%22C:%5CUsers%5Cislam%5CAppData%5CLocal%5CPrograms%5CPython%5CPython310%5Clib%5Csite-packages%5Cselenium%5Cwebdriver%5Csupport%5Cevent_firing_webdriver.py%22,%20line%20183,%20in%20click%0A%20%20%20%20self._dispatch(%22click%22,%20(self._webelement,%20self._driver),%20%22click%22,%20())%0A%20%20File%20%22C:%5CUsers%5Cislam%5CAppData%5CLocal%5CPrograms%5CPython%5CPython310%5Clib%5Csite-packages%5Cselenium%5Cwebdriver%5Csupport%5Cevent_firing_webdriver.py%22,%20line%20200,%20in%20_dispatch%0A%20%20%20%20result%20=%20getattr(self._webelement,%20d_call)(*d_args)%0A%20%20File%20%22C:%5CUsers%5Cislam%5CAppData%5CLocal%5CPrograms%5CPython%5CPython310%5Clib%5Csite-packages%5Cselenium%5Cwebdriver%5Cremote%5Cwebelement.py%22,%20line%2088,%20in%20click%0A%20%20%20%20self._execute(Command.CLICK_ELEMENT)%0A%20%20File%20%22C:%5CUsers%5Cislam%5CAppData%5CLocal%5CPrograms%5CPython%5CPython310%5Clib%5Csite-packages%5Cselenium%5Cwebdriver%5Cremote%5Cwebelement.py%22,%20line%20396,%20in%20_execute%0A%20%20%20%20return%20self._parent.execute(command,%20params)%0A%20%20File%20%22C:%5CUsers%5Cislam%5CAppData%5CLocal%5CPrograms%5CPython%5CPython310%5Clib%5Csite-packages%5Cselenium%5Cwebdriver%5Cremote%5Cwebdriver.py%22,%20line%20435,%20in%20execute%0A%20%20%20%20self.error_handler.check_response(response)%0A%20%20File%20%22C:%5CUsers%5Cislam%5CAppData%5CLocal%5CPrograms%5CPython%5CPython310%5Clib%5Csite-packages%5Cselenium%5Cwebdriver%5Cremote%5Cerrorhandler.py%22,%20line%20247,%20in%20check_response%0A%20%20%20%20raise%20exception_class(message,%20screen,%20stacktrace)%0Aselenium.common.exceptions.ElementClickInterceptedException:%20Message:%20element%20click%20intercepted:%20Element%20%3Cinput%20type=%22button%22%20value=%22Sam%20Panopoulos%22%20id=%22rqAnswerOption1%22%20class=%22rqOption%22%20data-serpquery=%22/search?q=Sam+Panopoulos&amp;filters=BTQI%3A%221%22+BTCI%3A%221%22+ShowTimesTaskPaneTrigger%3A%22false%22&amp;skipopalnative=true&amp;rnoreward=1&amp;FORM=ML151V%22%20data-option=%22Sam%20Panopoulos%22%20tabindex=%220%22%20role=%22button%22%20aria-label=%22Second%20of%204%20options.%20Sam%20Panopoulos%22%3E%20is%20not%20clickable%20at%20point%20(260,%20808).%20Other%20element%20would%20receive%20the%20click:%20%3Cspan%20id=%22b_desc%22%20class=%22b_desc%22%3E...%3C/span%3E%0A%20%20(Session%20info:%20chrome=105.0.5172.0)%0AStacktrace:%0ABacktrace:%0A%09Ordinal0%20%5B0x006C8823+2197539%5D%0A%09Ordinal0%20%5B0x00660911+1771793%5D%0A%09Ordinal0%20%5B0x00573FE8+802792%5D%0A%09Ordinal0%20%5B0x005A8AF7+1018615%5D%0A%09Ordinal0%20%5B0x005A6AA8+1010344%5D%0A%09Ordinal0%20%5B0x005A479B+1001371%5D%0A%09Ordinal0%20%5B0x005A3509+996617%5D%0A%09Ordinal0%20%5B0x00599093+954515%5D%0A%09Ordinal0%20%5B0x005BD65C+1103452%5D%0A%09Ordinal0%20%5B0x00598A74+952948%5D%0A%09Ordinal0%20%5B0x005BD874+1103988%5D%0A%09Ordinal0%20%5B0x005CDA72+1170034%5D%0A%09Ordinal0%20%5B0x005BD476+1102966%5D%0A%09Ordinal0%20%5B0x00597660+947808%5D%0A%09Ordinal0%20%5B0x00598556+951638%5D%0A%09GetHandleVerifier%20%5B0x00971A32+2740578%5D%0A%09GetHandleVerifier%20%5B0x00963776+2682534%5D%0A%09GetHandleVerifier%20%5B0x0075307A+518058%5D%0A%09GetHandleVerifier%20%5B0x00752196+514246%5D%0A%09Ordinal0%20%5B0x00667ADB+1800923%5D%0A%09Ordinal0%20%5B0x0066C2E8+1819368%5D%0A%09Ordinal0%20%5B0x0066C3D5+1819605%5D%0A%09Ordinal0%20%5B0x00675810+1857552%5D%0A%09BaseThreadInitThunk%20%5B0x76786739+25%5D%0A%09RtlGetFullPathName_UEx%20%5B0x77148FEF+1215%5D%0A%09RtlGetFullPathName_UEx%20%5B0x77148FBD+1165%5D%0A%0A HTTP/1.1" 200 3910 )

and thanks a lot for your help I really appreciate this "
@jjjchens235

**Comment by ShoGinn** [comment]
So I think with the current code construct getting page source isn't possible. I'll recommend the fix be a debug setting that saves the page html so we can isolate the popup.

**Comment by jjjchens235** [comment]
which punchcard is this? I'm assuiming it's `"Fancy yourself a foodie?` Day 1.

 I tried simulating this again with a different account but I'm not getting this popup:
```sh
['Sun, Jul 17 2022 07:01PM', 'Failed Edge Search, Web Search, Mobile Search, Offers, Latest Punch Card Activity']

You selected punch card
       >> Logging in
           << Successfully logged in
> Starting punch card
       >> Punch card "Fancy yourself a foodie?" is not complete yet.
       >> Starting activity "Day 1: Guilty pleasures"
           << Sign in Bing bug for offer 'Day 1: Guilty pleasures', will try again
              >>> Starting quiz
              >>> Multiple choice
                     >>>> Progress: [##############################] 10/10 (100%)
                  <<< Successfully completed quiz
              >>> Latest punch card activity successfully completed!
       >> Punch card "Resident Evil Season 1" is not complete yet.
       >> Starting activity "Activate punch card"
              >>> Latest punch card activity successfully completed!
       >> Overall punch card progress: 1 of 4 completed
    < Successfully completed punch card
```

**Comment by farshadz1997** [comment]
@jjjchens235 
Hi,
I work on Microsoft Rewards bot as well and encountered with this issue as well, try adding `driver.find_element(By.ID, 'bnp_btn_accept').click()`  in all quizzes and polls function in the bot to fix the problem.
