### ISSUE TITLE
RuntimeError: Unable to handle https://login.live.com/

### ISSUE THREAD

**Issue by solarbeam122** [jjjchens235/bing-rewards#248]
Recently ran into an issue where the script won't work, just started today and I'm not sure what's going on. I have pasted the following, if you need more info I can provide. I live in the USA. 

Mon, Jul 18 2022 09:14AM
Traceback (most recent call last):
  File "C:\bing-rewards\BingRewards\src\rewards.py", line 144, in __check_login_url
    authenticator_code = self.driver.find_element(By.ID, "idRemoteNGC_DisplaySign").text
  File "C:\Users\Justus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 108, in find_element
    return self._dispatch("find", (by, value, self._driver), "find_element", (by, value))
  File "C:\Users\Justus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 183, in _dispatch
    raise e
  File "C:\Users\Justus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 180, in _dispatch
    result = getattr(self._driver, d_call)(*d_args)
  File "C:\Users\Justus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 1251, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Justus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Justus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="idRemoteNGC_DisplaySign"]"}
  (Session info: headless chrome=103.0.5060.114)
Stacktrace:
Backtrace:
	Ordinal0 [0x010E6463+2188387]
	Ordinal0 [0x0107E461+1762401]
	Ordinal0 [0x00F93D78+802168]
	Ordinal0 [0x00FC1880+989312]
	Ordinal0 [0x00FC1B1B+989979]
	Ordinal0 [0x00FEE912+1173778]
	Ordinal0 [0x00FDC824+1099812]
	Ordinal0 [0x00FECC22+1166370]
	Ordinal0 [0x00FDC5F6+1099254]
	Ordinal0 [0x00FB6BE0+945120]
	Ordinal0 [0x00FB7AD6+948950]
	GetHandleVerifier [0x013871F2+2712546]
	GetHandleVerifier [0x0137886D+2652765]
	GetHandleVerifier [0x0117002A+520730]
	GetHandleVerifier [0x0116EE06+516086]
	Ordinal0 [0x0108468B+1787531]
	Ordinal0 [0x01088E88+1805960]
	Ordinal0 [0x01088F75+1806197]
	Ordinal0 [0x01091DF1+1842673]
	BaseThreadInitThunk [0x7554FA29+25]
	RtlGetAppContainerNamedObjectPath [0x776C7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x776C7A6E+238]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bing-rewards\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\bing-rewards\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\bing-rewards\BingRewards\src\rewards.py", line 1379, in complete_search_type
    self.__get_driver(device_type)
  File "C:\bing-rewards\BingRewards\src\rewards.py", line 1269, in __get_driver
    self.__login()
  File "C:\bing-rewards\BingRewards\src\rewards.py", line 183, in __login
    is_login_complete = self.__check_login_url(self.driver.current_url)
  File "C:\bing-rewards\BingRewards\src\rewards.py", line 153, in __check_login_url
    raise RuntimeError(f"Unable to handle {url}")
RuntimeError: Unable to handle https://login.live.com/

$ python BingRewards -nhl
C:\Users\Justus\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe: can't find '__main__' module in 'C:\\bing-rewards\\BingRewards'

**Comment by solarbeam122** [comment]
Actually you can close this, I figured it out. My apologies.

**Comment by coollbv** [comment]
It was Microsoft login outage yesterday...

**Comment by RotatingWires** [comment]
hey I'm having the same issue what'd you do to fix
![image](https://user-images.githubusercontent.com/100501698/181588122-9f0b7bc8-cb17-45fe-841e-259a3f3632d5.png)

**Comment by jjjchens235** [comment]
looks like everyone is good here.
