### ISSUE TITLE
unknown error: session deleted because of page crash

### ISSUE THREAD

**Issue by UltimateWishub** [jjjchens235/bing-rewards#250]
**Before posting issue...**

1. Run using non-headless mode: `python BingRewards -nhl`
2. Copy relevant output from `errors.log`

**Your Issue - include the details from the above steps:**
Wed, Jul 20 2022 12:04PM
Traceback (most recent call last):
  File "C:\Users\(user)\Documents\bing-rewards-1.12\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\(user)\Documents\bing-rewards-1.12\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\(user)\Documents\bing-rewards-1.12\BingRewards\src\rewards.py", line 1383, in complete_search_type
    self.complete_remaining_searches(search_type, prev_completion)
  File "C:\Users\(user)\Documents\bing-rewards-1.12\BingRewards\src\rewards.py", line 1361, in complete_remaining_searches
    self.__complete_edge_search()
  File "C:\Users\(user)\Documents\bing-rewards-1.12\BingRewards\src\rewards.py", line 1310, in __complete_edge_search
    self.completion.edge_search = self.__complete_action(
  File "C:\Users\(user)\Documents\bing-rewards-1.12\BingRewards\src\rewards.py", line 1287, in __complete_action
    completion = action(**action_kwargs)
  File "C:\Users\(user)\Documents\bing-rewards-1.12\BingRewards\src\rewards.py", line 336, in __search
    progress = self.__get_search_progress(search_type)
  File "C:\Users\(user)\Documents\bing-rewards-1.12\BingRewards\src\rewards.py", line 252, in __get_search_progress
    user_status = self.get_dashboard_data()['userStatus']
  File "C:\Users\(user)\Documents\bing-rewards-1.12\BingRewards\src\rewards.py", line 233, in get_dashboard_data
    self.__open_dashboard()
  File "C:\Users\(user)\Documents\bing-rewards-1.12\BingRewards\src\rewards.py", line 199, in __open_dashboard
    self.driver.get(self.__DASHBOARD_URL)
  File "C:\Users\(user)\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 83, in get
    self._dispatch("navigate_to", (url, self._driver), "get", (url, ))
  File "C:\Users\(user)\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 114, in _dispatch
    result = getattr(self._driver, d_call)(*d_args)
  File "C:\Users\(user)\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 447, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\(user)\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "C:\Users\(user)\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: MicrosoftEdge=102.0.1245.56)
Stacktrace:
Backtrace:
  Microsoft::Applications::Events::EventProperties::unpack [0x00007FF6C0413AA2+24578]
  Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x00007FF6C034E612+563634]
  Ordinal0 [0x00007FF6BFE50E6B+659051]
  Ordinal0 [0x00007FF6BFE3E034+581684]
  Ordinal0 [0x00007FF6BFE3D915+579861]
  Ordinal0 [0x00007FF6BFE3CE14+577044]
  Ordinal0 [0x00007FF6BFE3BB60+572256]
  Ordinal0 [0x00007FF6BFE3C0E3+573667]
  Ordinal0 [0x00007FF6BFE491A6+627110]
  Ordinal0 [0x00007FF6BFE595F2+693746]
  Ordinal0 [0x00007FF6BFE5CFF9+708601]
  Ordinal0 [0x00007FF6BFE3C485+574597]
  Ordinal0 [0x00007FF6BFE591A1+692641]
  Ordinal0 [0x00007FF6BFEBBFDB+1097691]
  Ordinal0 [0x00007FF6BFEA75C3+1013187]
  Ordinal0 [0x00007FF6BFE7E4E0+845024]
  Ordinal0 [0x00007FF6BFE7F8D8+850136]
  Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6C0105278+119992]
  Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6C00F0D87+36807]
  Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6C00F3F1C+49500]
  Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6BFF4F606+20582]
  Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x00007FF6C0355A7B+593435]
  Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x00007FF6C035AFB4+615252]
  Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x00007FF6C035B10D+615597]
  Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x00007FF6C0365D1E+659646]
  BaseThreadInitThunk [0x00007FFA200E244D+29]
  RtlUserThreadStart [0x00007FFA2152DF88+40]

**Comment by UltimateWishub** [comment]
it might be because of low ram i have 4 gb

**Comment by Killerherts** [comment]
> it might be because of low ram i have 4 gb

You're more than likely correct I have had a ton of issues running in containers with limited memory and the error looks the same. You could try my fork it writes directly to the disk to avoid this issue for containers.

**Comment by UltimateWishub** [comment]
> You're more than likely correct I have had a ton of issues running in containers with limited memory and the error looks the same. You could try my fork it writes directly to the disk to avoid this issue for containers.

im not that experienced in github so idk how to use your fork, but i tried running with sandbox mode turned off and it worked

**Comment by Killerherts** [comment]
> > You're more than likely correct I have had a ton of issues running in containers with limited memory and the error looks the same. You could try my fork it writes directly to the disk to avoid this issue for containers.
> 
> im not that experienced in github so idk how to use your fork, but i tried running with sandbox mode turned off and it worked

Awesome go ahead close the issue if it's still working for you.
