### ISSUE TITLE
Problem with MacOS M1 PRO

### ISSUE THREAD

**Issue by deathart** [jjjchens235/bing-rewards#253]
Hello

After searching for hours on the internet for my error I found nothing, when launching the command I got an error directly, here is my error.log file:

```
Thu, Jul 28 2022 04:50PM
Traceback (most recent call last):
  File "/Users/deathart/bingrewards/elune/BingRewards/src/driver.py", line 197, in get_driver
    driver = cls.WebDriverCls(driver_path, options=options)
  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service drivers/chromedriver unexpectedly exited. Status code was: -9


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/deathart/bingrewards/elune/BingRewards/BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "/Users/deathart/bingrewards/elune/BingRewards/BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "/Users/deathart/bingrewards/elune/BingRewards/src/rewards.py", line 1379, in complete_search_type
    self.__get_driver(device_type)
  File "/Users/deathart/bingrewards/elune/BingRewards/src/rewards.py", line 1266, in __get_driver
    self.driver = self.driver_factory.get_driver(
  File "/Users/deathart/bingrewards/elune/BingRewards/src/driver.py", line 223, in get_driver
    raise WebDriverException(error_msg)
selenium.common.exceptions.WebDriverException: Message: Message: Service drivers/chromedriver unexpectedly exited. Status code was: -9
```

My command:

`python3 BingRewards/BingRewards.py -d chrome -di -c -nhl`

Thanks :)

**Comment by jjjchens235** [comment]
can you try one more time with updated code in master?

**Comment by deathart** [comment]
Hello, thanks its work perfectly !

**Comment by jjjchens235** [comment]
Yay!
