### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by physlikenan** [jjjchens235/bing-rewards#255]
Traceback (most recent call last):
  File ".\BingRewards.py", line 7, in <module>
    from src.rewards import Rewards
  File "C:\Users\kenan\Documents\bing-rewards-master\bing-rewards-master\BingRewards\src\rewards.py", line 21, in <module>
    class Rewards:
  File "C:\Users\kenan\Documents\bing-rewards-master\bing-rewards-master\BingRewards\src\rewards.py", line 34, in Rewards
    messengers: list[BaseMessenger]
TypeError: 'type' object is not subscriptable

**Comment by jjjchens235** [comment]
dup of this:
https://github.com/jjjchens235/bing-rewards/issues/245

tl dr: a recent change introduced a python feature compatible only with python 3.9+. 
I have updated master branch to make this <3.8 compatible, please try updated code.
