### ISSUE TITLE
no such element: Unable to locate element when running headless

### ISSUE THREAD

**Issue by raphalation** [jjjchens235/bing-rewards#265]
Recieving the bellow error when running headless. Works fine however when using -nhl. Any ideas?

You selected remaining

DevTools listening on ws://127.0.0.1:59480/devtools/browser/f051d8fd-6030-48d3-a134-e2f6d84a5f43
       >> Logging in
Traceback (most recent call last):
  File "C:\Users\rapha\Documents\bing-rewards\BingRewards\src\rewards.py", line 145, in __check_login_url
    authenticator_code = self.driver.find_element(By.ID, "idRemoteNGC_DisplaySign").text
  File "C:\Users\rapha\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 108, in find_element
    return self._dispatch("find", (by, value, self._driver), "find_element", (by, value))
  File "C:\Users\rapha\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 180, in _dispatch
    result = getattr(self._driver, d_call)(*d_args)
  File "C:\Users\rapha\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 1251, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\rapha\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\rapha\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="idRemoteNGC_DisplaySign"]"}
  (Session info: headless chrome=105.0.5195.54)
Stacktrace:
Backtrace:
        Ordinal0 [0x008BC0A3+2212003]
        Ordinal0 [0x00852CC1+1780929]
        Ordinal0 [0x0076465D+804445]
        Ordinal0 [0x00793475+996469]
        Ordinal0 [0x0079363B+996923]
        Ordinal0 [0x007C1382+1184642]
        Ordinal0 [0x007AEC64+1109092]
        Ordinal0 [0x007BF5B2+1177010]
        Ordinal0 [0x007AEA36+1108534]
        Ordinal0 [0x007883C9+951241]
        Ordinal0 [0x00789396+955286]
        GetHandleVerifier [0x00B69CE2+2746722]
        GetHandleVerifier [0x00B5A234+2682548]
        GetHandleVerifier [0x0094B34A+524234]
        GetHandleVerifier [0x00949B60+518112]
        Ordinal0 [0x00859FBC+1810364]
        Ordinal0 [0x0085EA28+1829416]
        Ordinal0 [0x0085EB15+1829653]
        Ordinal0 [0x00868744+1869636]
        BaseThreadInitThunk [0x75026739+25]
        RtlGetFullPathName_UEx [0x76FC90AF+1215]
        RtlGetFullPathName_UEx [0x76FC907D+1165]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rapha\Documents\bing-rewards\BingRewards\BingRewards.py", line 179, in <module>
    main()
  File "C:\Users\rapha\Documents\bing-rewards\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\rapha\Documents\bing-rewards\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\rapha\Documents\bing-rewards\BingRewards\src\rewards.py", line 1380, in complete_search_type
    self.__get_driver(device_type)
  File "C:\Users\rapha\Documents\bing-rewards\BingRewards\src\rewards.py", line 1270, in __get_driver
    self.__login()
  File "C:\Users\rapha\Documents\bing-rewards\BingRewards\src\rewards.py", line 184, in __login
    is_login_complete = self.__check_login_url(self.driver.current_url)
  File "C:\Users\rapha\Documents\bing-rewards\BingRewards\src\rewards.py", line 154, in __check_login_url
    raise RuntimeError(f"Unable to handle {url}")
RuntimeError: Unable to handle https://login.live.com/

**Comment by raphalation** [comment]
Seemed to be an issue with the config.json file. Resolved by editing manually
