### ISSUE TITLE
Discord Message error not sent

### ISSUE THREAD

**Issue by Fluff663** [jjjchens235/bing-rewards#271]
Errors.log contents
Starting new HTTPS connection (1): discord.com:443
https://discord.com:443 "POST /api/webhooks/1010388696689811568/dAVyHBnRKYy15saZnh_sV3F60aXiQEwry9OlyKl5u3t3Yt-s18vl0EMsnmuScQSiwqxA HTTP/1.1" 400 49
Thu, Sep 01 2022 04:30PM
Traceback (most recent call last):
  File "C:\Users\Fluff\Desktop\bing-rewards-master\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\Fluff\Desktop\bing-rewards-master\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\Fluff\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 1384, in complete_search_type
    self.complete_remaining_searches(search_type, prev_completion)
  File "C:\Users\Fluff\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 1364, in complete_remaining_searches
    self.__complete_mobile_search()
  File "C:\Users\Fluff\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 1330, in __complete_mobile_search
    self.completion.mobile_search = self.__complete_action(
  File "C:\Users\Fluff\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 1288, in __complete_action
    completion = action(**action_kwargs)
  File "C:\Users\Fluff\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 377, in __search
    search_box.send_keys(query, Keys.RETURN)  # unique search term
  File "C:\Users\Fluff\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 189, in send_keys
    self._dispatch("change_value_of", (self._webelement, self._driver), "send_keys", value)
  File "C:\Users\Fluff\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 200, in _dispatch
    result = getattr(self._webelement, d_call)(*d_args)
  File "C:\Users\Fluff\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 223, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\Fluff\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 396, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Fluff\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Fluff\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=105.0.5195.54)
Stacktrace:
Backtrace:
	Ordinal0 [0x00C5DF13+2219795]
	Ordinal0 [0x00BF2841+1779777]
	Ordinal0 [0x00B0423D+803389]
	Ordinal0 [0x00B06D04+814340]
	Ordinal0 [0x00B06BC2+814018]
	Ordinal0 [0x00B06E50+814672]
	Ordinal0 [0x00B33A4B+997963]
	Ordinal0 [0x00B33B21+998177]
	Ordinal0 [0x00B2C1D4+967124]
	Ordinal0 [0x00B4E7FC+1107964]
	Ordinal0 [0x00B294B4+955572]
	Ordinal0 [0x00B4EA14+1108500]
	Ordinal0 [0x00B5F192+1175954]
	Ordinal0 [0x00B4E616+1107478]
	Ordinal0 [0x00B27F89+950153]
	Ordinal0 [0x00B28F56+954198]
	GetHandleVerifier [0x00F52CB2+3040210]
	GetHandleVerifier [0x00F42BB4+2974420]
	GetHandleVerifier [0x00CF6A0A+565546]
	GetHandleVerifier [0x00CF5680+560544]
	Ordinal0 [0x00BF9A5C+1808988]
	Ordinal0 [0x00BFE3A8+1827752]
	Ordinal0 [0x00BFE495+1827989]
	Ordinal0 [0x00C080A4+1867940]
	BaseThreadInitThunk [0x76227BA9+25]
	RtlInitializeExceptionChain [0x7748BB3B+107]
	RtlClearBits [0x7748BABF+191]

Starting new HTTPS connection (1): discord.com:443
https://discord.com:443 "POST /api/webhooks/1010388696689811568/

Output in console
> Starting Mobile search
       >> Starting search
              >>> Progress: [#####################         ] 70/100 (70%)Boo! Discord notification NOT sent, response code is: <Response [400]> with response msg `{"content": ["Must be 2000 or fewer in length."]}`

Traceback (most recent call last):
  File "C:\Users\Fluff\Desktop\bing-rewards-master\BingRewards\BingRewards.py", line 179, in <module>
    main()
  File "C:\Users\Fluff\Desktop\bing-rewards-master\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\Fluff\Desktop\bing-rewards-master\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\Fluff\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 1384, in complete_search_type
    self.complete_remaining_searches(search_type, prev_completion)
  File "C:\Users\Fluff\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 1364, in complete_remaining_searches
    self.__complete_mobile_search()
  File "C:\Users\Fluff\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 1330, in __complete_mobile_search
    self.completion.mobile_search = self.__complete_action(
  File "C:\Users\Fluff\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 1288, in __complete_action
    completion = action(**action_kwargs)
  File "C:\Users\Fluff\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 377, in __search
    search_box.send_keys(query, Keys.RETURN)  # unique search term
  File "C:\Users\Fluff\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 189, in send_keys
    self._dispatch("change_value_of", (self._webelement, self._driver), "send_keys", value)
  File "C:\Users\Fluff\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 200, in _dispatch
    result = getattr(self._webelement, d_call)(*d_args)
  File "C:\Users\Fluff\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 223, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\Fluff\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 396, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Fluff\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Fluff\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=105.0.5195.54)
Stacktrace:
Backtrace:
        Ordinal0 [0x00C5DF13+2219795]
        Ordinal0 [0x00BF2841+1779777]
        Ordinal0 [0x00B0423D+803389]
        Ordinal0 [0x00B06D04+814340]
        Ordinal0 [0x00B06BC2+814018]
        Ordinal0 [0x00B06E50+814672]
        Ordinal0 [0x00B33A4B+997963]
        Ordinal0 [0x00B33B21+998177]
        Ordinal0 [0x00B2C1D4+967124]
        Ordinal0 [0x00B4E7FC+1107964]
        Ordinal0 [0x00B294B4+955572]
        Ordinal0 [0x00B4EA14+1108500]
        Ordinal0 [0x00B5F192+1175954]
        Ordinal0 [0x00B4E616+1107478]
        Ordinal0 [0x00B27F89+950153]
        Ordinal0 [0x00B28F56+954198]
        GetHandleVerifier [0x00F52CB2+3040210]
        GetHandleVerifier [0x00F42BB4+2974420]
        GetHandleVerifier [0x00CF6A0A+565546]
        GetHandleVerifier [0x00CF5680+560544]
        Ordinal0 [0x00BF9A5C+1808988]
        Ordinal0 [0x00BFE3A8+1827752]
        Ordinal0 [0x00BFE495+1827989]
        Ordinal0 [0x00C080A4+1867940]
        BaseThreadInitThunk [0x76227BA9+25]
        RtlInitializeExceptionChain [0x7748BB3B+107]
        RtlClearBits [0x7748BABF+191]

**Comment by Fluff663** [comment]
This error only seems to occur when i specify the -nhl argument

**Comment by jjjchens235** [comment]
I apologize if I'm missing your point, but when I ran it with `-di -nhl` it works perfectly fine:

```sh
BingRewards/ on branch dev
(ins)$ python BingRewards.py -pc -c -di -nhl

Command line options selected:
email=None, search_type=punch card, driver=<class 'src.driver.ChromeDriverFactory'>, headless=False, cookies=True, nosandbox=False, telegram=False, discord=True, google_sheets=False, google_trends_geo=US

['Sun, Sep 11 2022 05:41PM', 'Failed Edge Search, Web Search, Mobile Search, Offers, Latest Punch Card Activity']

You selected punch card
       >> Logging in
           << Successfully logged in
> Starting punch card
       >> Punch card "Refresh your memory" is already completed.
       >> Overall punch card progress: 4 of 4 completed
    < Successfully completed punch card


> Summary
       >> Points earned this run: 0
       >> Microsoft 'Points earned' today: 328
       >> Streak count: 13
       >> 13 days
       >> Available points: 2,508
       >> Lifetime points: 425,008

['Sun, Sep 11 2022 05:44PM', 'Failed Edge Search, Web Search, Mobile Search, Offers']
Discord notification sent
```

**Comment by Fluff663** [comment]
it looks like another error caused the log to be so long discord wouldnt take it

**Comment by jjjchens235** [comment]
Oh i see your point.. this would definitely do it:
```
>>> Progress: [##################### ] 70/100 (70%)
Boo! Discord notification NOT sent, response code is: <Response [400]> with response msg {"content": ["Must be 2000 or fewer in length."]}
```
