### ISSUE TITLE
Timeout exceptions on open_dashboard

### ISSUE THREAD

**Issue by pepershukov** [jjjchens235/bing-rewards#272]
I am really clueless why this timeout occured on the dashboard. It loaded the page 3 times, and then exited...
It did successfully log in from my email and password from the config file.
I am running this in a fresh venv in hopes of a 'no-conflict' situation.

I am sorry if this is a similar copy of another issue, as I couldn't find a fix to this...

Any ideas on the problem?
Here is the console output...
```
(venv) 10:10:35.39 | C:\Users\peter\Downloads\bing-rewards\BingRewards$ python BingRewards.py -nhl

Command line options selected:
email=None, search_type=remaining, driver=<class 'src.driver.ChromeDriverFactory'>, headless=False, cookies=False, nosandbox=False, telegram=False, discord=False, google_sheets=False, google_trends_geo=US

['Wed, Sep 07 2022 10:09AM', 'Failed Edge Search, Web Search, Mobile Search, Offers, Latest Punch Card Activity']

You selected remaining

DevTools listening on ws://127.0.0.1:20009/devtools/browser/358bfbc4-74f3-4fee-a751-7a225dcff6e4
       >> Logging in
           << Successfully logged in
Traceback (most recent call last):
  File "C:\Users\peter\Downloads\bing-rewards\BingRewards\src\rewards.py", line 217, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.presence_of_element_located((By.XPATH, offer_xpath)))
  File "C:\Users\peter\Downloads\bing-rewards\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x002978B3+2193587]
        Ordinal0 [0x00230681+1771137]
        Ordinal0 [0x001441A8+803240]
        Ordinal0 [0x001724A0+992416]
        Ordinal0 [0x0017273B+993083]
        Ordinal0 [0x0019F7C2+1177538]
        Ordinal0 [0x0018D7F4+1103860]
        Ordinal0 [0x0019DAE2+1170146]
        Ordinal0 [0x0018D5C6+1103302]
        Ordinal0 [0x001677E0+948192]
        Ordinal0 [0x001686E6+952038]
        GetHandleVerifier [0x00540CB2+2738370]
        GetHandleVerifier [0x005321B8+2678216]
        GetHandleVerifier [0x003217AA+512954]
        GetHandleVerifier [0x00320856+509030]
        Ordinal0 [0x0023743B+1799227]
        Ordinal0 [0x0023BB68+1817448]
        Ordinal0 [0x0023BC55+1817685]
        Ordinal0 [0x00245230+1856048]
        BaseThreadInitThunk [0x75E0FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77A67A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77A67A6E+238]
        (No symbol) [0x00000000]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\peter\Downloads\bing-rewards\BingRewards\src\rewards.py", line 217, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.presence_of_element_located((By.XPATH, offer_xpath)))
  File "C:\Users\peter\Downloads\bing-rewards\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x002978B3+2193587]
        Ordinal0 [0x00230681+1771137]
        Ordinal0 [0x001441A8+803240]
        Ordinal0 [0x001724A0+992416]
        Ordinal0 [0x0017273B+993083]
        Ordinal0 [0x0019F7C2+1177538]
        Ordinal0 [0x0018D7F4+1103860]
        Ordinal0 [0x0019DAE2+1170146]
        Ordinal0 [0x0018D5C6+1103302]
        Ordinal0 [0x001677E0+948192]
        Ordinal0 [0x001686E6+952038]
        GetHandleVerifier [0x00540CB2+2738370]
        GetHandleVerifier [0x005321B8+2678216]
        GetHandleVerifier [0x003217AA+512954]
        GetHandleVerifier [0x00320856+509030]
        Ordinal0 [0x0023743B+1799227]
        Ordinal0 [0x0023BB68+1817448]
        Ordinal0 [0x0023BC55+1817685]
        Ordinal0 [0x00245230+1856048]
        BaseThreadInitThunk [0x75E0FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77A67A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77A67A6E+238]
        (No symbol) [0x00000000]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\peter\Downloads\bing-rewards\BingRewards\BingRewards.py", line 179, in <module>
    main()
  File "C:\Users\peter\Downloads\bing-rewards\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\peter\Downloads\bing-rewards\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\peter\Downloads\bing-rewards\BingRewards\src\rewards.py", line 1381, in complete_search_type
    init_points = self.__get_available_points()
  File "C:\Users\peter\Downloads\bing-rewards\BingRewards\src\rewards.py", line 1279, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
  File "C:\Users\peter\Downloads\bing-rewards\BingRewards\src\rewards.py", line 234, in get_dashboard_data
    self.__open_dashboard()
  File "C:\Users\peter\Downloads\bing-rewards\BingRewards\src\rewards.py", line 221, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\peter\Downloads\bing-rewards\BingRewards\src\rewards.py", line 221, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\peter\Downloads\bing-rewards\BingRewards\src\rewards.py", line 220, in __open_dashboard
    raise(e)
  File "C:\Users\peter\Downloads\bing-rewards\BingRewards\src\rewards.py", line 217, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.presence_of_element_located((By.XPATH, offer_xpath)))
  File "C:\Users\peter\Downloads\bing-rewards\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x002978B3+2193587]
        Ordinal0 [0x00230681+1771137]
        Ordinal0 [0x001441A8+803240]
        Ordinal0 [0x001724A0+992416]
        Ordinal0 [0x0017273B+993083]
        Ordinal0 [0x0019F7C2+1177538]
        Ordinal0 [0x0018D7F4+1103860]
        Ordinal0 [0x0019DAE2+1170146]
        Ordinal0 [0x0018D5C6+1103302]
        Ordinal0 [0x001677E0+948192]
        Ordinal0 [0x001686E6+952038]
        GetHandleVerifier [0x00540CB2+2738370]
        GetHandleVerifier [0x005321B8+2678216]
        GetHandleVerifier [0x003217AA+512954]
        GetHandleVerifier [0x00320856+509030]
        Ordinal0 [0x0023743B+1799227]
        Ordinal0 [0x0023BB68+1817448]
        Ordinal0 [0x0023BC55+1817685]
        Ordinal0 [0x00245230+1856048]
        BaseThreadInitThunk [0x75E0FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77A67A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77A67A6E+238]
        (No symbol) [0x00000000]


(venv) 10:14:43.01 | C:\Users\peter\Downloads\bing-rewards\BingRewards$
```

**Comment by numbor** [comment]
The same thing happens to me.
I tried to change the value of the constant __WEB_DRIVER_WAIT_SHORT from 5 to 15, but without success.

**Comment by numbor** [comment]
it seems to wait for the loading of the page, but does not find certain elements.

rewards.py:216 offer_xpath = '//*[@id="daily-sets"]/mee-card-group[1]/div/mee-card[1]/div/card-content/mee-rewards-daily-set-item-content/div/a'

**Comment by pepershukov** [comment]
**Found the problem.** Basically all it was is a **regional issue** - I live in Cyprus and not in USA. And so the website functoniality differs A TON.
**The solution** is to **use a VPN to connect to USA**, or anyhow make your region be that.

At the end of the day, I got it working!!
