### ISSUE TITLE
Too many timeout exceptions

### ISSUE THREAD

**Issue by kbuffington** [jjjchens235/bing-rewards#28]
I'm on level 2 and can't get searches to work:

```
> Starting Edge search

DevTools listening on ws://127.0.0.1:64167/devtools/browser/51fa9d74-0543-4cc1-93a8-7da821add27d
       >> Logging in
           << Successfully logged in
       >> Starting search
                  <<< When searching, too many time out exceptions when getting progress element
Traceback (most recent call last):
  File "BingRewards\BingRewards.py", line 136, in <module>
    __main(args[0], arg1)
  File "BingRewards\BingRewards.py", line 86, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "D:\Source\bing-rewards\BingRewards\src\rewards.py", line 857, in complete_all
    driver = self.__complete_edge_search()
  File "D:\Source\bing-rewards\BingRewards\src\rewards.py", line 706, in __complete_edge_search
    self.completion.edge_search = self.__search(driver, Driver.WEB_DEVICE, is_edge_search)
  File "D:\Source\bing-rewards\BingRewards\src\rewards.py", line 185, in __search
    current_progress, complete_progress = self.__get_search_progress(driver, device, is_edge)
  File "D:\Source\bing-rewards\BingRewards\src\rewards.py", line 114, in __get_search_progress
    for element in progress_elements:
UnboundLocalError: local variable 'progress_elements' referenced before assignment
```

**Comment by kbuffington** [comment]
Looks like when I attempted to copy/paste my password while running setup.py it didn't take and therefore even though it says `<< Successfully logged in` I was not logged in at all. Working fine now.
