### ISSUE TITLE
Running in docker - no space left on device

### ISSUE THREAD

**Issue by Lexxior** [jjjchens235/bing-rewards#289]
Running the container with the given compose config gives this error
There is more than enough space left on the device and permissions are set for the user in the compose file

```
+ echo 'Linking bing-rewards logs to /logs'

Linking bing-rewards logs to /logs

+ mkdir /bing-rewards/BingRewards/logs

mkdir: cannot create directory ‘/bing-rewards/BingRewards/logs’: No such file or directory

+ ln -s /bing-rewards/BingRewards/logs /bing

ln: failed to create symbolic link '/bing/logs': File exists

+ touch /bing-rewards/BingRewards/logs/cronBing.log

touch: cannot touch '/bing-rewards/BingRewards/logs/cronBing.log': No such file or directory

+ touch /bing-rewards/BingRewards/logs/error.log

touch: cannot touch '/bing-rewards/BingRewards/logs/error.log': No such file or directory

+ cd /bing-rewards/BingRewards

/entry.sh: line 21: cd: /bing-rewards/BingRewards: No such file or directory

+ tail -f '/bing-rewards/BingRewards/logs/*.log'

tail: cannot open '/bing-rewards/BingRewards/logs/*.log' for reading: No such file or directory

tail: no files remaining

+ service cron start

Starting periodic command scheduler: cron.

+ crontab /etc/cron.d/bing.cron

+ echo 'Cloning jjchens235/bing-rewards'

Cloning jjchens235/bing-rewards

+ git clone --branch dev https://github.com/jjjchens235/bing-rewards.git /bing-rewards/

Cloning into '/bing-rewards'...

/bing-rewards/.git: No space left on device

+ echo 'Setting Up pip and installing requirements'

Setting Up pip and installing requirements

+ python -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable

ERROR: Exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper

    status = run_func(*args)

  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper

    return func(self, options, args)

  File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 294, in run

    wheel_cache = WheelCache(options.cache_dir, options.format_control)

  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cache.py", line 219, in __init__

    self._ephem_cache = EphemWheelCache(format_control)

  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cache.py", line 191, in __init__

    self._temp_dir = TempDirectory(

  File "/usr/local/lib/python3.9/site-packages/pip/_internal/utils/temp_dir.py", line 125, in __init__

    path = self._create(kind)

  File "/usr/local/lib/python3.9/site-packages/pip/_internal/utils/temp_dir.py", line 164, in _create

    path = os.path.realpath(tempfile.mkdtemp(prefix=f"pip-{kind}-"))

  File "/usr/local/lib/python3.9/tempfile.py", line 363, in mkdtemp

    _os.mkdir(file, 0o700)

OSError: [Errno 28] No space left on device: '/tmp/pip-ephem-wheel-cache-_8939u8m'

+ pip install --no-warn-script-location -r /bing-rewards/BingRewards/requirements.txt

Defaulting to user installation because normal site-packages is not writeable

ERROR: Exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper

    status = run_func(*args)

  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper

    return func(self, options, args)

  File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 294, in run

    wheel_cache = WheelCache(options.cache_dir, options.format_control)

  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cache.py", line 219, in __init__

    self._ephem_cache = EphemWheelCache(format_control)

  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cache.py", line 191, in __init__

    self._temp_dir = TempDirectory(

  File "/usr/local/lib/python3.9/site-packages/pip/_internal/utils/temp_dir.py", line 125, in __init__

    path = self._create(kind)

  File "/usr/local/lib/python3.9/site-packages/pip/_internal/utils/temp_dir.py", line 164, in _create

    path = os.path.realpath(tempfile.mkdtemp(prefix=f"pip-{kind}-"))

  File "/usr/local/lib/python3.9/tempfile.py", line 363, in mkdtemp

    _os.mkdir(file, 0o700)

OSError: [Errno 28] No space left on device: '/tmp/pip-ephem-wheel-cache-rervbvyu'

+ test -f /config/config.json

+ echo 'Config was imported linking /config/config.json to /bing-rewards/BingRewards/config'

Config was imported linking /config/config.json to /bing-rewards/BingRewards/config

+ mkdir /bing-rewards/BingRewards/config

mkdir: cannot create directory ‘/bing-rewards/BingRewards/config’: No such file or directory

+ ln -s /config/config.json /bing-rewards/BingRewards/config/config.json

ln: failed to create symbolic link '/bing-rewards/BingRewards/config/config.json': No such file or directory

+ echo 'Linking bing-rewards logs to /logs'

Linking bing-rewards logs to /logs

+ mkdir /bing-rewards/BingRewards/logs

mkdir: cannot create directory ‘/bing-rewards/BingRewards/logs’: No such file or directory

+ ln -s /bing-rewards/BingRewards/logs /bing

ln: failed to create symbolic link '/bing/logs': File exists

+ touch /bing-rewards/BingRewards/logs/cronBing.log

touch: cannot touch '/bing-rewards/BingRewards/logs/cronBing.log': No such file or directory

+ touch /bing-rewards/BingRewards/logs/error.log

touch: cannot touch '/bing-rewards/BingRewards/logs/error.log': No such file or directory

+ cd /bing-rewards/BingRewards

/entry.sh: line 21: cd: /bing-rewards/BingRewards: No such file or directory

+ tail -f '/bing-rewards/BingRewards/logs/*.log'

tail: cannot open '/bing-rewards/BingRewards/logs/*.log' for reading: No such file or directory

tail: no files remaining

+ service cron start

Starting periodic command scheduler: cron.

+ crontab /etc/cron.d/bing.cron

+ echo 'Cloning jjchens235/bing-rewards'

Cloning jjchens235/bing-rewards

+ git clone --branch dev https://github.com/jjjchens235/bing-rewards.git /bing-rewards/

Cloning into '/bing-rewards'...

/bing-rewards/.git: No space left on device

+ echo 'Setting Up pip and installing requirements'

Setting Up pip and installing requirements

+ python -m pip install --upgrade pip

```

**Comment by Lexxior** [comment]
Apparently there was something wrong with docker
docker prune and a reboot fixed the issue

**Comment by Lexxior** [comment]
Apparently there was something wrong with docker
docker prune and a reboot fixed the issue
