### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by pearlheartgtr** [jjjchens235/bing-rewards#29]
These errors have been coming up in all three of my accounts.

       >> Logging in
           << Successfully logged in
       >> Starting search
              >>> Progress: [###                           ] 15/150 (10%)                  <<< When searching, too many time out exceptions when getting progress element
Traceback (most recent call last):
  File "C:\Users\...\Desktop\2bing-rewards\BingRewards\BingRewards.py", line 136, in <module>
    __main(args[0], arg1)
  File "C:\Users\...\Desktop\2bing-rewards\BingRewards\BingRewards.py", line 86, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "C:\Users\...\Desktop\2bing-rewards\BingRewards\src\rewards.py", line 858, in complete_all
    self.__complete_web_search()
  File "C:\Users\...\Desktop\2bing-rewards\BingRewards\src\rewards.py", line 730, in __complete_web_search
    self.completion.web_search = self.__search(driver, Driver.WEB_DEVICE)
  File "C:\Users\...\Desktop\2bing-rewards\BingRewards\src\rewards.py", line 185, in __search
    current_progress, complete_progress = self.__get_search_progress(driver, device, is_edge)
  File "C:\Users\...\Desktop\2bing-rewards\BingRewards\src\rewards.py", line 114, in __get_search_progress
    for element in progress_elements:
UnboundLocalError: local variable 'progress_elements' referenced before assignment

**Comment by pearlheartgtr** [comment]
Seems to have been a Bing glitch. It's working again.
