### ISSUE TITLE
A New Web Hero - Failed Offers

### ISSUE THREAD

**Issue by SylveonBottle** [jjjchens235/bing-rewards#292]
```
> Error checking rewards status -
 Traceback (most recent call last):
  File "C:\Users\depre\Documents\bing-rewards\BingRewards\src\rewards.py", line 1251, in __print_stats
    days_to_bonus_str = self.driver.find_elements(
IndexError: list index out of range

['Sat, Oct 15 2022 08:11PM', 'Failed Offers']
```

Opening Bing Rewards manually shows this new icon, stated as not complete:

![image](https://user-images.githubusercontent.com/17802843/196013339-4fe18a1a-62dd-4d6e-9f34-3e6b40d2ac67.png)

After running BingRewards.py with no-headless flag, I was able to find the reward when the browser window popped up. After clicking the link manually, a new page opened up. After closing that page, the script continued as normal and resulted in a success.

```
> Starting punch card
       >> Punch card "Spooky season is here" is already completed.
       >> Punch card "The Classic Fallout Trilogy" is already completed.
       >> Overall punch card progress: 4 of 4 completed
    < Successfully completed punch card

> Error checking rewards status -
 Traceback (most recent call last):
  File "C:\Users\depre\Documents\bing-rewards\BingRewards\src\rewards.py", line 1251, in __print_stats
    days_to_bonus_str = self.driver.find_elements(
IndexError: list index out of range


['Sat, Oct 15 2022 08:13PM', 'Successful']
```

Upon checking the site in my browser once again, it does indeed show a claimed symbol:
![image](https://user-images.githubusercontent.com/17802843/196013424-0eef4312-76ea-4ac3-a1bf-59332609539c.png)

**Comment by SylveonBottle** [comment]
Please note that the link was changed while browsing in no-headless mode. I think it said something like "Click here to try it", or something. It was definitely different from the image provided above.

Also note that I was using msedge for this.
My flags are as followed: `python.exe .\BingRewards.py -d msedge -di -c`
