### ISSUE TITLE
Unable to start - urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by Mariobob** [jjjchens235/bing-rewards#296]
When I run the bot like so: 
python3 BingRewards/BingRewards.py -di it attempts to start but fails. The error is

Traceback (most recent call last):
  File "/Users/mariobob/Desktop/Automations/Bing-Rewards/BingRewards/BingRewards.py", line 179, in <module>
    main()
  File "/Users/mariobob/Desktop/Automations/Bing-Rewards/BingRewards/BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "/Users/mariobob/Desktop/Automations/Bing-Rewards/BingRewards/BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "/Users/mariobob/Desktop/Automations/Bing-Rewards/BingRewards/src/rewards.py", line 1386, in complete_search_type
    self.__get_driver(device_type)
  File "/Users/mariobob/Desktop/Automations/Bing-Rewards/BingRewards/src/rewards.py", line 1273, in __get_driver
    self.driver = self.driver_factory.get_driver(
  File "/Users/mariobob/Desktop/Automations/Bing-Rewards/BingRewards/src/driver.py", line 197, in get_driver
    cls.__download_driver()
  File "/Users/mariobob/Desktop/Automations/Bing-Rewards/BingRewards/src/driver.py", line 108, in __download_driver
    response = urlopen(
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

If I switch to the msedge driver with the flag -d msedge it works but it doesn't seem to work as well as the chromedriver does. 
edit: device is a m1 macbook air

**Comment by xzor9** [comment]
I have the same issue on my m1 macbook.

**Comment by Mariobob** [comment]
Seems to be gone after pulling the new code from latest commit
