### ISSUE TITLE
Error: Stalls at Login

### ISSUE THREAD

**Issue by PHILLJAY** [jjjchens235/bing-rewards#302]
Trying to get this set up for my friend, installed python from the windows store, used scoop to install github then cloned this into the user/code directory.

We tried a few times but this is the error:

https://pastebin.com/gcM8t8gD

```
Traceback (most recent call last):
  File "C:\Users\blueb\code\bing-rewards\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\blueb\code\bing-rewards\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\blueb\code\bing-rewards\BingRewards\src\rewards.py", line 1386, in complete_search_type
    self.__get_driver(device_type)
  File "C:\Users\blueb\code\bing-rewards\BingRewards\src\rewards.py", line 1276, in __get_driver
    self.__login()
  File "C:\Users\blueb\code\bing-rewards\BingRewards\src\rewards.py", line 190, in __login
    is_login_complete = self.__check_login_url(self.driver.current_url)
  File "C:\Users\blueb\code\bing-rewards\BingRewards\src\rewards.py", line 117, in __check_login_url
    WebDriverWait(self.driver, 30).until(
  File "C:\Users\blueb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
Backtrace:
	Ordinal0 [0x0036ACD3+2075859]
	Ordinal0 [0x002FEE61+1633889]
	Ordinal0 [0x001FB7BD+571325]
	Ordinal0 [0x0022AC2F+764975]
	Ordinal0 [0x0022AE1B+765467]
	Ordinal0 [0x0025D0F2+970994]
	Ordinal0 [0x00247364+881508]
	Ordinal0 [0x0025B56A+963946]
	Ordinal0 [0x00247136+880950]
	Ordinal0 [0x0021FEFD+720637]
	Ordinal0 [0x00220F3F+724799]
	GetHandleVerifier [0x0061EED2+2769538]
	GetHandleVerifier [0x00610D95+2711877]
	GetHandleVerifier [0x003FA03A+521194]
	GetHandleVerifier [0x003F8DA0+516432]
	Ordinal0 [0x0030682C+1665068]
	Ordinal0 [0x0030B128+1683752]
	Ordinal0 [0x0030B215+1683989]
	Ordinal0 [0x00316484+1729668]
	BaseThreadInitThunk [0x75F17BA9+25]
	RtlInitializeExceptionChain [0x7746BB9B+107]
	RtlClearBits [0x7746BB1F+191]

```

even after switching to edge this still happens, wondering if someone could help me out here, thanks!

**Comment by badplay** [comment]
i am not a programmer
but i never use the install from windows store becoorse this want work for many pprogramms at me. so install python from website with exe. alsow at install let the path install click it on addpatch. 
then install the requierements and install the gitfiles inside own folder and start setup.py then start bingrewards.py and try

**Comment by jjjchens235** [comment]
It's hard to tell from the log, do you mind running the program with the `-nhl` flag and report what the behavior of the browser is, i.e what page does it get to before error'ing out?

**Comment by PHILLJAY** [comment]
I'm going to try to install python properly instead of from the windows store first. I'll update if the issue persists

**Comment by PHILLJAY** [comment]
Update: installing python properly from the web helped. Never trusting the windows store again. As an aside Microsoft should really take that down if its going to break things.
