### ISSUE TITLE
Unable to handle https://login.live.com/

### ISSUE THREAD

**Issue by Dr0mus** [jjjchens235/bing-rewards#309]
Traceback (most recent call last):
  File "/mnt/c/Users/Dromu/Documents/bing-rewards/BingRewards/src/rewards.py", line 151, in __check_login_url
    authenticator_code = self.driver.find_element(By.ID, "idRemoteNGC_DisplaySign").text
  File "/home/luna/.local/lib/python3.10/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 105, in find_element
    return self._dispatch("find", (by, value, self._driver), "find_element", (by, value))
  File "/home/luna/.local/lib/python3.10/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 115, in _dispatch
    result = getattr(self._driver, d_call)(*d_args)
  File "/home/luna/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/luna/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/home/luna/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="idRemoteNGC_DisplaySign"]"}
  (Session info: chrome=107.0.5304.110)
Stacktrace:
#0 0x55f60a282463 <unknown>
#1 0x55f60a0468d8 <unknown>
#2 0x55f60a08443a <unknown>
#3 0x55f60a084651 <unknown>
#4 0x55f60a0c07a4 <unknown>
#5 0x55f60a0a564d <unknown>
#6 0x55f60a0be30f <unknown>
#7 0x55f60a0a5443 <unknown>
#8 0x55f60a0763c5 <unknown>
#9 0x55f60a077531 <unknown>
#10 0x55f60a2d4dce <unknown>
#11 0x55f60a2d8192 <unknown>
#12 0x55f60a2b993e <unknown>
#13 0x55f60a2d9103 <unknown>
#14 0x55f60a2acd85 <unknown>
#15 0x55f60a2fa0a8 <unknown>
#16 0x55f60a2fa239 <unknown>
#17 0x55f60a315492 <unknown>
#18 0x7f80bb34fb43 <unknown>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/Dromu/Documents/bing-rewards/BingRewards/BingRewards.py", line 179, in <module>
    main()
  File "/mnt/c/Users/Dromu/Documents/bing-rewards/BingRewards/BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "/mnt/c/Users/Dromu/Documents/bing-rewards/BingRewards/BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "/mnt/c/Users/Dromu/Documents/bing-rewards/BingRewards/src/rewards.py", line 1386, in complete_search_type
    self.__get_driver(device_type)
  File "/mnt/c/Users/Dromu/Documents/bing-rewards/BingRewards/src/rewards.py", line 1276, in __get_driver
    self.__login()
  File "/mnt/c/Users/Dromu/Documents/bing-rewards/BingRewards/src/rewards.py", line 190, in __login
    is_login_complete = self.__check_login_url(self.driver.current_url)
  File "/mnt/c/Users/Dromu/Documents/bing-rewards/BingRewards/src/rewards.py", line 160, in __check_login_url
    raise RuntimeError(f"Unable to handle {url}")
RuntimeError: Unable to handle https://login.live.com/

**Your Issue - include the details from the above steps:**
I just ran it randomly today and it didn't work today. On other machines it's working fine (not with my personal account but another), for my account personal account I have 2fa and when I was doing -nhl it showed me this:
![image](https://user-images.githubusercontent.com/38384816/202695868-ad2f38a6-8938-49a6-9512-a54a6c0f4e3c.png)
When it got to the 2 factor page it didn't wait for me to press the right number but it waited like 4-5 seconds and then went that ^. I saw that there was another post about this issue but it login outage from Microsoft.

**Comment by deathart** [comment]
Hello, I have the same problem only on my account that has access to the new interface

**Comment by fafzal820** [comment]
I started having the same issue today.

**Comment by dagda3** [comment]
Was there ever a solution to this? Having the issue today.

**Comment by deathart** [comment]
Same for me

**Comment by Dr0mus** [comment]
I haven't found a solution, The computer I was using this on was had low specs. I am using this on a more powerful computer and it seems to work fine now.

**Comment by fafzal820** [comment]
I haven't found a solution. My computer has pretty solid specs. I tried removing the entire folder. Reload latest version from here but no luck. Same issue when trying to login.
