### ISSUE TITLE
Apparentl driver issue when MSEdge updates

### ISSUE THREAD

**Issue by dabluecaboose** [jjjchens235/bing-rewards#314]
```
Sun, Nov 27 2022 03:55PM
Traceback (most recent call last):
  File "D:\misc\bing-rewards-1.14\BingRewards\src\driver.py", line 202, in get_driver
    driver = cls.WebDriverCls(driver_path, options=options)
  File "C:\Users\viper\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\edge\webdriver.py", line 82, in __init__
    keep_alive,
  File "C:\Users\viper\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 114, in __init__
    options=options,
  File "C:\Users\viper\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\viper\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\viper\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\viper\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 105
Current browser version is 107.0.1418.56 with binary path C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
Stacktrace:
Backtrace:
	Microsoft::Applications::Events::EventProperties::SetProperty [0x00007FF705582012+17554]
	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF70551E962+1438514]
	Ordinal0 [0x00007FF705149345+627525]
	Ordinal0 [0x00007FF7051773D4+816084]
	Ordinal0 [0x00007FF7051728B3+796851]
	Ordinal0 [0x00007FF70516D9F0+776688]
	Ordinal0 [0x00007FF7051A969F+1021599]
	Ordinal0 [0x00007FF7051A3A43+997955]
	Ordinal0 [0x00007FF7051794C0+824512]
	Ordinal0 [0x00007FF70517A9F8+829944]
	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF7053E02F8+134344]
	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF7053C9C25+42485]
	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF7053CCD0C+55004]
	Ordinal0 [0x00007FF705234F14+1593108]
	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF7055240AB+1460859]
	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF705528074+1477188]
	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF7055281CD+1477533]
	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF705530199+1510249]
	BaseThreadInitThunk [0x00007FF8F5E874B4+20]
	RtlUserThreadStart [0x00007FF8F5FC26A1+33]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\BingRewards\BingRewards.py", line 135, in main
  File ".\BingRewards\BingRewards.py", line 92, in complete_search
  File "D:\misc\bing-rewards-1.14\BingRewards\src\rewards.py", line 1386, in complete_search_type
    self.__get_driver(device_type)
  File "D:\misc\bing-rewards-1.14\BingRewards\src\rewards.py", line 1274, in __get_driver
    device_type, self.headless, self.cookies, self.nosandbox
  File "D:\misc\bing-rewards-1.14\BingRewards\src\driver.py", line 210, in get_driver
    raise SessionNotCreatedException(error_msg)
selenium.common.exceptions.SessionNotCreatedException: Message: message: session not created: this version of microsoft edge webdriver only supports microsoft edge version 105
current browser version is 107.0.1418.56 with binary path c:\program files (x86)\microsoft\edge\application\msedge.exe
stacktrace:
backtrace:
	microsoft::applications::events::eventproperties::setproperty [0x00007ff705582012+17554]
	microsoft::applications::events::eventproperty::eventproperty [0x00007ff70551e962+1438514]
	ordinal0 [0x00007ff705149345+627525]
	ordinal0 [0x00007ff7051773d4+816084]
	ordinal0 [0x00007ff7051728b3+796851]
	ordinal0 [0x00007ff70516d9f0+776688]
	ordinal0 [0x00007ff7051a969f+1021599]
	ordinal0 [0x00007ff7051a3a43+997955]
	ordinal0 [0x00007ff7051794c0+824512]
	ordinal0 [0x00007ff70517a9f8+829944]
	microsoft::applications::events::eventproperty::eventproperty [0x00007ff7053e02f8+134344]
	microsoft::applications::events::eventproperty::eventproperty [0x00007ff7053c9c25+42485]
	microsoft::applications::events::eventproperty::eventproperty [0x00007ff7053ccd0c+55004]
	ordinal0 [0x00007ff705234f14+1593108]
	microsoft::applications::events::eventproperty::eventproperty [0x00007ff7055240ab+1460859]
	microsoft::applications::events::eventproperty::eventproperty [0x00007ff705528074+1477188]
	microsoft::applications::events::eventproperty::eventproperty [0x00007ff7055281cd+1477533]
	microsoft::applications::events::eventproperty::eventproperty [0x00007ff705530199+1510249]
	basethreadinitthunk [0x00007ff8f5e874b4+20]
	rtluserthreadstart [0x00007ff8f5fc26a1+33]
```

I have been wrestling with this issue all morning ever since I discovered I'd lost my streak.  It appears that somehow I updated my msedge and the driver was not being updated, so kept failing.

I resolved this problem by following the advice [here](https://github.com/jjjchens235/bing-rewards/issues/298#issuecomment-1312764775) and deleting my `msedgedriver.exe`.

Maybe there should be more robust logic around when to force a redownload of the driver?  It worked like a charm once I deleted the existing one and forced a redownload.

Just wanted to pass along my suggestions (and leave a detailed traceback in case anyone else had this issue).  Thanks for this awesome tool!

**Comment by jjjchens235** [comment]
Thanks for the head's up!

I tried reproducing this but the redownload is working for me. I was also using an old msedge driver version before running this:

```sh
BingRewards/ on branch dev
(ins)$ python BingRewards.py -d msedge

Command line options selected:
email=None, search_type=remaining, driver=<class 'src.driver.MsEdgeDriverFactory'>, headless=True, cookies=False, nosandbox=False, telegram=False, discord=False, google_sheets=False, google_trends_geo=US

You selected remaining
The downloaded driver does not match browser version...

Downloading Darwin msedgedriver version: 107.0.1418.62
       >> Logging in
           << Successfully logged in
> Starting Edge search
       >> Starting search
              >>> Progress: [##############################] 20/20 (100%)
           << Successfully completed search
    < Successfully completed Edge search
```

**Comment by dabluecaboose** [comment]
Well, if you can't reproduce it then maybe there was just something weird on my end.  Feel free to close this, at least now there's some documentation in the repo in case anyone else runs into this.
