### ISSUE TITLE
[Fixed] Dashboard error due to new URL

### ISSUE THREAD

**Issue by coollbv** [jjjchens235/bing-rewards#317]
Traceback (most recent call last):
  File "C:\msrw\bingrewards\bingrewards.py", line 179, in <module>
    main()
  File "C:\msrw\bingrewards\bingrewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\msrw\bingrewards\bingrewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\msrw\bingrewards\src\rewards.py", line 1387, in complete_search_type
    init_points = self.__get_available_points()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\msrw\bingrewards\src\rewards.py", line 1285, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\msrw\bingrewards\src\rewards.py", line 240, in get_dashboard_data
    self.__open_dashboard()
  File "C:\msrw\bingrewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\msrw\bingrewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\msrw\bingrewards\src\rewards.py", line 226, in __open_dashboard
    raise(e)
  File "C:\msrw\bingrewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Python3\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by lambor590** [comment]
Same with all my accounts.

**Comment by coollbv** [comment]
Looks like @DKL72 found the solution #318

When updating the master file maybe we can get a better/correct breakdown of points
Daily Points (only web/mobile/edge for the day)
Monthly Points
Daily Offers (the 3 changing tiles)
Other Offers (all other offers with or without punchcard separately)

**Comment by jjjchens235** [comment]
Reopening as an FYI for people encountering this issue
Fixed in this PR https://github.com/jjjchens235/bing-rewards/pull/316

**Comment by sbaraka** [comment]
getting a `Issue logging in, please run in -nhl mode to see the problem

Traceback (most recent call last):
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 179, in <module>
    main()
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1387, in complete_search_type
    self.__get_driver(device_type)
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1277, in __get_driver
    self.__login()
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 190, in __login
    is_login_complete = self.__check_login_url(self.driver.current_url)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by jjjchens235** [comment]
> getting a `Issue logging in, please run in -nhl mode to see the problem
> 
> Traceback (most recent call last): File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 179, in main() File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 135, in main complete_search(rewards, completion, args.search_type, search_hist) File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 92, in complete_search rewards.complete_search_type(search_type, completion, search_hist) File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1387, in complete_search_type self.__get_driver(device_type) File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1277, in __get_driver self.__login() File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 190, in __login is_login_complete = self.__check_login_url(self.driver.current_url) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

Please provide the full log, as well as the behavior exhibited when running with -nhl mode

**Comment by sbaraka** [comment]
```> Error during Web search:
 Traceback (most recent call last):
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1294, in __complete_action
    self.__get_driver(mandatory_device_type)
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1277, in __get_driver
    self.__login()
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 190, in __login
    is_login_complete = self.__check_login_url(self.driver.current_url)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 117, in __check_login_url
    WebDriverWait(self.driver, 30).until(
  File "C:\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x00D3ACD3+2075859]
        Ordinal0 [0x00CCEE61+1633889]
        Ordinal0 [0x00BCB7BD+571325]
        Ordinal0 [0x00BFAC2F+764975]
        Ordinal0 [0x00BFAE1B+765467]
        Ordinal0 [0x00C2D0F2+970994]
        Ordinal0 [0x00C17364+881508]
        Ordinal0 [0x00C2B56A+963946]
        Ordinal0 [0x00C17136+880950]
        Ordinal0 [0x00BEFEFD+720637]
        Ordinal0 [0x00BF0F3F+724799]
        GetHandleVerifier [0x00FEEED2+2769538]
        GetHandleVerifier [0x00FE0D95+2711877]
        GetHandleVerifier [0x00DCA03A+521194]
        GetHandleVerifier [0x00DC8DA0+516432]
        Ordinal0 [0x00CD682C+1665068]
        Ordinal0 [0x00CDB128+1683752]
        Ordinal0 [0x00CDB215+1683989]
        Ordinal0 [0x00CE6484+1729668]
        BaseThreadInitThunk [0x7560FEF9+25]
        RtlGetAppContainerNamedObjectPath [0x775D7BBE+286]
        RtlGetAppContainerNamedObjectPath [0x775D7B8E+238]


> Starting Offers
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Python311\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python311\Lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Python311\Lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python311\Lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python311\Lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python311\Lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Python311\Lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Python311\Lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000025384AA5750>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 179, in <module>
    main()
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1391, in complete_search_type
    self.complete_remaining_searches(search_type, prev_completion)
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1375, in complete_remaining_searches
    self.__complete_offers()
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1345, in __complete_offers
    self.completion.offers = self.__complete_action(
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1295, in __complete_action
    completion = action(**action_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1118, in __offers
    self.__open_dashboard()
  File "C:\Users\Koa\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 206, in __open_dashboard
    self.driver.get(self.__DASHBOARD_URL)
  File "C:\Python311\Lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 82, in get
    self._dispatch("navigate_to", (url, self._driver), "get", (url,))
  File "C:\Python311\Lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 115, in _dispatch
    result = getattr(self._driver, d_call)(*d_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 455, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 442, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 294, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 316, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\urllib3\request.py", line 78, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\urllib3\poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=53428): Max retries exceeded with url: /session/d6095bcbe93fd90263666a27dfe9f369/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025384AA5750>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))```

**Comment by weimath** [comment]
@sbaraka 
try
pip install urllib3==1.25.11

**Comment by jjjchens235** [comment]
This error has been fixed for a while now, closing
