### ISSUE TITLE
Logging In Successfully, TimeOut afterwards

### ISSUE THREAD

**Issue by CtrlValCanc** [jjjchens235/bing-rewards#318]
While running it in -nhl it successfully login, goes to the rewards page, refresh it two or three times and gives out this error. Tried reinstalling python (always from the site), installing the requirements, make sure chrome is installed this time. It gives the same error using the msedge drivers. 
Currently on w11.

```
C:\Users\ninal\Documents\bing-rewards-1.15\BingRewards>python BingRewards.py -nhl

Command line options selected:
email=None, search_type=remaining, driver=<class 'src.driver.ChromeDriverFactory'>, headless=False, cookies=False, nosandbox=True, telegram=False, discord=False, google_sheets=False, google_trends_geo=US

['Wed, Nov 30 2022 02:54PM', 'Failed Edge Search, Web Search, Mobile Search, Offers, Latest Punch Card Activity']

You selected remaining

DevTools listening on ws://127.0.0.1:49950/devtools/browser/2c6fb2d7-ab70-4399-b758-1c6a47234df5
       >> Logging in
           << Successfully logged in
Traceback (most recent call last):
  File "C:\Users\ninal\Documents\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ninal\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ninal\Documents\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ninal\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ninal\Documents\bing-rewards-1.15\BingRewards\BingRewards.py", line 179, in <module>
    main()
  File "C:\Users\ninal\Documents\bing-rewards-1.15\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\ninal\Documents\bing-rewards-1.15\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\ninal\Documents\bing-rewards-1.15\BingRewards\src\rewards.py", line 1387, in complete_search_type
    init_points = self.__get_available_points()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ninal\Documents\bing-rewards-1.15\BingRewards\src\rewards.py", line 1285, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ninal\Documents\bing-rewards-1.15\BingRewards\src\rewards.py", line 240, in get_dashboard_data
    self.__open_dashboard()
  File "C:\Users\ninal\Documents\bing-rewards-1.15\BingRewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\ninal\Documents\bing-rewards-1.15\BingRewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\ninal\Documents\bing-rewards-1.15\BingRewards\src\rewards.py", line 226, in __open_dashboard
    raise(e)
  File "C:\Users\ninal\Documents\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ninal\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

**Comment by DKL72** [comment]
This seems to be the same issue as #317 

I found where the issue is. Need to change the URL in rewards.py in **__open_dashboard** to **rewards.bing.com**, it must have changed. This solved the issue for me. 

    def __open_dashboard(self, try_count=0):
        """
        Opens dashboard url
        Checks that the url is correct
        And all the offer elements are loaded
        """
        max_try_count = 2
        self.driver.get(self.__DASHBOARD_URL)

        try:
            #check the url
            WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
                # 'any_of' checks for either condition
                EC.any_of(
                    EC.url_contains("https://rewards.bing.com/?redref"),
                    EC.url_contains("https://rewards.bing.com/")
                )

**Comment by CtrlValCanc** [comment]
> This seems to be the same issue as #317
> 
> I found where the issue is. Need to change the URL in rewards.py in **__open_dashboard** to **rewards.bing.com**, it must have changed. This solved the issue for me.
> 
> ```
> def __open_dashboard(self, try_count=0):
>     """
>     Opens dashboard url
>     Checks that the url is correct
>     And all the offer elements are loaded
>     """
>     max_try_count = 2
>     self.driver.get(self.__DASHBOARD_URL)
> 
>     try:
>         #check the url
>         WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
>             # 'any_of' checks for either condition
>             EC.any_of(
>                 EC.url_contains("https://rewards.bing.com/?redref"),
>                 EC.url_contains("https://rewards.bing.com/")
>             )
> ```
