### ISSUE TITLE
as of Today its not working

### ISSUE THREAD

**Issue by badplay** [jjjchens235/bing-rewards#319]
tryed version 1.15 with chrome and edge but as of today its not working after login it gets a error
C:\Users\beelink\Downloads\Python  \Brewd>"C:\Users\beelink\AppData\Local\Programs\Python\Python37\python.exe" folder1\BingRewards\BingRewards.py -r -nhl -d chrome   & REM You may have to modify the c:\python to the location of your python installation. If it is in program files, make sure to include the whole path in quotes.

Command line options selected:
email=None, search_type=remaining, driver=<class 'src.driver.ChromeDriverFactory'>, headless=False, cookies=False, nosandbox=False, telegram=False, discord=False, google_sheets=False, google_trends_geo=US

You selected remaining
Downloading Windows chromedriver version: 108.0.5359.71

DevTools listening on ws://127.0.0.1:1917/devtools/browser/8a6b4d12-b50a-4fe0-a348-30c04f951a78
The downloaded driver does not match browser version...

Downloading Windows chromedriver version: 107.0.5304.62

DevTools listening on ws://127.0.0.1:1931/devtools/browser/e9d7f889-3af3-43ca-858b-b35866625cd9
       >> Logging in
           << Successfully logged in
Traceback (most recent call last):
  File "C:\Users\beelink\Downloads\Python  \Brewd\folder1\BingRewards\src\rewards.py", line 214, in __open_dashboard
    EC.url_contains("https://rewards.microsoft.com/")
  File "C:\Users\beelink\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\beelink\Downloads\Python  \Brewd\folder1\BingRewards\src\rewards.py", line 214, in __open_dashboard
    EC.url_contains("https://rewards.microsoft.com/")
  File "C:\Users\beelink\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "folder1\BingRewards\BingRewards.py", line 179, in <module>
    main()
  File "folder1\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "folder1\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\beelink\Downloads\Python  \Brewd\folder1\BingRewards\src\rewards.py", line 1387, in complete_search_type
    init_points = self.__get_available_points()
  File "C:\Users\beelink\Downloads\Python  \Brewd\folder1\BingRewards\src\rewards.py", line 1285, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
  File "C:\Users\beelink\Downloads\Python  \Brewd\folder1\BingRewards\src\rewards.py", line 240, in get_dashboard_data
    self.__open_dashboard()
  File "C:\Users\beelink\Downloads\Python  \Brewd\folder1\BingRewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\beelink\Downloads\Python  \Brewd\folder1\BingRewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\beelink\Downloads\Python  \Brewd\folder1\BingRewards\src\rewards.py", line 226, in __open_dashboard
    raise(e)
  File "C:\Users\beelink\Downloads\Python  \Brewd\folder1\BingRewards\src\rewards.py", line 214, in __open_dashboard
    EC.url_contains("https://rewards.microsoft.com/")
  File "C:\Users\beelink\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

C:\Users\beelink\Downloads\Python  \Brewd>powershell Get-Content folder1\BingRewards\logs\error.log -Tail 6  1>>bing_log.txt

C:\Users\beelink\Downloads\Python  \Brewd>echo ============================folder2===========================  1>>bing_log.txt

**Comment by jjjchens235** [comment]
dup #317
