### ISSUE TITLE
selenium.common.exceptions.TimeoutException: Message:

### ISSUE THREAD

**Issue by Woody-Wan** [jjjchens235/bing-rewards#321]
```
$ python BingRewards.py -nsb
Traceback (most recent call last):
  File "/bing-rewards/BingRewards/BingRewards.py", line 6, in <module>
    from options import parse_search_args
  File "/bing-rewards/BingRewards/options.py", line 3, in <module>
    from src.driver import ChromeDriverFactory, MsEdgeDriverFactory
  File "/bing-rewards/BingRewards/src/driver.py", line 8, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
$ python BingRewards.py -nsb

Command line options selected:
email=None, search_type=remaining, driver=<class 'src.driver.ChromeDriverFactory'>, headless=True, cookies=False, nosandbox=True, telegram=False, discord=False, google_sheets=False, google_trends_geo=US

You selected remaining
Downloading Linux chromedriver version: 108.0.5359.71
The downloaded driver does not match browser version...

Downloading Linux chromedriver version: 107.0.5304.62
       >> Logging in
           << Successfully logged in
Traceback (most recent call last):
  File "/bing-rewards/BingRewards/src/rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "/home/nonroot/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bing-rewards/BingRewards/src/rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "/home/nonroot/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bing-rewards/BingRewards/BingRewards.py", line 179, in <module>
    main()
  File "/bing-rewards/BingRewards/BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "/bing-rewards/BingRewards/BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "/bing-rewards/BingRewards/src/rewards.py", line 1387, in complete_search_type
    init_points = self.__get_available_points()
  File "/bing-rewards/BingRewards/src/rewards.py", line 1285, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
  File "/bing-rewards/BingRewards/src/rewards.py", line 240, in get_dashboard_data
    self.__open_dashboard()
  File "/bing-rewards/BingRewards/src/rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "/bing-rewards/BingRewards/src/rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "/bing-rewards/BingRewards/src/rewards.py", line 226, in __open_dashboard
    raise(e)
  File "/bing-rewards/BingRewards/src/rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "/home/nonroot/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

Using docker destop, Linux chromedriver version: 107.0.5304.62

**Comment by fexofenadine** [comment]
i have the same in windows

**Comment by Lexxior** [comment]
https://github.com/jjjchens235/bing-rewards/issues/318#issuecomment-1332218501

**Comment by jjjchens235** [comment]
This is a dup of #317 which is fixed.

I believe that within the container, the `update.sh` script is run automatically via cronjob by default at [0 0 */1 * *](https://crontab.guru/#0_0_*/1_*_*) (once a day at 00:00).

Please lmk if this is still an issue.
