### ISSUE TITLE
Doesnt work after logging inf

### ISSUE THREAD

**Issue by UltimateWishub** [jjjchens235/bing-rewards#324]
**Before posting issue...**

1. Run using non-headless mode: `python BingRewards -nhl`
2. Copy relevant output from `errors.log`

**Your Issue - include the details from the above steps:**

```
Sat, Dec 03 2022 08:00AM
Traceback (most recent call last):
  File "c:\Users\User\Documents\bing-rewards-1.11\BingRewards\src\rewards.py", line 193, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\Documents\bing-rewards-1.11\BingRewards\src\rewards.py", line 193, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\Documents\bing-rewards-1.11\BingRewards\BingRewards.py", line 130, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "c:\Users\User\Documents\bing-rewards-1.11\BingRewards\BingRewards.py", line 90, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "c:\Users\User\Documents\bing-rewards-1.11\BingRewards\src\rewards.py", line 1369, in complete_search_type
    init_points = self.__get_available_points()
  File "c:\Users\User\Documents\bing-rewards-1.11\BingRewards\src\rewards.py", line 1267, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
  File "c:\Users\User\Documents\bing-rewards-1.11\BingRewards\src\rewards.py", line 223, in get_dashboard_data
    self.__open_dashboard()
  File "c:\Users\User\Documents\bing-rewards-1.11\BingRewards\src\rewards.py", line 210, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "c:\Users\User\Documents\bing-rewards-1.11\BingRewards\src\rewards.py", line 210, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "c:\Users\User\Documents\bing-rewards-1.11\BingRewards\src\rewards.py", line 209, in __open_dashboard
    raise(e)
  File "c:\Users\User\Documents\bing-rewards-1.11\BingRewards\src\rewards.py", line 193, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
``` 

it doesnt work after logging in
it just refreshes a few times and gives up

**Comment by codenotworking** [comment]
I receive the same error as well.

**Comment by J-Sexton** [comment]
@codenotworking 
@UltimateWishub  I think a fix for this was pushed to the master branch but hasn't been added to the docker image

**Comment by UltimateWishub** [comment]
so do i just run update.sh?

**Comment by UltimateWishub** [comment]
nvm i was able to fix it by replacing all the `https://rewards.microsoft.com/` with `https://rewards.bing.com/`

they are on lines 23, 196, 197 in /BingRewards/src/rewards.py

**Comment by codenotworking** [comment]
> nvm i was able to fix it by replacing all the `https://rewards.microsoft.com/` with `https://rewards.bing.com/`
> 
> they are on lines 23, 196, 197 in /BingRewards/src/rewards.py

This worked for me.  I had to modify the v1.15 release to get it to work.
