### ISSUE TITLE
Dashboard elements changes?

### ISSUE THREAD

**Issue by coollbv** [jjjchens235/bing-rewards#328]
It seems they changed something... again. The account logs in, but after logging in it seems to have issue locating elements

Traceback (most recent call last):
  File "C:\msrw\bingrewards\src\rewards.py", line 223, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.presence_of_element_located((By.XPATH, offer_xpath)))
  File "C:\Python3\Lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        (No symbol) [0x005CF243]
        (No symbol) [0x00557FD1]
        (No symbol) [0x0044D04D]
        (No symbol) [0x0047C0B0]
        (No symbol) [0x0047C22B]
        (No symbol) [0x004AE612]
        (No symbol) [0x004985D4]
        (No symbol) [0x004AC9EB]
        (No symbol) [0x00498386]
        (No symbol) [0x0047163C]
        (No symbol) [0x0047269D]
        GetHandleVerifier [0x00869A22+2655074]
        GetHandleVerifier [0x0085CA24+2601828]
        GetHandleVerifier [0x00678C0A+619850]
        GetHandleVerifier [0x00677830+614768]
        (No symbol) [0x005605FC]
        (No symbol) [0x00565968]
        (No symbol) [0x00565A55]
        (No symbol) [0x0057051B]
        BaseThreadInitThunk [0x75527BA9+25]
        RtlInitializeExceptionChain [0x770FBB9B+107]
        RtlClearBits [0x770FBB1F+191]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\msrw\bingrewards\src\rewards.py", line 223, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.presence_of_element_located((By.XPATH, offer_xpath)))
  File "C:\Python3\Lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        (No symbol) [0x005CF243]
        (No symbol) [0x00557FD1]
        (No symbol) [0x0044D04D]
        (No symbol) [0x0047C0B0]
        (No symbol) [0x0047C22B]
        (No symbol) [0x004AE612]
        (No symbol) [0x004985D4]
        (No symbol) [0x004AC9EB]
        (No symbol) [0x00498386]
        (No symbol) [0x0047163C]
        (No symbol) [0x0047269D]
        GetHandleVerifier [0x00869A22+2655074]
        GetHandleVerifier [0x0085CA24+2601828]
        GetHandleVerifier [0x00678C0A+619850]
        GetHandleVerifier [0x00677830+614768]
        (No symbol) [0x005605FC]
        (No symbol) [0x00565968]
        (No symbol) [0x00565A55]
        (No symbol) [0x0057051B]
        BaseThreadInitThunk [0x75527BA9+25]
        RtlInitializeExceptionChain [0x770FBB9B+107]
        RtlClearBits [0x770FBB1F+191]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\msrw\bingrewards\bingrewards.py", line 179, in <module>
    main()
  File "C:\msrw\bingrewards\bingrewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\msrw\bingrewards\bingrewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\msrw\bingrewards\src\rewards.py", line 1387, in complete_search_type
    init_points = self.__get_available_points()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\msrw\bingrewards\src\rewards.py", line 1285, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\msrw\bingrewards\src\rewards.py", line 240, in get_dashboard_data
    self.__open_dashboard()
  File "C:\msrw\bingrewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\msrw\bingrewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\msrw\bingrewards\src\rewards.py", line 226, in __open_dashboard
    raise(e)
  File "C:\msrw\bingrewards\src\rewards.py", line 223, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.presence_of_element_located((By.XPATH, offer_xpath)))
  File "C:\Python3\Lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        (No symbol) [0x005CF243]
        (No symbol) [0x00557FD1]
        (No symbol) [0x0044D04D]
        (No symbol) [0x0047C0B0]
        (No symbol) [0x0047C22B]
        (No symbol) [0x004AE612]
        (No symbol) [0x004985D4]
        (No symbol) [0x004AC9EB]
        (No symbol) [0x00498386]
        (No symbol) [0x0047163C]
        (No symbol) [0x0047269D]
        GetHandleVerifier [0x00869A22+2655074]
        GetHandleVerifier [0x0085CA24+2601828]
        GetHandleVerifier [0x00678C0A+619850]
        GetHandleVerifier [0x00677830+614768]
        (No symbol) [0x005605FC]
        (No symbol) [0x00565968]
        (No symbol) [0x00565A55]
        (No symbol) [0x0057051B]
        BaseThreadInitThunk [0x75527BA9+25]
        RtlInitializeExceptionChain [0x770FBB9B+107]
        RtlClearBits [0x770FBB1F+191]

**Comment by coollbv** [comment]
Never mind, it seems the whole rewards site is messed up. Just the standard weekly cluster&^$%
