### ISSUE TITLE
Why even try downloading multiple WebDrivers?

### ISSUE THREAD

**Issue by DigiOhhh** [jjjchens235/bing-rewards#330]
A certain version of Edge requires the same version of WebDriver in order for Selenium to work. Why even bother with different versions?
Not only that, but in my case Edge was just updated and bing-rewards was not able to find the correct WebDriver version: instead it only checked beta, dev, canary versions! And then gave up.
What's even funnier is how Selenium can tell which version of Edge is installed, as you can see in the following log. Mine is `108.0.1462.42`, and the corresponding WebDriver is available:

![image](https://user-images.githubusercontent.com/37815914/206472462-4536909b-20fc-4a89-88ad-2cc2d9114cec.png)

But for some reason it is completely ignored, and bing-rewards starts with version `109.0.1518.14`

```
PS C:\Users\xxxx\Documents\GitHub\bing-rewards> python .\BingRewards\BingRewards.py -d msedge -c -t -gtg IT

Command line options selected:
email=None, search_type=remaining, driver=<class 'src.driver.MsEdgeDriverFactory'>, headless=True, cookies=True, nosandbox=False, telegram=True, discord=False, google_sheets=False, google_trends_geo=IT

['Thu, Dec 08 2022 02:53PM', 'Failed Edge Search, Web Search, Mobile Search, Offers, Latest Punch Card Activity']

You selected remaining

DevTools listening on ws://127.0.0.1:61395/devtools/browser/94519bef-4dc9-4b00-8761-1aed89c45bcd
The downloaded driver does not match browser version...

Downloading Windows msedgedriver version: 109.0.1518.14

DevTools listening on ws://127.0.0.1:61409/devtools/browser/ba6f2419-f9f6-4f7d-b883-65c26ef443a5
The downloaded driver does not match browser version...

Downloading Windows msedgedriver version: 110.0.1543.0

DevTools listening on ws://127.0.0.1:61422/devtools/browser/5c5c7f2b-37d5-4cfe-a48e-ab9fa1b17c60
The downloaded driver does not match browser version...

Downloading Windows msedgedriver version: 110.0.1546.0
Boo! Telegram notification NOT sent, response code is: <Response [400]> with response msg `{"ok":false,"error_code":400,"description":"Bad Request: message is too long"}`

Traceback (most recent call last):
  File "C:\Users\xxxx\Documents\GitHub\bing-rewards\BingRewards\src\driver.py", line 202, in get_driver
    driver = cls.WebDriverCls(driver_path, options=options)
  File "C:\Users\xxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\edge\webdriver.py", line 61, in _init_
    super()._init_(DesiredCapabilities.EDGE['browserName'], "ms",
  File "C:\Users\xxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in _init_
    super()._init_(
  File "C:\Users\xxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 277, in _init_
    self.start_session(capabilities, browser_profile)
  File "C:\Users\xxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 370, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\xxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "C:\Users\xxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 110
Current browser version is 108.0.1462.42 with binary path C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
Stacktrace:
Backtrace:
        Microsoft::Applications::Events::EventProperties::SetProperty [0x00007FF6B7581992+16802]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6B751EBD2+817698]
        (No symbol) [0x00007FF6B71BF2A0]
        (No symbol) [0x00007FF6B71EFD7D]
        (No symbol) [0x00007FF6B71EA968]
        (No symbol) [0x00007FF6B71E5F5A]
        (No symbol) [0x00007FF6B7229DD5]
        (No symbol) [0x00007FF6B7221D73]
        (No symbol) [0x00007FF6B71F3738]
        (No symbol) [0x00007FF6B71F27EC]
        (No symbol) [0x00007FF6B71F3EF4]
        Microsoft::Applications::Events::EventProperties::SetProperty [0x00007FF6B7403A78+176792]
        (No symbol) [0x00007FF6B72C062F]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6B746051A+37738]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6B74635E5+50229]
        Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF6B7791013+1527939]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6B752749A+852714]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6B752C484+873172]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6B752C5DC+873516]
        Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6B75352AE+909566]
        BaseThreadInitThunk [0x00007FFB8F1E74B4+20]
        RtlUserThreadStart [0x00007FFB8F4C26A1+33]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxx\Documents\GitHub\bing-rewards\BingRewards\BingRewards.py", line 179, in <module>
    main()
  File "C:\Users\xxxx\Documents\GitHub\bing-rewards\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\xxxx\Documents\GitHub\bing-rewards\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\xxxx\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 1387, in complete_search_type
    self.__get_driver(device_type)
  File "C:\Users\xxxx\Documents\GitHub\bing-rewards\BingRewards\src\rewards.py", line 1274, in __get_driver
    self.driver = self.driver_factory.get_driver(
  File "C:\Users\xxxx\Documents\GitHub\bing-rewards\BingRewards\src\driver.py", line 216, in get_driver
    cls.__download_driver(dl_try_count)
  File "C:\Users\xxxx\Documents\GitHub\bing-rewards\BingRewards\src\driver.py", line 108, in __download_driver
    response = urlopen(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by Summon528** [comment]
It skipped stable version because as recent as [3 days ago](http://web.archive.org/web/20221205230744/https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/), the stable version will be displayed in the upper banner. 
![image](https://user-images.githubusercontent.com/10328757/206569078-f985d212-4ce2-405a-927f-b42639d04b88.png)
Seems like MS removed it; therefore bing-reward can't find the correct driver. (I'll admit the initial code isn't really robust)

**Comment by jjjchens235** [comment]
There's a nice library that abstracts this problem, but only for [chromedriver](https://github.com/yeongbin-jo/python-chromedriver-autoinstaller).

**Comment by heximing** [comment]
I manually downloaded the 108.0.1462.42 driver and put is in the "drivers" folder; problem fixed.

**Comment by jjjchens235** [comment]
Fix for MS Edge issue is in dev br: 55b73dd

Will get a release out later this week.
