### ISSUE TITLE
Problem with running docker container. 

### ISSUE THREAD

**Issue by BIPTOA** [jjjchens235/bing-rewards#339]
**Before posting issue...**

1. Run using non-headless mode: `python BingRewards -nhl`
2. Copy relevant output from `errors.log`

**Your Issue - include the details
I tired changing url and rebuilding docker container I style get these errors. Also after trying to run docker exec bing-rewards python BingRewards.py -nsb (and getting error like below) container starts using quite a lot of ram (300mb) 
Tue, Jan 03 2023 03:16PM
Traceback (most recent call last):
  File "/bing-rewards/BingRewards/src/rewards.py", line 224, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.presence_of_element_located((By.XPATH, offer_xpath)))
  File "/home/nonroot/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x55c5dd88f2a3 <unknown>
#1 0x55c5dd64df77 <unknown>
#2 0x55c5dd68a80c <unknown>
#3 0x55c5dd68aa71 <unknown>
#4 0x55c5dd6c4734 <unknown>
#5 0x55c5dd6aab5d <unknown>
#6 0x55c5dd6c247c <unknown>
#7 0x55c5dd6aa903 <unknown>
#8 0x55c5dd67dece <unknown>
#9 0x55c5dd67efde <unknown>
#10 0x55c5dd8df63e <unknown>
#11 0x55c5dd8e2b79 <unknown>
#12 0x55c5dd8c589e <unknown>
#13 0x55c5dd8e3a83 <unknown>
#14 0x55c5dd8b8505 <unknown>
#15 0x55c5dd904ca8 <unknown>
#16 0x55c5dd904e36 <unknown>
#17 0x55c5dd920333 <unknown>
#18 0x7fa54d88bea7 start_thread

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bing-rewards/BingRewards/src/rewards.py", line 224, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.presence_of_element_located((By.XPATH, offer_xpath)))
  File "/home/nonroot/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x55c5dd88f2a3 <unknown>
#1 0x55c5dd64df77 <unknown>
#2 0x55c5dd68a80c <unknown>
#3 0x55c5dd68aa71 <unknown>
#4 0x55c5dd6c4734 <unknown>
#5 0x55c5dd6aab5d <unknown>
#6 0x55c5dd6c247c <unknown>
#7 0x55c5dd6aa903 <unknown>
#8 0x55c5dd67dece <unknown>
#9 0x55c5dd67efde <unknown>
#10 0x55c5dd8df63e <unknown>
#11 0x55c5dd8e2b79 <unknown>
#12 0x55c5dd8c589e <unknown>
#13 0x55c5dd8e3a83 <unknown>
#14 0x55c5dd8b8505 <unknown>
#15 0x55c5dd904ca8 <unknown>
#16 0x55c5dd904e36 <unknown>
#17 0x55c5dd920333 <unknown>
#18 0x7fa54d88bea7 start_thread

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bing-rewards/BingRewards/BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "/bing-rewards/BingRewards/BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "/bing-rewards/BingRewards/src/rewards.py", line 1388, in complete_search_type
    init_points = self.__get_available_points()
  File "/bing-rewards/BingRewards/src/rewards.py", line 1286, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
  File "/bing-rewards/BingRewards/src/rewards.py", line 241, in get_dashboard_data
    self.__open_dashboard()
  File "/bing-rewards/BingRewards/src/rewards.py", line 228, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "/bing-rewards/BingRewards/src/rewards.py", line 228, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "/bing-rewards/BingRewards/src/rewards.py", line 227, in __open_dashboard
    raise(e)
  File "/bing-rewards/BingRewards/src/rewards.py", line 224, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.presence_of_element_located((By.XPATH, offer_xpath)))
  File "/home/nonroot/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x55c5dd88f2a3 <unknown>
#1 0x55c5dd64df77 <unknown>
#2 0x55c5dd68a80c <unknown>
#3 0x55c5dd68aa71 <unknown>
#4 0x55c5dd6c4734 <unknown>
#5 0x55c5dd6aab5d <unknown>
#6 0x55c5dd6c247c <unknown>
#7 0x55c5dd6aa903 <unknown>
#8 0x55c5dd67dece <unknown>
#9 0x55c5dd67efde <unknown>
#10 0x55c5dd8df63e <unknown>
#11 0x55c5dd8e2b79 <unknown>
#12 0x55c5dd8c589e <unknown>
#13 0x55c5dd8e3a83 <unknown>
#14 0x55c5dd8b8505 <unknown>
#15 0x55c5dd904ca8 <unknown>
#16 0x55c5dd904e36 <unknown>
#17 0x55c5dd920333 <unknown>
#18 0x7fa54d88bea7 start_thread

from the above steps:**

**Comment by Killerherts** [comment]
If you are running in docker, you also need -nsb 
-nhl is basically irrelevant since the display it thinks it is using is virtualized

**Comment by BIPTOA** [comment]
>  Yes it auto starts using like that, and you can force it to run "right now" with docker exec bing-rewards python BingRewards.py -nsb and it causes the same thing.
