### ISSUE TITLE
What am I doing wrong? Not working

### ISSUE THREAD

**Issue by PubgStarz** [jjjchens235/bing-rewards#34]
Hi, i follow all the read me file and still got errors and it doesn't work... Any ideas? Thanks

```
C:\Users\M\Desktop\bing-rewards-master\BingRewards> BingRewards.py
Enter   w for web,
        m for mobile,
        b for both,
        o for offers,
        a for all,
        r for remaining (default)
Input:  a
['Sat, Aug 29 2020 05:06PM', 'Failed Edge Search, Web Search, Mobile Search, Offers']

        You selected all

> Starting Edge search

DevTools listening on ws://127.0.0.1:51691/devtools/browser/e244f9e6-af60-41c2-a2dd-01e7fa0ce802
downloading chrome driver version: 83.0.4103.39

DevTools listening on ws://127.0.0.1:51709/devtools/browser/67c97ec1-f7cd-44c4-ad0b-d95363abccad
downloading chrome driver version: 84.0.4147.30

DevTools listening on ws://127.0.0.1:51728/devtools/browser/b95d0639-e9cb-442a-bb44-e679133bc8ca
downloading chrome driver version: 85.0.4183.87

DevTools listening on ws://127.0.0.1:51743/devtools/browser/5967569c-8ce9-4a57-808c-a4086099bcd9
downloading chrome driver version: 73.0.3683.68
Tried downloading the 0 most recent chrome drivers. None match current Chrome browser version
Traceback (most recent call last):
  File "C:\Users\M\Desktop\bing-rewards-master\BingRewards\BingRewards.py", line 136, in <module>
    __main(args[0], arg1)
  File "C:\Users\M\Desktop\bing-rewards-master\BingRewards\BingRewards.py", line 86, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "C:\Users\M\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 857, in complete_all
    driver = self.__complete_edge_search()
  File "C:\Users\M\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 702, in __complete_edge_search
    driver = Driver.get_driver(self.path, Driver.WEB_DEVICE, self.headless)
  File "C:\Users\M\Desktop\bing-rewards-master\BingRewards\src\driver.py", line 108, in get_driver
    return EventFiringWebDriver(driver, EventListener())
UnboundLocalError: local variable 'driver' referenced before assignment

C:\Users\M\Desktop\bing-rewards-master\BingRewards>
```

**Comment by jjjchens235** [comment]
Multiple accounts is not supported currently, and there is no plans to add this feature. This is the most common question/request, but the reason for this is because it goes against the original author's intention and I want to honor that.

Caveat: I think a docker container implementation would be a good middle ground solution. Unfortunately, I'm not too familiar with Docker so someone would have to implement it and I would gladly merge with master.

**Comment by codenotworking** [comment]
I ended up modifying some of the code to implement multiple accounts.  Basically I wrapped the `try/except` statement in `BingRewards.py` in a `while` loop.  For the `config.py` file, I added the additional hashed accounts, with a number attached to **email** and **password** `dictionary` keys (example: email1, password1, email2, password 2, etc.).  This allowed me to control the `while` loop.  There are other minor modifications I had to do, but if you have some programming skills and know some Python, you can modify it to suit your needs.

**Comment by Emerald-op** [comment]
@codenotworking is there any way you can help me do this.

**Comment by udithap** [comment]
> I ended up modifying some of the code to implement multiple accounts. Basically I wrapped the `try/except` statement in `BingRewards.py` in a `while` loop. For the `config.py` file, I added the additional hashed accounts, with a number attached to **email** and **password** `dictionary` keys (example: email1, password1, email2, password 2, etc.). This allowed me to control the `while` loop. There are other minor modifications I had to do, but if you have some programming skills and know some Python, you can modify it to suit your needs.

You can do this easily without any programming by having multiple instances of Bing rewards in seperate folder per account. Each config.py will hold the account details as usual and a simple windows batch file can be created to run each BingRewards.py

**Comment by Emerald-op** [comment]
Alright thank you so much can you help me make the batch file if possible.

**Comment by udithap** [comment]
Create a main folder on your computer some where accessible.
Create subfolders in this folder for each account you have, eg: account1, account2, etc
In each account folder put the contents of bing-rewards-master. Then each folder will contain a BingRewards folder and 4 more files including setup.py
Run setup.py in each folder and enter the correct account details for that account.
create a batch file in the main folder with some name like run_bing.bat
Put the following contents in the batch file. (The text starting from & REM are just comments for you. You can ignore them in your batch file. You can add more accounts in the same way)

`cd path\to\your\main\folder\ & REM First change to the batch file folder

echo Points as at = %time% %date%> bing_log.txt & REM create a simple logfile with time and end result of the batch run
echo ============================account1=========================== >> bing_log.txt

C:\python\python.exe account1\BingRewards\BingRewards.py -r & REM run the first account Bing rewards and repeat for each account as below
powershell Get-Content account1\BingRewards\logs\error.log -Tail 6 >> bing_log.txt

echo ============================account2=========================== >> bing_log.txt
C:\python\python.exe account2\BingRewards\BingRewards.py -r
powershell Get-Content account2\BingRewards\logs\error.log -Tail 6 >> bing_log.txt

echo ============================account3=========================== >> bing_log.txt
C:\python\python.exe account3\BingRewards\BingRewards.py -r
powershell Get-Content account3\BingRewards\logs\error.log -Tail 6 >> bing_log.txt

echo ============================account4=========================== >> bing_log.txt
C:\python\python.exe account4\BingRewards\BingRewards.py -r
powershell Get-Content account4\BingRewards\logs\error.log -Tail 6 >> bing_log.txt`

**Comment by Emerald-op** [comment]
Is there anything else I need to change?
cd C:\Users\Emerald\Documents\Rewardsz & REM First change to the batch file folder

echo Points as at = %time% %date%> bing_log.txt & REM create a simple logfile with time and end result of the batch run
echo ============================account1=========================== >> bing_log.txt

"C:\Users\Emerald\Documents\Rewardsz\bing-rewards-master\BingRewards\BingRewards.py" -r & REM You may have to modify the c:\python to the location of your python installation. If it is in program files, make sure to include the whole path in quotes.
powershell Get-Content account1\BingRewards\logs\error.log -Tail 6 >> bing_log.txt

echo ============================account2=========================== >> bing_log.txt
"C:\Users\Emerald\Documents\Rewardsz\bing-rewards-master 2\BingRewards\BingRewards.py" -r
powershell Get-Content account2\BingRewards\logs\error.log -Tail 6 >> bing_log.txt

echo ============================account3=========================== >> bing_log.txt
"C:\Users\Emerald\Documents\Rewardsz\bing-rewards-master 3\BingRewards\BingRewards.py" -r
powershell Get-Content account3\BingRewards\logs\error.log -Tail 6 >> bing_log.txt

echo ============================account4=========================== >> bing_log.txt
"C:\Users\Emerald\Documents\Rewardsz\bing-rewards-master 4\BingRewards\BingRewards.py" -r
powershell Get-Content account4\BingRewards\logs\error.log -Tail 6 >> bing_log.txt

**Comment by udithap** [comment]
I do not see the path to the python.exe in your file.

**Comment by J12345654321** [comment]
> I do not see the path to the python.exe in your file.

Stupid question, when a batch file is written...how do you get the system "to go"?  I'm really dumb at this!

**Comment by chris987789** [comment]
time to close this as it's not going to be implemented within the program but a simple google search can show you how to do it??

**Comment by Kalphyris** [comment]
I just copy/pasted the folder directory and changed line 81 to "if not"

**Comment by chris987789** [comment]
Yes that is the quick way to do it, don't want to change it to multiple accounts though because higher chance to get blocked .

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Fluff663** [comment]
if you _really_ want to you can redo the setup in a different folder

**Comment by heximing** [comment]
For me, I create different shortcuts of CMD.exe like these:
`C:\Windows\System32\cmd.exe /k {path to python.exe} {path to BingRewards.py} -r -e {your email} -p {your password}`

The downside is that the email and password are not encoded.

You will need to run each shortcut individually and manually one after one. If you want full automatic, you can put them to startup AND you need to set some delay for each shortcut. Usually, each account takes > 20 minutes to run.

**Comment by riahc3** [comment]
> Create a main folder on your computer some where accessible. Create subfolders in this folder for each account you have, eg: account1, account2, etc In each account folder put the contents of bing-rewards-master. Then each folder will contain a BingRewards folder and 4 more files including setup.py Run setup.py in each folder and enter the correct account details for that account. create a batch file in the main folder with some name like run_bing.bat Put the following contents in the batch file. (The text starting from & REM are just comments for you. You can ignore them in your batch file. You can add more accounts in the same way)
> 
> cd path\to\your\main\folder\ & REM First change to the batch file folder
> 
> echo Points as at = %time% %date%> bing_log.txt & REM create a simple logfile with time and end result of the batch run echo ============================account1=========================== >> bing_log.txt
> 
> C:\python\python.exe account1\BingRewards\BingRewards.py -r & REM You may have to modify the c:\python to the location of your python installation. If it is in program files, make sure to include the whole path in quotes. powershell Get-Content account1\BingRewards\logs\error.log -Tail 6 >> bing_log.txt
> 
> echo ============================account2=========================== >> bing_log.txt C:\python\python.exe account2\BingRewards\BingRewards.py -r powershell Get-Content account2\BingRewards\logs\error.log -Tail 6 >> bing_log.txt
> 
> echo ============================account3=========================== >> bing_log.txt C:\python\python.exe account3\BingRewards\BingRewards.py -r powershell Get-Content account3\BingRewards\logs\error.log -Tail 6 >> bing_log.txt
> 
> echo ============================account4=========================== >> bing_log.txt C:\python\python.exe account4\BingRewards\BingRewards.py -r powershell Get-Content account4\BingRewards\logs\error.log -Tail 6 >> bing_log.txt

Why are you using REM and calling PoSH at the same time? 😂

**Comment by riahc3** [comment]
> For me, I create different shortcuts of CMD.exe like these: `C:\Windows\System32\cmd.exe /k {path to python.exe} {path to BingRewards.py} -r -e {your email} -p {your password}`
> 
> The downside is that the email and password are not encoded.
> 
> You will need to run each shortcut individually and manually one after one. If you want full automatic, you can put them to startup AND you need to set some delay for each shortcut. Usually, each account takes > 20 minutes to run.

This seems like the most logical solution. You update it once and with a script file run each line. Each line, if it takes 20 minutes, will run afterwards.
