### ISSUE TITLE
Error when reaching rewards page

### ISSUE THREAD

**Issue by calebidklol** [jjjchens235/bing-rewards#344]
**Before posting issue...**

1. Run using non-headless mode: `python BingRewards -nhl`
2. Copy relevant output from `errors.log`

**Your Issue - include the details from the above steps:**

1. Opened using non headless mode, images not loading, page refreshes 2-3 times, then crashes.

Sat, Jan 07 2023 05:54PM
Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1387, in complete_search_type
    init_points = self.__get_available_points()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1285, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 240, in get_dashboard_data
    self.__open_dashboard()
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 226, in __open_dashboard
    raise(e)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

Sat, Jan 07 2023 05:58PM
Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1387, in complete_search_type
    init_points = self.__get_available_points()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1285, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 240, in get_dashboard_data
    self.__open_dashboard()
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 226, in __open_dashboard
    raise(e)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

Sat, Jan 07 2023 05:59PM
Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1387, in complete_search_type
    init_points = self.__get_available_points()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1285, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 240, in get_dashboard_data
    self.__open_dashboard()
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 226, in __open_dashboard
    raise(e)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

Starting new HTTPS connection (1): discord.com:443
https://discord.com:443 "POST /api/webhooks/1061417741678039060/gaBuKTKP55QmAb6dZkTRa5noHOpdHkipOwBGt__Rbf8RgvX4lNeAYe6UFLoWG9xo0fkg HTTP/1.1" 400 49
Sat, Jan 07 2023 06:02PM
Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1387, in complete_search_type
    init_points = self.__get_available_points()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1285, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 240, in get_dashboard_data
    self.__open_dashboard()
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 226, in __open_dashboard
    raise(e)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

Starting new HTTPS connection (1): discord.com:443
https://discord.com:443 "POST /api/webhooks/1061417741678039060/gaBuKTKP55QmAb6dZkTRa5noHOpdHkipOwBGt__Rbf8RgvX4lNeAYe6UFLoWG9xo0fkg HTTP/1.1" 400 49
Sat, Jan 07 2023 06:03PM
Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1387, in complete_search_type
    init_points = self.__get_available_points()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1285, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 240, in get_dashboard_data
    self.__open_dashboard()
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 226, in __open_dashboard
    raise(e)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

Starting new HTTPS connection (1): discord.com:443
https://discord.com:443 "POST /api/webhooks/1061417741678039060/gaBuKTKP55QmAb6dZkTRa5noHOpdHkipOwBGt__Rbf8RgvX4lNeAYe6UFLoWG9xo0fkg HTTP/1.1" 400 49
Sat, Jan 07 2023 06:06PM
Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1387, in complete_search_type
    init_points = self.__get_available_points()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1285, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 240, in get_dashboard_data
    self.__open_dashboard()
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 226, in __open_dashboard
    raise(e)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

Sat, Jan 07 2023 06:07PM
Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1387, in complete_search_type
    init_points = self.__get_available_points()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 1285, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 240, in get_dashboard_data
    self.__open_dashboard()
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 226, in __open_dashboard
    raise(e)
  File "C:\Users\ctb12\Downloads\bing-rewards-1.15\BingRewards\src\rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "C:\Users\ctb12\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by royaltongue** [comment]
Also running into the same issue with the latest pull from Github, In NHL mode, Chrome is pulled up, logs in successfully, navigates to the rewards dashboard, then refreshes a few times without ever loading images on the rewards page. After a few refreshes, the bot crashes and this is shown in the terminal

```
localuser@localuser-desktop:~/Documents/bingrewardsjj/billsep/BingRewards$ python3.9 BingRewards.py -nhl

Command line options selected:
email=None, search_type=remaining, driver=<class 'src.driver.ChromeDriverFactory'>, headless=False, cookies=False, nosandbox=False, telegram=False, discord=False, google_sheets=False, google_trends_geo=US

['Sat, Jan 07 2023 06:31PM', 'Failed Edge Search, Web Search, Mobile Search, Offers, Latest Punch Card Activity']

You selected remaining
       >> Logging in
           << Successfully logged in
Traceback (most recent call last):
  File "/home/localuser/Documents/bingrewardsjj/billsep/BingRewards/src/rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "/home/localuser/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/localuser/Documents/bingrewardsjj/billsep/BingRewards/src/rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "/home/localuser/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/localuser/Documents/bingrewardsjj/billsep/BingRewards/BingRewards.py", line 179, in <module>
    main()
  File "/home/localuser/Documents/bingrewardsjj/billsep/BingRewards/BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "/home/localuser/Documents/bingrewardsjj/billsep/BingRewards/BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "/home/localuser/Documents/bingrewardsjj/billsep/BingRewards/src/rewards.py", line 1387, in complete_search_type
    init_points = self.__get_available_points()
  File "/home/localuser/Documents/bingrewardsjj/billsep/BingRewards/src/rewards.py", line 1285, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
  File "/home/localuser/Documents/bingrewardsjj/billsep/BingRewards/src/rewards.py", line 240, in get_dashboard_data
    self.__open_dashboard()
  File "/home/localuser/Documents/bingrewardsjj/billsep/BingRewards/src/rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "/home/localuser/Documents/bingrewardsjj/billsep/BingRewards/src/rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "/home/localuser/Documents/bingrewardsjj/billsep/BingRewards/src/rewards.py", line 226, in __open_dashboard
    raise(e)
  File "/home/localuser/Documents/bingrewardsjj/billsep/BingRewards/src/rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "/home/localuser/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```
