### ISSUE TITLE
Error with Chromedriver?

### ISSUE THREAD

**Issue by Affoghiamoci** [jjjchens235/bing-rewards#350]
Hi! I have this error:

`You selected remaining
Downloading Darwin chromedriver version: 110.0.5481.30
Traceback (most recent call last):
  File "/Users/affoghiamoci/Documents/Rewards/Angela/BingRewards/BingRewards.py", line 154, in <module>
    main()
  File "/Users/affoghiamoci/Documents/Rewards/Angela/BingRewards/BingRewards.py", line 116, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "/Users/affoghiamoci/Documents/Rewards/Angela/BingRewards/BingRewards.py", line 77, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "/Users/affoghiamoci/Documents/Rewards/Angela/BingRewards/src/rewards.py", line 1371, in complete_search_type
    self.__get_driver(device_type)
  File "/Users/affoghiamoci/Documents/Rewards/Angela/BingRewards/src/rewards.py", line 1258, in __get_driver
    self.driver = self.driver_factory.get_driver(
  File "/Users/affoghiamoci/Documents/Rewards/Angela/BingRewards/src/driver.py", line 171, in get_driver
    cls.__download_driver()
  File "/Users/affoghiamoci/Documents/Rewards/Angela/BingRewards/src/driver.py", line 89, in __download_driver
    response = urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found`

how can i resolve this?

**Comment by MA-TTP** [comment]
So I seem to have had that too:

```Traceback (most recent call last):
  File "/Users/mashooraiyaan/Documents/bing-rewards-1.15/BingRewards/src/rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "/opt/homebrew/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mashooraiyaan/Documents/bing-rewards-1.15/BingRewards/src/rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "/opt/homebrew/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mashooraiyaan/Documents/bing-rewards-1.15/BingRewards/BingRewards.py", line 179, in <module>
    main()
  File "/Users/mashooraiyaan/Documents/bing-rewards-1.15/BingRewards/BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "/Users/mashooraiyaan/Documents/bing-rewards-1.15/BingRewards/BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "/Users/mashooraiyaan/Documents/bing-rewards-1.15/BingRewards/src/rewards.py", line 1387, in complete_search_type
    init_points = self.__get_available_points()
  File "/Users/mashooraiyaan/Documents/bing-rewards-1.15/BingRewards/src/rewards.py", line 1285, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
  File "/Users/mashooraiyaan/Documents/bing-rewards-1.15/BingRewards/src/rewards.py", line 240, in get_dashboard_data
    self.__open_dashboard()
  File "/Users/mashooraiyaan/Documents/bing-rewards-1.15/BingRewards/src/rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "/Users/mashooraiyaan/Documents/bing-rewards-1.15/BingRewards/src/rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "/Users/mashooraiyaan/Documents/bing-rewards-1.15/BingRewards/src/rewards.py", line 226, in __open_dashboard
    raise(e)
  File "/Users/mashooraiyaan/Documents/bing-rewards-1.15/BingRewards/src/rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "/opt/homebrew/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: ```

**Comment by sensboston** [comment]
In the https://github.com/jjjchens235/bing-rewards/blob/master/BingRewards/src/rewards.py, try to add **time.sleep(1)** line at line 207 (to get:
```
        self.driver.get(self.__DASHBOARD_URL)
        time.sleep(1)
        try:
```
P.S. I'm using old version, not the current, but this helped me.
