### ISSUE TITLE
Timeout on login

### ISSUE THREAD

**Issue by webdeck** [jjjchens235/bing-rewards#51]
Python updated from 3.8 to 3.9.  I reinstalled the requirements, but now it times out when I try to run:

```
python3 BingRewards/BingRewards.py 
Enter 	w for web, 
	m for mobile, 
	b for both, 
	o for offers, 
	a for all, 
	r for remaining (default) 
Input: 	a
['Fri, Oct 30 2020 07:45AM', 'Failed Edge Search, Web Search, Mobile Search, Offers']

	You selected all

> Starting Edge search
       >> Logging in
Traceback (most recent call last):
  File "/Users/xxx/src/bing-rewards/BingRewards/src/rewards.py", line 99, in __login
    WebDriverWait(driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.url_contains("https://account.microsoft.com/"))
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxx/src/bing-rewards/BingRewards/BingRewards.py", line 136, in <module>
    __main(args[0], arg1)
  File "/Users/xxx/src/bing-rewards/BingRewards/BingRewards.py", line 82, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "/Users/xxx/src/bing-rewards/BingRewards/src/rewards.py", line 889, in complete_all
    driver = self.__complete_edge_search()
  File "/Users/xxx/src/bing-rewards/BingRewards/src/rewards.py", line 734, in __complete_edge_search
    self.__login(driver)
  File "/Users/xxx/src/bing-rewards/BingRewards/src/rewards.py", line 105, in __login
    raise RuntimeError("Did NOT log in successfully")
RuntimeError: Did NOT log in successfully
Exit 1
```

**Comment by webdeck** [comment]
Never mind - a reboot fixed this.
