### ISSUE TITLE
No module named request

### ISSUE THREAD

**Issue by Nilafhiosagam** [jjjchens235/bing-rewards#66]
Hi, excuse my lack of python

Traceback (most recent call last):
  File "BingRewards.py", line 3, in <module>
    from src.rewards import Rewards
  File "/home/pi/Documents/python_scripts/bing-rewards/BingRewards/src/rewards.py", line 1, in <module>
    from src.driver import Driver
  File "/home/pi/Documents/python_scripts/bing-rewards/BingRewards/src/driver.py", line 3, in <module>
    from urllib.request import urlopen
ImportError: No module named request

I ran requirements.txt at the start and when I run "pip install requests" I get

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.21.0)

**Comment by Nilafhiosagam** [comment]
created a new virtual environment as I guess I should have done originally
