### ISSUE TITLE
Selenium error

### ISSUE THREAD

**Issue by Nilafhiosagam** [jjjchens235/bing-rewards#67]
Hi 

Recieving the following error and unsure of the issue

>> Logging in
           << Successfully logged in
       >> Starting search
Traceback (most recent call last):
  File "C:\Users\mynamehere\Documents\bing-rewards-master\BingRewards\BingRewards.py", line 136, in <module>
    __main(args[0], arg1)
  File "C:\Users\mynamehere\Documents\bing-rewards-master\BingRewards\BingRewards.py", line 92, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "C:\Users\mynamehere\Documents\bing-rewards-master\BingRewards\src\rewards.py", line 907, in complete_all
    driver = self.__complete_edge_search()
  File "C:\Users\mynamehere\Documents\bing-rewards-master\BingRewards\src\rewards.py", line 753, in __complete_edge_search
    self.completion.edge_search = self.__search(driver, Driver.WEB_DEVICE, is_edge=True)
  File "C:\Users\mynamehere\Documents\bing-rewards-master\BingRewards\src\rewards.py", line 185, in __search
    progress = self.__get_search_progress(driver, device, is_edge)
  File "C:\Users\mynamehere\Documents\bing-rewards-master\BingRewards\src\rewards.py", line 136, in __get_search_progress
    progress_name = element.find_element_by_xpath('./div/div[2]/mee-rewards-user-points-details/div/div/div/div/p[1]').text.upper()
  File "C:\Users\mynamehere\Documents\bing-rewards-master\my_python\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 271, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\mynamehere\Documents\bing-rewards-master\my_python\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 235, in find_element
    return self._dispatch("find", (by, value, self._driver), "find_element", (by, value))
  File "C:\Users\mynamehere\Documents\bing-rewards-master\my_python\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 294, in _dispatch
    raise e
  File "C:\Users\mynamehere\Documents\bing-rewards-master\my_python\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 291, in _dispatch
    result = getattr(self._webelement, d_call)(*d_args)
  File "C:\Users\mynamehere\Documents\bing-rewards-master\my_python\lib\site-packages\selenium\webdriver\remote\webelement.py", line 658, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT,
  File "C:\Users\mynamehere\Documents\bing-rewards-master\my_python\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\mynamehere\Documents\bing-rewards-master\my_python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\mynamehere\Documents\bing-rewards-master\my_python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"./div/div[2]/mee-rewards-user-points-details/div/div/div/div/p[1]"}
  (Session info: headless chrome=89.0.4389.90)

**Comment by jjjchens235** [comment]
Hi - sorry for delayed response, are you located in the USA?

**Comment by Nilafhiosagam** [comment]
Thanks. No I'm in Ireland. Which means the element is missing from my homepage I presume
