### ISSUE TITLE
"Allow Bing to access your location" error for mobile search

### ISSUE THREAD

**Issue by codenotworking** [jjjchens235/bing-rewards#77]
Just received the following error:

```
> Starting mobile search

DevTools listening on ws://127.0.0.1:56371/devtools/browser/f3e2c706-aa4b-4aea-9d90-41e2314bdc0a
       >> Logging in
           << Successfully logged in
       >> Starting search
              >>> Progress: [                              ] 0/100 (0%)Traceback (most recent call last):

selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: Want more relevant search results? Allow Bing to access your location. Click 'Allow' on the next prompt.
Message: unexpected alert open: {Alert text : Want more relevant search results? Allow Bing to access your location. Click 'Allow' on the next prompt.}
  (Session info: headless chrome=91.0.4472.77)
```

**Comment by LordFarhad** [comment]
I'm having the same issue.

**Comment by codenotworking** [comment]
This error happened to me again today.  I'll provide the full traceback.

```
> Starting mobile search

DevTools listening on ws://127.0.0.1:54777/devtools/browser/86aa8525-1e9c-43d8-b29c-7746d77f604d
       >> Logging in
           << Successfully logged in
       >> Starting search
              >>> Progress: [                              ] 0/100 (0%)Traceback (most recent call last):
  File "C:\Dropbox\Apps\BingRewards\BingRewards.py", line 372, in <module>
    __main(args[0], arg1.replace("-", ""))
  File "C:\Dropbox\Apps\BingRewards\BingRewards.py", line 177, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "C:\Dropbox\Apps\BingRewards\src\rewards.py", line 951, in complete_all
    driver = self.__complete_mobile_search()
  File "C:\Dropbox\Apps\BingRewards\src\rewards.py", line 837, in __complete_mobile_search
    self.completion.mobile_search = self.__search(driver, Driver.MOBILE_DEVICE)
  File "C:\Dropbox\Apps\BingRewards\src\rewards.py", line 235, in __search
    WebDriverWait(driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.element_to_be_clickable((By.ID, "bnp_btn_accept"))).click()
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 297, in __call__
    element = visibility_of_element_located(self.locator)(driver)
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 101, in find_element
    return self._dispatch("find", (by, value, self._driver), "find_element", (by, value))
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 160, in _dispatch
    raise e
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 157, in _dispatch
    result = getattr(self._driver, d_call)(*d_args)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: Want more relevant search results? Allow Bing to access your location. Click 'Allow' on the next prompt.
Message: unexpected alert open: {Alert text : Want more relevant search results? Allow Bing to access your location. Click 'Allow' on the next prompt.}
  (Session info: headless chrome=91.0.4472.77)
```

**Comment by LordFarhad** [comment]
basically script needs to suppress / ignore or accept the following prompt:

Alert Text: Want more relevant search results? Allow Bing to access your location. Click 'Allow' on the next prompt.
Message: unexpected alert open: {Alert text : Want more relevant search results? Allow Bing to access your location. Click 'Allow' on the next prompt.}
  (Session info: headless chrome=91.0.4472.77

**Comment by jjjchens235** [comment]
I tried mobile search today and wasn't able to reproduce this error.

I updated this [line](https://github.com/jjjchens235/bing-rewards/blob/218b4b18b3edbc847b478c276d31bb6365c39fd8/BingRewards/src/driver.py#L92)

to....

        options.add_experimental_option("prefs", {"profile.default_content_setting_values.geolocation" : 1, "profile.default_content_setting_values.notifications" : 2}) # geolocation permission, 0=Ask, 1=Allow, 2=Deny


Let me know if this updated line fixes/doesn't fix the issue

**Comment by codenotworking** [comment]
> ```
>     options.add_experimental_option("prefs", {"profile.default_content_setting_values.geolocation" : 1, "profile.default_content_setting_values.notifications" : 2}) # geolocation permission, 0=Ask, 1=Allow, 2=Deny
> ```
I applied this modification to **driver.py**.  Today I received the same error message as in my initial post.

Here's the full traceback:

```
> Starting mobile search

DevTools listening on ws://127.0.0.1:52422/devtools/browser/6906438c-a85c-4cd9-8214-b6fb8f98f631
       >> Logging in
           << Successfully logged in
       >> Starting search
              >>> Progress: [                              ] 0/100 (0%)Traceback (most recent call last):
  File "C:\Dropbox\Apps\BingRewards\BingRewards.py", line 377, in <module>
    __main(args[0], arg1.replace("-", ""))
  File "C:\Dropbox\Apps\BingRewards\BingRewards.py", line 179, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "C:\Dropbox\Apps\BingRewards\src\rewards.py", line 951, in complete_all
    driver = self.__complete_mobile_search()
  File "C:\Dropbox\Apps\BingRewards\src\rewards.py", line 837, in __complete_mobile_search
    self.completion.mobile_search = self.__search(driver, Driver.MOBILE_DEVICE)
  File "C:\Dropbox\Apps\BingRewards\src\rewards.py", line 235, in __search
    WebDriverWait(driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.element_to_be_clickable((By.ID, "bnp_btn_accept"))).click()
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 297, in __call__
    element = visibility_of_element_located(self.locator)(driver)
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 101, in find_element
    return self._dispatch("find", (by, value, self._driver), "find_element", (by, value))
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 160, in _dispatch
    raise e
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 157, in _dispatch
    result = getattr(self._driver, d_call)(*d_args)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: Want more relevant search results? Allow Bing to access your location. Click 'Allow' on the next prompt.
Message: unexpected alert open: {Alert text : Want more relevant search results? Allow Bing to access your location. Click 'Allow' on the next prompt.}
  (Session info: headless chrome=91.0.4472.114)
```

**Comment by jjjchens235** [comment]
Are you still getting this issue?

Per this [stackoverflow](https://stackoverflow.com/questions/28397370/python-selenium-unexpectedalertpresentexception), I wonder if something like this would work:
```
try:
    #self.__sys_out("cookie popup cleared", 3)
    WebDriverWait(driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.element_to_be_clickable((By.ID, "bnp_btn_accept"))).click()
except TimeoutException:
    #self.__sys_out("No cookie popup present", 3)
    pass
except selenium.common.exceptions.UnexpectedAlertPresentException:
    alert = driver.switch_to.alert()
    alert.accept()
```

**Comment by codenotworking** [comment]
I have not received the error in a while.  Maybe Microsoft made a change.  But I'll try the code if it ever appears again.

**Comment by codenotworking** [comment]
> ```python
> # existing code
> try:
>     #self.__sys_out("cookie popup cleared", 3)
>     WebDriverWait(driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.element_to_be_clickable((By.ID, "bnp_btn_accept"))).click()
> except TimeoutException:
>     #self.__sys_out("No cookie popup present", 3)
>     pass
> 
> 
> #new code to handle issue
> except selenium.common.exceptions.UnexpectedAlertPresentException:
>     alert = driver.switch_to.alert()
>     alert.accept()
> ```
Today, I received the `Want more relevant search results? Allow Bing to access your location. Click 'Allow' on the next prompt.` error message again.  I tried the above suggested code and receive a totally different error:
```python
DevTools listening on ws://127.0.0.1:53749/devtools/browser/779f0334-aa37-4840-b23d-043bf9e3e859
       >> Logging in
           << Successfully logged in
       >> Starting search
              >>> Progress: [###                           ] 10/100 (10%)Traceback (most recent call last):
  File "C:\Dropbox\Apps\BingRewards\src\rewards.py", line 256, in __search
    WebDriverWait(driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.element_to_be_clickable((By.ID, "bnp_btn_accept"))).click()
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 297, in __call__
    element = visibility_of_element_located(self.locator)(driver)
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 101, in find_element
    return self._dispatch("find", (by, value, self._driver), "find_element", (by, value))
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 160, in _dispatch
    raise e
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 157, in _dispatch
    result = getattr(self._driver, d_call)(*d_args)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: Want more relevant search results? Allow Bing to access your location. Click 'Allow' on the next prompt.
Message: unexpected alert open: {Alert text : Want more relevant search results? Allow Bing to access your location. Click 'Allow' on the next prompt.}
  (Session info: headless chrome=93.0.4577.63)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Dropbox\Apps\BingRewards\BingRewards.py", line 380, in <module>
    __main(args[0], arg1.replace("-", ""))
  File "C:\Dropbox\Apps\BingRewards\BingRewards.py", line 156, in __main
    rewards.complete_mobile_search(hist_log.get_search_hist())
  File "C:\Dropbox\Apps\BingRewards\src\rewards.py", line 962, in complete_mobile_search
    driver = self.__complete_mobile_search()
  File "C:\Dropbox\Apps\BingRewards\src\rewards.py", line 868, in __complete_mobile_search
    self.completion.mobile_search = self.__search(driver, Driver.MOBILE_DEVICE)
  File "C:\Dropbox\Apps\BingRewards\src\rewards.py", line 266, in __search
    alert = driver.switch_to.alert()
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\switch_to.py", line 55, in alert
    alert.text
  File "C:\Python38\lib\site-packages\selenium\webdriver\common\alert.py", line 67, in text
    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)["value"]
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoAlertPresentException: Message: no such alert
  (Session info: headless chrome=93.0.4577.63)
```
It seems the suggested code isn't working.  That stackoverflow link references [Selenium's alerts, prompts, and confirmations](https://www.selenium.dev/documentation/webdriver/js_alerts_prompts_and_confirmations/).  There is example code for detecting the element before clicking on it.  I managed to use Edge's device tool to simulate mobile search, and I received the popup.  But I couldn't find any element information when inspecting the page.  Once I manually clicked the "Ok" button, another popup appeared asking me to allow Edge to detect location.

I think the code first needs to somehow detect the first popup, in order to detect the "Allow" button which the suggested code from stackoverflow is mentioning.

**Comment by jjjchens235** [comment]
Closing after @glinesbdev  fix. Please reopen if further issues.
