### ISSUE TITLE
Lightspeed quiz error

### ISSUE THREAD

**Issue by webdeck** [jjjchens235/bing-rewards#84]
When bing-rewards took the Lightspeed quiz, it scored 0 out of 4.  Now it keeps trying to take it again on subsequent runs, and fails with this error:

```
       >> Trying Lightspeed quiz
Traceback (most recent call last):
  File "/Users/mriccio/src/bing-rewards/BingRewards/BingRewards.py", line 142, in <module>
    __main(args[0], arg1.replace("-", ""))
  File "/Users/mriccio/src/bing-rewards/BingRewards/BingRewards.py", line 100, in __main
    rewards.complete_offers()
  File "/Users/mriccio/src/bing-rewards/BingRewards/src/rewards.py", line 929, in complete_offers
    driver = self.__complete_offers()
  File "/Users/mriccio/src/bing-rewards/BingRewards/src/rewards.py", line 860, in __complete_offers
    self.completion.offers = self.__offers(driver)
  File "/Users/mriccio/src/bing-rewards/BingRewards/src/rewards.py", line 771, in __offers
    c = self.__click_offer(driver, offer, './div[2]/h3', './mee-rewards-points/div/div/span[1]', './div[2]/p', './div[3]/a/span/ng-transclude')
  File "/Users/mriccio/src/bing-rewards/BingRewards/src/rewards.py", line 674, in __click_offer
    offer.find_element_by_xpath(link_xpath).click()
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 226, in click
    self._dispatch("click", (self._webelement, self._driver), "click", ())
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 294, in _dispatch
    raise e
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 291, in _dispatch
    result = getattr(self._webelement, d_call)(*d_args)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (768, 1973)
  (Session info: headless chrome=91.0.4472.114)
```

**Comment by webdeck** [comment]
<img width="350" alt="Screen Shot 2021-07-20 at 6 56 49 AM" src="https://user-images.githubusercontent.com/5542961/126336748-655c3e06-e1fa-4f7b-807c-3859afb01f80.png">
<img width="1426" alt="Screen Shot 2021-07-20 at 6 56 59 AM" src="https://user-images.githubusercontent.com/5542961/126336761-3a1facda-96d8-406c-9741-ee8e338a7b36.png">

**Comment by connect-dots** [comment]
If it helps I had the same thing over the weekend, across my fam accounts. They all bombed out with the same message you had. I ran the script again in the evenings with the -b switch so at least all the searches registered and the streak count was kept. After a few days the scripts started to run fine and the lightspeed quiz completed correctly - without any intervention from me.

Give it a few days and see if it sorts itself out - might just be a bug. Lord knows there's enough in the rest of the MS ecosystem 😏

**Comment by jjjchens235** [comment]
It looks like lightspeed quiz runs correctly today, so I will close.
