### ISSUE TITLE
Error with dailey sets

### ISSUE THREAD

**Issue by PubgStarz** [jjjchens235/bing-rewards#85]
Hi I have a problem with the daily sets, it was working perfectly for a couple a week and now ive run into this error and ive got no clue to fix this...

```
Traceback (most recent call last):
  File "C:\BingRewards\ms_rewards_farmer.py", line 596, in <module>
    completeDailySet(browser)
  File "C:\BingRewards\ms_rewards_farmer.py", line 369, in completeDailySet
    d = getDashboardData(browser)['dailySetPromotions']
  File "C:\BingRewards\ms_rewards_farmer.py", line 365, in getDashboardData
    dashboard = json.loads(dashboard)
  File "C:\Users\M\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\M\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\M\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by shinji257** [comment]
I believe this is the wrong bot?  I know this bot and that repository is gone now.  It also started to give me the same error which has led me to search for a new bot and got this one now.

**Comment by jjjchens235** [comment]
I'm disappointed you're cheating on this bot with other ones!!
