### ISSUE TITLE
TLSv1 and TLSv1.1 not supported on Ubuntu 20.04+

### ISSUE THREAD

**Issue by binarymelon** [jjjchens235/bing-rewards#89]
I'm wondering if it would be possible to add a flag to use TLSv1.2?  By default Ubuntu 20.04+ do not support 1.0 and 1.1.

**Comment by WangZhuo2015** [comment]
I solved this problem by removing the TLS flag directly.

**Comment by jjjchens235** [comment]
It looks TLS is used once both in `driver.py` and `rewards.py`.
In both instances, there is exception handling for the TLS where that argument is not used on SSLerror
`        except ssl.SSLError as e:
            response = urlopen("https://sites.google.com/a/chromium.org/chromedriver/downloads").read()
`
Even with this except block, you're still getting an error? If so, can you please post your log.

**Comment by binarymelon** [comment]
```Traceback (most recent call last):
  File "/home/ryan/dev/bing-rewards/BingRewards/BingRewards.py", line 142, in <module>
    __main(args[0], arg1.replace("-", ""))
  File "/home/ryan/dev/bing-rewards/BingRewards/BingRewards.py", line 82, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "/home/ryan/dev/bing-rewards/BingRewards/src/rewards.py", line 941, in complete_all
    driver = self.__complete_edge_search()
  File "/home/ryan/dev/bing-rewards/BingRewards/src/rewards.py", line 787, in __complete_edge_search
    self.completion.edge_search = self.__search(driver, Driver.WEB_DEVICE, is_edge=True)
  File "/home/ryan/dev/bing-rewards/BingRewards/src/rewards.py", line 191, in __search
    last_request_time = self.__update_search_queries(trending_date, last_request_time)
  File "/home/ryan/dev/bing-rewards/BingRewards/src/rewards.py", line 163, in __update_search_queries
    response = urlopen(self.__TRENDS_URL.format(timestamp.strftime("%Y%m%d")), context=ssl.SSLContext(ssl.PROTOCOL_TLSv1))
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL] internal error (_ssl.c:1129)>```

**Comment by binarymelon** [comment]
I should also mention that as @WangZhuo2015 mentioned removing the version flag altogether also seems to work, but I have no idea if that change is backwards compatible.

**Comment by jjjchens235** [comment]
Thanks for the detailed logs. It sounds like you guys have a temporary fix, I will put on my back-log to add an extra except clause to catch this `URLError` exception, for both files.

**Comment by jjjchens235** [comment]
This should be fixed with the following update:
use `protocol_tls` instead of `protocol_tlsv1`

**Comment by binarymelon** [comment]
@jjjchens235 I'm not sure what versions you're planning to support, but PROTOCOL_TLS wasn't introduced until 3.6.

**Comment by jjjchens235** [comment]
Good callout, I think that's fine though, Python v3.5 is no longer supported by Python.
